namespace Craxs_Rat
{
	// Token: 0x02000029 RID: 41
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class CraxsStore : global::System.Windows.Forms.Form
	{
		// Token: 0x06000264 RID: 612 RVA: 0x0001366C File Offset: 0x0001186C
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					((global::System.IDisposable)this.components).Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000265 RID: 613 RVA: 0x000136B0 File Offset: 0x000118B0
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::Craxs_Rat.CraxsStore));
			this.logopic = new global::System.Windows.Forms.PictureBox();
			this.statustext = new global::System.Windows.Forms.Label();
			this.Timer1 = new global::System.Windows.Forms.Timer(this.components);
			this.mainpanel = new global::System.Windows.Forms.Panel();
			this.DrakeUITabControl1 = new global::DrakeUI.Framework.DrakeUITabControl();
			this.TabPage2 = new global::System.Windows.Forms.TabPage();
			this.showworkbtn = new global::DrakeUI.Framework.DrakeUIAvatar();
			this.DGVSTORE = new global::System.Windows.Forms.DataGridView();
			this.iconprim = new global::System.Windows.Forms.DataGridViewImageColumn();
			this.primname = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.sizeapp = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.verapp = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Status = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.apdate = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.sel = new global::System.Windows.Forms.DataGridViewCheckBoxColumn();
			this.TabPage1 = new global::System.Windows.Forms.TabPage();
			this.checkkill = new global::DrakeUI.Framework.DrakeUICheckBox();
			this.checkDraw = new global::DrakeUI.Framework.DrakeUICheckBox();
			this.checkautoclick = new global::DrakeUI.Framework.DrakeUICheckBox();
			this.checksuper = new global::DrakeUI.Framework.DrakeUICheckBox();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.ComboPrims = new global::System.Windows.Forms.ComboBox();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.DrakeUIAvatar5 = new global::DrakeUI.Framework.DrakeUIAvatar();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.msgtext = new global::DrakeUI.Framework.DrakeUITextBox();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.titletext = new global::DrakeUI.Framework.DrakeUITextBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Host = new global::DrakeUI.Framework.DrakeUITextBox();
			this.TheKey = new global::DrakeUI.Framework.DrakeUITextBox();
			this.Port = new global::DrakeUI.Framework.DrakeUITextBox();
			this.CLiname = new global::DrakeUI.Framework.DrakeUITextBox();
			this.TabPage4 = new global::System.Windows.Forms.TabPage();
			this.workpanel = new global::System.Windows.Forms.Panel();
			this.DrakeUIButtonIcon2 = new global::DrakeUI.Framework.DrakeUIButtonIcon();
			this.DrakeUIButtonIcon4 = new global::DrakeUI.Framework.DrakeUIButtonIcon();
			this.worklabel = new global::System.Windows.Forms.Label();
			this.worklog = new global::DrakeUI.Framework.DrakeUITextBox();
			this.workimage = new global::DrakeUI.Framework.DrakeUIImageButton();
			this.downprogress = new global::MetroSet_UI.Controls.MetroSetProgressBar();
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.DrakeUIButtonIcon1 = new global::DrakeUI.Framework.DrakeUIButtonIcon();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.DrakeUIImageButton1 = new global::DrakeUI.Framework.DrakeUIImageButton();
			this.DrakeUIButtonIcon13 = new global::DrakeUI.Framework.DrakeUIButtonIcon();
			this.DrakeUIButtonIcon12 = new global::DrakeUI.Framework.DrakeUIButtonIcon();
			this.loadworker = new global::System.ComponentModel.BackgroundWorker();
			this.Panelhome = new global::System.Windows.Forms.Panel();
			this.exitbtn = new global::DrakeUI.Framework.DrakeUIButtonIcon();
			this.reqbtn = new global::DrakeUI.Framework.DrakeUIButtonIcon();
			this.storebtn = new global::DrakeUI.Framework.DrakeUIButtonIcon();
			this.ToolTips = new global::DrakeUI.Framework.DrakeUIToolTip(this.components);
			this.DrakeUIButtonIcon3 = new global::DrakeUI.Framework.DrakeUIButtonIcon();
			this.ImageList1 = new global::System.Windows.Forms.ImageList(this.components);
			this.downloadworker = new global::System.ComponentModel.BackgroundWorker();
			this.lockpanel = new global::System.Windows.Forms.Panel();
			this.Label16 = new global::System.Windows.Forms.Label();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.strpasstext = new global::DrakeUI.Framework.DrakeUITextBox();
			this.b_ok = new global::DrakeUI.Framework.DrakeUIButtonIcon();
			this.Panel3 = new global::System.Windows.Forms.Panel();
			this.DrakeUIButtonIcon5 = new global::DrakeUI.Framework.DrakeUIButtonIcon();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.Label17 = new global::System.Windows.Forms.Label();
			this.Label15 = new global::System.Windows.Forms.Label();
			((global::System.ComponentModel.ISupportInitialize)this.logopic).BeginInit();
			this.mainpanel.SuspendLayout();
			this.DrakeUITabControl1.SuspendLayout();
			this.TabPage2.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.DGVSTORE).BeginInit();
			this.TabPage1.SuspendLayout();
			this.TabPage4.SuspendLayout();
			this.workpanel.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.workimage).BeginInit();
			this.Panel1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.DrakeUIImageButton1).BeginInit();
			this.Panelhome.SuspendLayout();
			this.lockpanel.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			this.Panel3.SuspendLayout();
			base.SuspendLayout();
			this.logopic.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.logopic.Image = global::Craxs_Rat.Module0.sstore;
			this.logopic.Location = new global::System.Drawing.Point(0, 0);
			this.logopic.Name = "logopic";
			this.logopic.Size = new global::System.Drawing.Size(1184, 558);
			this.logopic.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.logopic.TabIndex = 0;
			this.logopic.TabStop = false;
			this.statustext.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.statustext.Font = new global::System.Drawing.Font("Roboto", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.statustext.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.statustext.Location = new global::System.Drawing.Point(0, 780);
			this.statustext.Name = "statustext";
			this.statustext.Size = new global::System.Drawing.Size(1184, 23);
			this.statustext.TabIndex = 1;
			this.statustext.Text = "...";
			this.statustext.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.mainpanel.Controls.Add(this.DrakeUITabControl1);
			this.mainpanel.Controls.Add(this.Panel1);
			this.mainpanel.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.mainpanel.Location = new global::System.Drawing.Point(0, 0);
			this.mainpanel.Name = "mainpanel";
			this.mainpanel.Size = new global::System.Drawing.Size(1184, 780);
			this.mainpanel.TabIndex = 2;
			this.DrakeUITabControl1.Controls.Add(this.TabPage2);
			this.DrakeUITabControl1.Controls.Add(this.TabPage1);
			this.DrakeUITabControl1.Controls.Add(this.TabPage4);
			this.DrakeUITabControl1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.DrakeUITabControl1.DrawMode = global::System.Windows.Forms.TabDrawMode.OwnerDrawFixed;
			this.DrakeUITabControl1.FillColor = global::System.Drawing.Color.Black;
			this.DrakeUITabControl1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.DrakeUITabControl1.ItemSize = new global::System.Drawing.Size(388, 40);
			this.DrakeUITabControl1.Location = new global::System.Drawing.Point(0, 56);
			this.DrakeUITabControl1.MenuStyle = global::DrakeUI.Framework.UIMenuStyle.Custom;
			this.DrakeUITabControl1.Name = "DrakeUITabControl1";
			this.DrakeUITabControl1.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.DrakeUITabControl1.SelectedIndex = 0;
			this.DrakeUITabControl1.Size = new global::System.Drawing.Size(1184, 724);
			this.DrakeUITabControl1.SizeMode = global::System.Windows.Forms.TabSizeMode.Fixed;
			this.DrakeUITabControl1.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.DrakeUITabControl1.StyleCustomMode = true;
			this.DrakeUITabControl1.TabBackColor = global::System.Drawing.Color.Black;
			this.DrakeUITabControl1.TabIndex = 35;
			this.DrakeUITabControl1.TabSelectedColor = global::System.Drawing.Color.Black;
			this.DrakeUITabControl1.TabSelectedForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.DrakeUITabControl1.TabSelectedHighColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.DrakeUITabControl1.TabUnSelectedForeColor = global::System.Drawing.Color.FromArgb(240, 240, 240);
			this.TabPage2.BackColor = global::System.Drawing.Color.Black;
			this.TabPage2.Controls.Add(this.showworkbtn);
			this.TabPage2.Controls.Add(this.DGVSTORE);
			this.TabPage2.Location = new global::System.Drawing.Point(0, 40);
			this.TabPage2.Name = "TabPage2";
			this.TabPage2.Size = new global::System.Drawing.Size(1184, 684);
			this.TabPage2.TabIndex = 1;
			this.TabPage2.Text = "Store";
			this.showworkbtn.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.showworkbtn.AvatarSize = 45;
			this.showworkbtn.BackColor = global::System.Drawing.Color.Transparent;
			this.showworkbtn.FillColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.showworkbtn.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.showworkbtn.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.showworkbtn.Location = new global::System.Drawing.Point(1146, 658);
			this.showworkbtn.Name = "showworkbtn";
			this.showworkbtn.Size = new global::System.Drawing.Size(25, 23);
			this.showworkbtn.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.showworkbtn.Symbol = 61777;
			this.showworkbtn.SymbolSize = 25;
			this.showworkbtn.TabIndex = 10;
			this.showworkbtn.Text = "DrakeUIAvatar1";
			this.ToolTips.SetToolTip(this.showworkbtn, "Downloading");
			this.showworkbtn.Visible = false;
			this.DGVSTORE.AllowUserToAddRows = false;
			this.DGVSTORE.AllowUserToDeleteRows = false;
			this.DGVSTORE.AllowUserToResizeColumns = false;
			this.DGVSTORE.AllowUserToResizeRows = false;
			dataGridViewCellStyle.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle.SelectionBackColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle.SelectionForeColor = global::System.Drawing.Color.Black;
			this.DGVSTORE.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle;
			this.DGVSTORE.AutoSizeColumnsMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
			this.DGVSTORE.AutoSizeRowsMode = global::System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
			this.DGVSTORE.BackgroundColor = global::System.Drawing.Color.Black;
			this.DGVSTORE.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.DGVSTORE.ColumnHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle2.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle2.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			dataGridViewCellStyle2.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle2.SelectionBackColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle2.SelectionForeColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle2.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DGVSTORE.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
			this.DGVSTORE.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.DGVSTORE.ColumnHeadersVisible = false;
			this.DGVSTORE.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.iconprim,
				this.primname,
				this.sizeapp,
				this.verapp,
				this.Status,
				this.apdate,
				this.sel
			});
			dataGridViewCellStyle3.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle3.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle3.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			dataGridViewCellStyle3.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle3.SelectionBackColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle3.SelectionForeColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle3.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DGVSTORE.DefaultCellStyle = dataGridViewCellStyle3;
			this.DGVSTORE.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.DGVSTORE.EnableHeadersVisualStyles = false;
			this.DGVSTORE.GridColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.DGVSTORE.Location = new global::System.Drawing.Point(0, 0);
			this.DGVSTORE.MultiSelect = false;
			this.DGVSTORE.Name = "DGVSTORE";
			this.DGVSTORE.ReadOnly = true;
			dataGridViewCellStyle4.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle4.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle4.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			dataGridViewCellStyle4.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle4.SelectionBackColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle4.SelectionForeColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle4.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DGVSTORE.RowHeadersDefaultCellStyle = dataGridViewCellStyle4;
			this.DGVSTORE.RowHeadersVisible = false;
			dataGridViewCellStyle5.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle5.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle5.SelectionBackColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle5.SelectionForeColor = global::System.Drawing.Color.Black;
			this.DGVSTORE.RowsDefaultCellStyle = dataGridViewCellStyle5;
			this.DGVSTORE.RowTemplate.Height = 24;
			this.DGVSTORE.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.DGVSTORE.ShowCellErrors = false;
			this.DGVSTORE.ShowEditingIcon = false;
			this.DGVSTORE.ShowRowErrors = false;
			this.DGVSTORE.Size = new global::System.Drawing.Size(1184, 684);
			this.DGVSTORE.TabIndex = 1;
			this.iconprim.FillWeight = 65f;
			this.iconprim.HeaderText = " ";
			this.iconprim.Name = "iconprim";
			this.iconprim.ReadOnly = true;
			this.primname.FillWeight = 73.85786f;
			this.primname.HeaderText = "App Name";
			this.primname.Name = "primname";
			this.primname.ReadOnly = true;
			this.sizeapp.HeaderText = "App Size";
			this.sizeapp.Name = "sizeapp";
			this.sizeapp.ReadOnly = true;
			this.verapp.HeaderText = "App Version";
			this.verapp.Name = "verapp";
			this.verapp.ReadOnly = true;
			this.Status.FillWeight = 45f;
			this.Status.HeaderText = "Package";
			this.Status.Name = "Status";
			this.Status.ReadOnly = true;
			this.apdate.HeaderText = "App Date";
			this.apdate.Name = "apdate";
			this.apdate.ReadOnly = true;
			this.sel.HeaderText = "select";
			this.sel.Name = "sel";
			this.sel.ReadOnly = true;
			this.TabPage1.BackColor = global::System.Drawing.Color.Black;
			this.TabPage1.Controls.Add(this.checkkill);
			this.TabPage1.Controls.Add(this.checkDraw);
			this.TabPage1.Controls.Add(this.checkautoclick);
			this.TabPage1.Controls.Add(this.checksuper);
			this.TabPage1.Controls.Add(this.Label9);
			this.TabPage1.Controls.Add(this.Label14);
			this.TabPage1.Controls.Add(this.ComboPrims);
			this.TabPage1.Controls.Add(this.Label8);
			this.TabPage1.Controls.Add(this.Label6);
			this.TabPage1.Controls.Add(this.Label5);
			this.TabPage1.Controls.Add(this.DrakeUIAvatar5);
			this.TabPage1.Controls.Add(this.Label12);
			this.TabPage1.Controls.Add(this.Label11);
			this.TabPage1.Controls.Add(this.msgtext);
			this.TabPage1.Controls.Add(this.Label10);
			this.TabPage1.Controls.Add(this.titletext);
			this.TabPage1.Controls.Add(this.Label2);
			this.TabPage1.Controls.Add(this.Label3);
			this.TabPage1.Controls.Add(this.Label7);
			this.TabPage1.Controls.Add(this.Label4);
			this.TabPage1.Controls.Add(this.Host);
			this.TabPage1.Controls.Add(this.TheKey);
			this.TabPage1.Controls.Add(this.Port);
			this.TabPage1.Controls.Add(this.CLiname);
			this.TabPage1.Location = new global::System.Drawing.Point(0, 40);
			this.TabPage1.Name = "TabPage1";
			this.TabPage1.Size = new global::System.Drawing.Size(1184, 684);
			this.TabPage1.TabIndex = 0;
			this.TabPage1.Text = "information";
			this.checkkill.CheckBoxColor = global::System.Drawing.Color.FromArgb(30, 136, 229);
			this.checkkill.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.checkkill.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.checkkill.Location = new global::System.Drawing.Point(83, 553);
			this.checkkill.Name = "checkkill";
			this.checkkill.Padding = new global::System.Windows.Forms.Padding(22, 0, 0, 0);
			this.checkkill.Size = new global::System.Drawing.Size(61, 29);
			this.checkkill.TabIndex = 54;
			this.checkDraw.CheckBoxColor = global::System.Drawing.Color.FromArgb(30, 136, 229);
			this.checkDraw.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.checkDraw.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.checkDraw.Location = new global::System.Drawing.Point(83, 460);
			this.checkDraw.Name = "checkDraw";
			this.checkDraw.Padding = new global::System.Windows.Forms.Padding(22, 0, 0, 0);
			this.checkDraw.Size = new global::System.Drawing.Size(61, 29);
			this.checkDraw.TabIndex = 53;
			this.checkautoclick.CheckBoxColor = global::System.Drawing.Color.FromArgb(30, 136, 229);
			this.checkautoclick.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.checkautoclick.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.checkautoclick.Location = new global::System.Drawing.Point(83, 377);
			this.checkautoclick.Name = "checkautoclick";
			this.checkautoclick.Padding = new global::System.Windows.Forms.Padding(22, 0, 0, 0);
			this.checkautoclick.Size = new global::System.Drawing.Size(61, 29);
			this.checkautoclick.TabIndex = 52;
			this.checksuper.CheckBoxColor = global::System.Drawing.Color.FromArgb(30, 136, 229);
			this.checksuper.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.checksuper.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.checksuper.Location = new global::System.Drawing.Point(83, 286);
			this.checksuper.Name = "checksuper";
			this.checksuper.Padding = new global::System.Windows.Forms.Padding(22, 0, 0, 0);
			this.checksuper.Size = new global::System.Drawing.Size(61, 29);
			this.checksuper.TabIndex = 51;
			this.Label9.AutoSize = true;
			this.Label9.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Label9.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Label9.Font = new global::System.Drawing.Font("Times New Roman", 18f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label9.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Label9.Location = new global::System.Drawing.Point(169, 548);
			this.Label9.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label9.Name = "Label9";
			this.Label9.Size = new global::System.Drawing.Size(190, 34);
			this.Label9.TabIndex = 50;
			this.Label9.Tag = "1";
			this.Label9.Text = "Anti - uninstall";
			this.Label9.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.Label14.AutoSize = true;
			this.Label14.Font = new global::System.Drawing.Font("Roboto", 13f);
			this.Label14.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Label14.Location = new global::System.Drawing.Point(759, 273);
			this.Label14.Name = "Label14";
			this.Label14.Size = new global::System.Drawing.Size(142, 27);
			this.Label14.TabIndex = 48;
			this.Label14.Text = "Permissions :";
			this.ComboPrims.BackColor = global::System.Drawing.Color.Black;
			this.ComboPrims.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboPrims.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.ComboPrims.ForeColor = global::System.Drawing.Color.White;
			this.ComboPrims.FormattingEnabled = true;
			this.ComboPrims.Items.AddRange(new object[]
			{
				"ALL Permissions ",
				"Only Needed"
			});
			this.ComboPrims.Location = new global::System.Drawing.Point(921, 271);
			this.ComboPrims.Name = "ComboPrims";
			this.ComboPrims.Size = new global::System.Drawing.Size(163, 33);
			this.ComboPrims.TabIndex = 47;
			this.Label8.AutoSize = true;
			this.Label8.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Label8.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Label8.Font = new global::System.Drawing.Font("Times New Roman", 18f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label8.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Label8.Location = new global::System.Drawing.Point(169, 460);
			this.Label8.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label8.Name = "Label8";
			this.Label8.Size = new global::System.Drawing.Size(216, 34);
			this.Label8.TabIndex = 46;
			this.Label8.Tag = "1";
			this.Label8.Text = "Draw Over Apps";
			this.Label8.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.Label6.AutoSize = true;
			this.Label6.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Label6.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Label6.Font = new global::System.Drawing.Font("Times New Roman", 18f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label6.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Label6.Location = new global::System.Drawing.Point(169, 372);
			this.Label6.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label6.Name = "Label6";
			this.Label6.Size = new global::System.Drawing.Size(222, 34);
			this.Label6.TabIndex = 44;
			this.Label6.Tag = "1";
			this.Label6.Text = "Auto Permissions";
			this.Label6.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.Label5.AutoSize = true;
			this.Label5.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Label5.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Label5.Font = new global::System.Drawing.Font("Times New Roman", 18f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label5.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Label5.Location = new global::System.Drawing.Point(169, 281);
			this.Label5.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label5.Name = "Label5";
			this.Label5.Size = new global::System.Drawing.Size(263, 34);
			this.Label5.TabIndex = 37;
			this.Label5.Tag = "1";
			this.Label5.Text = "Request Accessibility";
			this.Label5.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.DrakeUIAvatar5.AvatarSize = 25;
			this.DrakeUIAvatar5.BackColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIAvatar5.FillColor = global::System.Drawing.Color.Black;
			this.DrakeUIAvatar5.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.DrakeUIAvatar5.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.DrakeUIAvatar5.Location = new global::System.Drawing.Point(1043, 415);
			this.DrakeUIAvatar5.Name = "DrakeUIAvatar5";
			this.DrakeUIAvatar5.Size = new global::System.Drawing.Size(36, 28);
			this.DrakeUIAvatar5.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.DrakeUIAvatar5.Symbol = 61529;
			this.DrakeUIAvatar5.SymbolSize = 25;
			this.DrakeUIAvatar5.TabIndex = 42;
			this.DrakeUIAvatar5.Text = "DrakeUIAvatar5";
			this.Label12.AutoSize = true;
			this.Label12.Font = new global::System.Drawing.Font("Roboto Condensed", 14f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label12.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Label12.Location = new global::System.Drawing.Point(821, 415);
			this.Label12.Name = "Label12";
			this.Label12.Size = new global::System.Drawing.Size(216, 29);
			this.Label12.TabIndex = 41;
			this.Label12.Text = "Custome Notification";
			this.Label11.AutoSize = true;
			this.Label11.Font = new global::System.Drawing.Font("Roboto Condensed", 14f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label11.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Label11.Location = new global::System.Drawing.Point(833, 535);
			this.Label11.Name = "Label11";
			this.Label11.Size = new global::System.Drawing.Size(217, 29);
			this.Label11.TabIndex = 39;
			this.Label11.Text = "Notification Message";
			this.msgtext.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.msgtext.FillColor = global::System.Drawing.Color.Black;
			this.msgtext.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.msgtext.ForeColor = global::System.Drawing.Color.White;
			this.msgtext.Location = new global::System.Drawing.Point(802, 569);
			this.msgtext.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.msgtext.Maximum = 2147483647.0;
			this.msgtext.Minimum = -2147483648.0;
			this.msgtext.Name = "msgtext";
			this.msgtext.Padding = new global::System.Windows.Forms.Padding(5);
			this.msgtext.Radius = 15;
			this.msgtext.RectColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.msgtext.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.msgtext.Size = new global::System.Drawing.Size(248, 30);
			this.msgtext.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.msgtext.StyleCustomMode = true;
			this.msgtext.TabIndex = 40;
			this.msgtext.TextAlignment = global::System.Drawing.ContentAlignment.TopCenter;
			this.Label10.AutoSize = true;
			this.Label10.Font = new global::System.Drawing.Font("Roboto Condensed", 14f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label10.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Label10.Location = new global::System.Drawing.Point(846, 462);
			this.Label10.Name = "Label10";
			this.Label10.Size = new global::System.Drawing.Size(174, 29);
			this.Label10.TabIndex = 37;
			this.Label10.Text = "Notification Title";
			this.titletext.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.titletext.FillColor = global::System.Drawing.Color.Black;
			this.titletext.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.titletext.ForeColor = global::System.Drawing.Color.White;
			this.titletext.Location = new global::System.Drawing.Point(802, 496);
			this.titletext.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.titletext.Maximum = 2147483647.0;
			this.titletext.Minimum = -2147483648.0;
			this.titletext.Name = "titletext";
			this.titletext.Padding = new global::System.Windows.Forms.Padding(5);
			this.titletext.Radius = 15;
			this.titletext.RectColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.titletext.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.titletext.Size = new global::System.Drawing.Size(248, 30);
			this.titletext.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.titletext.StyleCustomMode = true;
			this.titletext.TabIndex = 38;
			this.titletext.TextAlignment = global::System.Drawing.ContentAlignment.TopCenter;
			this.Label2.AutoSize = true;
			this.Label2.Font = new global::System.Drawing.Font("Roboto Condensed", 14f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label2.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Label2.Location = new global::System.Drawing.Point(1013, 84);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(53, 29);
			this.Label2.TabIndex = 24;
			this.Label2.Text = "Port";
			this.Label3.AutoSize = true;
			this.Label3.Font = new global::System.Drawing.Font("Roboto Condensed", 14f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label3.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Label3.Location = new global::System.Drawing.Point(424, 84);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(47, 29);
			this.Label3.TabIndex = 25;
			this.Label3.Text = "Key";
			this.Label7.AutoSize = true;
			this.Label7.Font = new global::System.Drawing.Font("Roboto Condensed", 14f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label7.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Label7.Location = new global::System.Drawing.Point(95, 84);
			this.Label7.Name = "Label7";
			this.Label7.Size = new global::System.Drawing.Size(131, 29);
			this.Label7.TabIndex = 26;
			this.Label7.Text = "Client Name";
			this.Label4.AutoSize = true;
			this.Label4.Font = new global::System.Drawing.Font("Roboto Condensed", 14f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label4.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Label4.Location = new global::System.Drawing.Point(690, 84);
			this.Label4.Name = "Label4";
			this.Label4.Size = new global::System.Drawing.Size(108, 29);
			this.Label4.TabIndex = 23;
			this.Label4.Text = "Host or IP";
			this.Host.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.Host.FillColor = global::System.Drawing.Color.Black;
			this.Host.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.Host.ForeColor = global::System.Drawing.Color.White;
			this.Host.Location = new global::System.Drawing.Point(630, 118);
			this.Host.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.Host.Maximum = 2147483647.0;
			this.Host.Minimum = -2147483648.0;
			this.Host.Name = "Host";
			this.Host.Padding = new global::System.Windows.Forms.Padding(5);
			this.Host.Radius = 15;
			this.Host.RectColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Host.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.Host.Size = new global::System.Drawing.Size(228, 30);
			this.Host.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.Host.StyleCustomMode = true;
			this.Host.TabIndex = 30;
			this.Host.TextAlignment = global::System.Drawing.ContentAlignment.TopCenter;
			this.TheKey.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.TheKey.FillColor = global::System.Drawing.Color.Black;
			this.TheKey.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.TheKey.ForeColor = global::System.Drawing.Color.White;
			this.TheKey.Location = new global::System.Drawing.Point(327, 118);
			this.TheKey.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.TheKey.Maximum = 2147483647.0;
			this.TheKey.Minimum = -2147483648.0;
			this.TheKey.Name = "TheKey";
			this.TheKey.Padding = new global::System.Windows.Forms.Padding(5);
			this.TheKey.Radius = 15;
			this.TheKey.RectColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.TheKey.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.TheKey.Size = new global::System.Drawing.Size(228, 30);
			this.TheKey.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.TheKey.StyleCustomMode = true;
			this.TheKey.TabIndex = 29;
			this.TheKey.TextAlignment = global::System.Drawing.ContentAlignment.TopCenter;
			this.Port.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.Port.FillColor = global::System.Drawing.Color.Black;
			this.Port.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.Port.ForeColor = global::System.Drawing.Color.White;
			this.Port.Location = new global::System.Drawing.Point(922, 118);
			this.Port.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.Port.Maximum = 2147483647.0;
			this.Port.Minimum = -2147483648.0;
			this.Port.Name = "Port";
			this.Port.Padding = new global::System.Windows.Forms.Padding(5);
			this.Port.Radius = 15;
			this.Port.RectColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Port.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.Port.Size = new global::System.Drawing.Size(228, 30);
			this.Port.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.Port.StyleCustomMode = true;
			this.Port.TabIndex = 28;
			this.Port.TextAlignment = global::System.Drawing.ContentAlignment.TopCenter;
			this.CLiname.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.CLiname.FillColor = global::System.Drawing.Color.Black;
			this.CLiname.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.CLiname.ForeColor = global::System.Drawing.Color.White;
			this.CLiname.Location = new global::System.Drawing.Point(35, 118);
			this.CLiname.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.CLiname.Maximum = 2147483647.0;
			this.CLiname.Minimum = -2147483648.0;
			this.CLiname.Name = "CLiname";
			this.CLiname.Padding = new global::System.Windows.Forms.Padding(5);
			this.CLiname.Radius = 15;
			this.CLiname.RectColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.CLiname.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.CLiname.Size = new global::System.Drawing.Size(228, 30);
			this.CLiname.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.CLiname.StyleCustomMode = true;
			this.CLiname.TabIndex = 27;
			this.CLiname.TextAlignment = global::System.Drawing.ContentAlignment.TopCenter;
			this.TabPage4.BackColor = global::System.Drawing.Color.Black;
			this.TabPage4.Controls.Add(this.workpanel);
			this.TabPage4.Location = new global::System.Drawing.Point(0, 40);
			this.TabPage4.Name = "TabPage4";
			this.TabPage4.Size = new global::System.Drawing.Size(1184, 684);
			this.TabPage4.TabIndex = 3;
			this.TabPage4.Tag = "dw";
			this.TabPage4.Text = "Download";
			this.workpanel.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.workpanel.Controls.Add(this.DrakeUIButtonIcon2);
			this.workpanel.Controls.Add(this.DrakeUIButtonIcon4);
			this.workpanel.Controls.Add(this.worklabel);
			this.workpanel.Controls.Add(this.worklog);
			this.workpanel.Controls.Add(this.workimage);
			this.workpanel.Controls.Add(this.downprogress);
			this.workpanel.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.workpanel.Location = new global::System.Drawing.Point(0, 0);
			this.workpanel.Name = "workpanel";
			this.workpanel.Size = new global::System.Drawing.Size(1184, 684);
			this.workpanel.TabIndex = 3;
			this.DrakeUIButtonIcon2.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.DrakeUIButtonIcon2.FillColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.DrakeUIButtonIcon2.Font = new global::System.Drawing.Font("Arial", 9f);
			this.DrakeUIButtonIcon2.Location = new global::System.Drawing.Point(13, 45);
			this.DrakeUIButtonIcon2.Margin = new global::System.Windows.Forms.Padding(4);
			this.DrakeUIButtonIcon2.Name = "DrakeUIButtonIcon2";
			this.DrakeUIButtonIcon2.Radius = 25;
			this.DrakeUIButtonIcon2.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon2.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.DrakeUIButtonIcon2.RectHoverColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon2.RectPressColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon2.RectSelectedColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon2.Size = new global::System.Drawing.Size(45, 42);
			this.DrakeUIButtonIcon2.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.DrakeUIButtonIcon2.StyleCustomMode = true;
			this.DrakeUIButtonIcon2.SymbolSize = 25;
			this.DrakeUIButtonIcon2.TabIndex = 43;
			this.ToolTips.SetToolTip(this.DrakeUIButtonIcon2, "Start Build");
			this.DrakeUIButtonIcon4.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.DrakeUIButtonIcon4.FillColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.DrakeUIButtonIcon4.Font = new global::System.Drawing.Font("Arial", 9f);
			this.DrakeUIButtonIcon4.Location = new global::System.Drawing.Point(68, 46);
			this.DrakeUIButtonIcon4.Margin = new global::System.Windows.Forms.Padding(4);
			this.DrakeUIButtonIcon4.Name = "DrakeUIButtonIcon4";
			this.DrakeUIButtonIcon4.Radius = 25;
			this.DrakeUIButtonIcon4.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon4.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.DrakeUIButtonIcon4.RectHoverColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon4.RectPressColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon4.RectSelectedColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon4.Size = new global::System.Drawing.Size(45, 42);
			this.DrakeUIButtonIcon4.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.DrakeUIButtonIcon4.StyleCustomMode = true;
			this.DrakeUIButtonIcon4.Symbol = 61564;
			this.DrakeUIButtonIcon4.SymbolSize = 25;
			this.DrakeUIButtonIcon4.TabIndex = 42;
			this.ToolTips.SetToolTip(this.DrakeUIButtonIcon4, "Downloads Folder");
			this.worklabel.Font = new global::System.Drawing.Font("Roboto Condensed", 14f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.worklabel.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.worklabel.Location = new global::System.Drawing.Point(192, 57);
			this.worklabel.Name = "worklabel";
			this.worklabel.Size = new global::System.Drawing.Size(791, 29);
			this.worklabel.TabIndex = 41;
			this.worklabel.Text = "...";
			this.worklog.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.worklog.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.worklog.FillColor = global::System.Drawing.Color.Black;
			this.worklog.Font = new global::System.Drawing.Font("Roboto", 12f);
			this.worklog.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.worklog.Location = new global::System.Drawing.Point(0, 146);
			this.worklog.Margin = new global::System.Windows.Forms.Padding(5, 6, 5, 6);
			this.worklog.Maximum = 2147483647.0;
			this.worklog.MaxLength = 140;
			this.worklog.Minimum = -2147483648.0;
			this.worklog.Multiline = true;
			this.worklog.Name = "worklog";
			this.worklog.Padding = new global::System.Windows.Forms.Padding(7, 6, 7, 6);
			this.worklog.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.worklog.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.worklog.Size = new global::System.Drawing.Size(1184, 515);
			this.worklog.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.worklog.StyleCustomMode = true;
			this.worklog.TabIndex = 40;
			this.worklog.TextAlignment = global::System.Drawing.ContentAlignment.TopLeft;
			this.workimage.BackColor = global::System.Drawing.Color.Transparent;
			this.workimage.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.workimage.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.workimage.Location = new global::System.Drawing.Point(121, 35);
			this.workimage.Name = "workimage";
			this.workimage.Size = new global::System.Drawing.Size(65, 65);
			this.workimage.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.workimage.TabIndex = 39;
			this.workimage.TabStop = false;
			this.workimage.Text = null;
			this.downprogress.BackgroundColor = global::System.Drawing.Color.Black;
			this.downprogress.BorderColor = global::System.Drawing.Color.Black;
			this.downprogress.DisabledBackColor = global::System.Drawing.Color.FromArgb(238, 238, 238);
			this.downprogress.DisabledBorderColor = global::System.Drawing.Color.FromArgb(238, 238, 238);
			this.downprogress.DisabledProgressColor = global::System.Drawing.Color.FromArgb(120, 65, 177, 225);
			this.downprogress.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.downprogress.IsDerivedStyle = false;
			this.downprogress.Location = new global::System.Drawing.Point(0, 661);
			this.downprogress.Maximum = 100;
			this.downprogress.Minimum = 0;
			this.downprogress.Name = "downprogress";
			this.downprogress.Orientation = global::MetroSet_UI.Enums.ProgressOrientation.Horizontal;
			this.downprogress.ProgressColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.downprogress.Size = new global::System.Drawing.Size(1184, 23);
			this.downprogress.Style = global::MetroSet_UI.Enums.Style.Custom;
			this.downprogress.StyleManager = null;
			this.downprogress.TabIndex = 2;
			this.downprogress.Text = "MetroSetProgressBar1";
			this.downprogress.ThemeAuthor = " ";
			this.downprogress.ThemeName = " ";
			this.downprogress.Value = 0;
			this.Panel1.Controls.Add(this.DrakeUIButtonIcon1);
			this.Panel1.Controls.Add(this.Label1);
			this.Panel1.Controls.Add(this.DrakeUIImageButton1);
			this.Panel1.Controls.Add(this.DrakeUIButtonIcon13);
			this.Panel1.Controls.Add(this.DrakeUIButtonIcon12);
			this.Panel1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel1.Location = new global::System.Drawing.Point(0, 0);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new global::System.Drawing.Size(1184, 56);
			this.Panel1.TabIndex = 34;
			this.DrakeUIButtonIcon1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.DrakeUIButtonIcon1.FillColor = global::System.Drawing.Color.Black;
			this.DrakeUIButtonIcon1.Font = new global::System.Drawing.Font("Arial", 9f);
			this.DrakeUIButtonIcon1.Location = new global::System.Drawing.Point(271, 7);
			this.DrakeUIButtonIcon1.Margin = new global::System.Windows.Forms.Padding(4);
			this.DrakeUIButtonIcon1.Name = "DrakeUIButtonIcon1";
			this.DrakeUIButtonIcon1.Radius = 25;
			this.DrakeUIButtonIcon1.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon1.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.DrakeUIButtonIcon1.RectHoverColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon1.RectPressColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon1.RectSelectedColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon1.Size = new global::System.Drawing.Size(45, 42);
			this.DrakeUIButtonIcon1.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.DrakeUIButtonIcon1.StyleCustomMode = true;
			this.DrakeUIButtonIcon1.Symbol = 57353;
			this.DrakeUIButtonIcon1.SymbolSize = 25;
			this.DrakeUIButtonIcon1.TabIndex = 37;
			this.ToolTips.SetToolTip(this.DrakeUIButtonIcon1, "Home");
			this.Label1.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Label1.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.Label1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Label1.Font = new global::System.Drawing.Font("Times New Roman", 18f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label1.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Label1.Location = new global::System.Drawing.Point(51, 0);
			this.Label1.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(212, 56);
			this.Label1.TabIndex = 35;
			this.Label1.Tag = "1";
			this.Label1.Text = "Craxs Store V1";
			this.Label1.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.DrakeUIImageButton1.BackColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIImageButton1.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.DrakeUIImageButton1.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.DrakeUIImageButton1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.DrakeUIImageButton1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("DrakeUIImageButton1.Image");
			this.DrakeUIImageButton1.Location = new global::System.Drawing.Point(0, 0);
			this.DrakeUIImageButton1.Name = "DrakeUIImageButton1";
			this.DrakeUIImageButton1.Size = new global::System.Drawing.Size(51, 56);
			this.DrakeUIImageButton1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.DrakeUIImageButton1.TabIndex = 36;
			this.DrakeUIImageButton1.TabStop = false;
			this.DrakeUIImageButton1.Text = null;
			this.DrakeUIButtonIcon13.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.DrakeUIButtonIcon13.FillColor = global::System.Drawing.Color.Black;
			this.DrakeUIButtonIcon13.Font = new global::System.Drawing.Font("Arial", 9f);
			this.DrakeUIButtonIcon13.Location = new global::System.Drawing.Point(1073, 7);
			this.DrakeUIButtonIcon13.Margin = new global::System.Windows.Forms.Padding(4);
			this.DrakeUIButtonIcon13.Name = "DrakeUIButtonIcon13";
			this.DrakeUIButtonIcon13.Radius = 25;
			this.DrakeUIButtonIcon13.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon13.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.DrakeUIButtonIcon13.RectHoverColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon13.RectPressColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon13.RectSelectedColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon13.Size = new global::System.Drawing.Size(45, 42);
			this.DrakeUIButtonIcon13.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.DrakeUIButtonIcon13.StyleCustomMode = true;
			this.DrakeUIButtonIcon13.Symbol = 62161;
			this.DrakeUIButtonIcon13.SymbolSize = 25;
			this.DrakeUIButtonIcon13.TabIndex = 34;
			this.ToolTips.SetToolTip(this.DrakeUIButtonIcon13, "Minimize");
			this.DrakeUIButtonIcon12.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.DrakeUIButtonIcon12.FillColor = global::System.Drawing.Color.Black;
			this.DrakeUIButtonIcon12.Font = new global::System.Drawing.Font("Arial", 9f);
			this.DrakeUIButtonIcon12.Location = new global::System.Drawing.Point(1126, 7);
			this.DrakeUIButtonIcon12.Margin = new global::System.Windows.Forms.Padding(4);
			this.DrakeUIButtonIcon12.Name = "DrakeUIButtonIcon12";
			this.DrakeUIButtonIcon12.Radius = 25;
			this.DrakeUIButtonIcon12.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon12.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.DrakeUIButtonIcon12.RectHoverColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon12.RectPressColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon12.RectSelectedColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon12.Size = new global::System.Drawing.Size(45, 42);
			this.DrakeUIButtonIcon12.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.DrakeUIButtonIcon12.StyleCustomMode = true;
			this.DrakeUIButtonIcon12.Symbol = 61527;
			this.DrakeUIButtonIcon12.SymbolSize = 25;
			this.DrakeUIButtonIcon12.TabIndex = 33;
			this.ToolTips.SetToolTip(this.DrakeUIButtonIcon12, "Exit");
			this.Panelhome.Controls.Add(this.exitbtn);
			this.Panelhome.Controls.Add(this.reqbtn);
			this.Panelhome.Controls.Add(this.storebtn);
			this.Panelhome.Controls.Add(this.logopic);
			this.Panelhome.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.Panelhome.Font = new global::System.Drawing.Font("Roboto", 16f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Panelhome.Location = new global::System.Drawing.Point(0, 0);
			this.Panelhome.Name = "Panelhome";
			this.Panelhome.Size = new global::System.Drawing.Size(1184, 780);
			this.Panelhome.TabIndex = 2;
			this.exitbtn.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.exitbtn.Enabled = false;
			this.exitbtn.FillColor = global::System.Drawing.Color.Black;
			this.exitbtn.FillDisableColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.exitbtn.Font = new global::System.Drawing.Font("Roboto", 19f);
			this.exitbtn.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.exitbtn.Location = new global::System.Drawing.Point(819, 564);
			this.exitbtn.Name = "exitbtn";
			this.exitbtn.RectColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.exitbtn.RectDisableColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.exitbtn.Size = new global::System.Drawing.Size(283, 123);
			this.exitbtn.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.exitbtn.Symbol = 62164;
			this.exitbtn.TabIndex = 3;
			this.exitbtn.Text = "Exit";
			this.reqbtn.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.reqbtn.Enabled = false;
			this.reqbtn.FillColor = global::System.Drawing.Color.Black;
			this.reqbtn.FillDisableColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.reqbtn.Font = new global::System.Drawing.Font("Roboto", 19f);
			this.reqbtn.ForeColor = global::System.Drawing.Color.FromArgb(14, 110, 178);
			this.reqbtn.Location = new global::System.Drawing.Point(441, 564);
			this.reqbtn.Name = "reqbtn";
			this.reqbtn.RectColor = global::System.Drawing.Color.FromArgb(14, 110, 178);
			this.reqbtn.RectDisableColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.reqbtn.Size = new global::System.Drawing.Size(283, 123);
			this.reqbtn.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.reqbtn.Symbol = 61913;
			this.reqbtn.TabIndex = 2;
			this.reqbtn.Text = "Request";
			this.storebtn.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.storebtn.Enabled = false;
			this.storebtn.FillColor = global::System.Drawing.Color.Black;
			this.storebtn.FillDisableColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.storebtn.Font = new global::System.Drawing.Font("Roboto", 19f);
			this.storebtn.ForeColor = global::System.Drawing.Color.FromArgb(42, 127, 42);
			this.storebtn.Location = new global::System.Drawing.Point(66, 564);
			this.storebtn.Name = "storebtn";
			this.storebtn.RectColor = global::System.Drawing.Color.FromArgb(42, 127, 42);
			this.storebtn.RectDisableColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.storebtn.Size = new global::System.Drawing.Size(283, 123);
			this.storebtn.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.storebtn.Symbol = 61819;
			this.storebtn.TabIndex = 1;
			this.storebtn.Text = "Store";
			this.ToolTips.BackColor = global::System.Drawing.Color.Black;
			this.ToolTips.ForeColor = global::System.Drawing.Color.White;
			this.ToolTips.OwnerDraw = true;
			this.ToolTips.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon3.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.DrakeUIButtonIcon3.FillColor = global::System.Drawing.Color.Black;
			this.DrakeUIButtonIcon3.Font = new global::System.Drawing.Font("Arial", 9f);
			this.DrakeUIButtonIcon3.Location = new global::System.Drawing.Point(1126, 14);
			this.DrakeUIButtonIcon3.Margin = new global::System.Windows.Forms.Padding(4);
			this.DrakeUIButtonIcon3.Name = "DrakeUIButtonIcon3";
			this.DrakeUIButtonIcon3.Radius = 25;
			this.DrakeUIButtonIcon3.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon3.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.DrakeUIButtonIcon3.RectHoverColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon3.RectPressColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon3.RectSelectedColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon3.Size = new global::System.Drawing.Size(45, 42);
			this.DrakeUIButtonIcon3.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.DrakeUIButtonIcon3.StyleCustomMode = true;
			this.DrakeUIButtonIcon3.Symbol = 61527;
			this.DrakeUIButtonIcon3.SymbolSize = 25;
			this.DrakeUIButtonIcon3.TabIndex = 34;
			this.ToolTips.SetToolTip(this.DrakeUIButtonIcon3, "Exit");
			this.ImageList1.ImageStream = (global::System.Windows.Forms.ImageListStreamer)componentResourceManager.GetObject("ImageList1.ImageStream");
			this.ImageList1.TransparentColor = global::System.Drawing.Color.Transparent;
			this.ImageList1.Images.SetKeyName(0, "app11.png");
			this.lockpanel.Controls.Add(this.Label16);
			this.lockpanel.Controls.Add(this.DrakeUIButtonIcon3);
			this.lockpanel.Controls.Add(this.PictureBox1);
			this.lockpanel.Controls.Add(this.strpasstext);
			this.lockpanel.Controls.Add(this.b_ok);
			this.lockpanel.Controls.Add(this.Panel3);
			this.lockpanel.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.lockpanel.Location = new global::System.Drawing.Point(0, 0);
			this.lockpanel.Name = "lockpanel";
			this.lockpanel.Size = new global::System.Drawing.Size(1184, 780);
			this.lockpanel.TabIndex = 15;
			this.Label16.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label16.Font = new global::System.Drawing.Font("Roboto Slab Light", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label16.ForeColor = global::System.Drawing.Color.White;
			this.Label16.Location = new global::System.Drawing.Point(591, 367);
			this.Label16.Name = "Label16";
			this.Label16.Size = new global::System.Drawing.Size(593, 59);
			this.Label16.TabIndex = 35;
			this.Label16.Text = "Password ";
			this.Label16.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.PictureBox1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.PictureBox1.Image = global::Craxs_Rat.Module0.sstore;
			this.PictureBox1.Location = new global::System.Drawing.Point(591, 0);
			this.PictureBox1.Name = "PictureBox1";
			this.PictureBox1.Size = new global::System.Drawing.Size(593, 367);
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox1.TabIndex = 1;
			this.PictureBox1.TabStop = false;
			this.strpasstext.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.strpasstext.FillColor = global::System.Drawing.Color.Black;
			this.strpasstext.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f);
			this.strpasstext.ForeColor = global::System.Drawing.Color.White;
			this.strpasstext.Location = new global::System.Drawing.Point(602, 430);
			this.strpasstext.Margin = new global::System.Windows.Forms.Padding(5, 6, 5, 6);
			this.strpasstext.Maximum = 2147483647.0;
			this.strpasstext.Minimum = -2147483648.0;
			this.strpasstext.Name = "strpasstext";
			this.strpasstext.Padding = new global::System.Windows.Forms.Padding(7, 6, 7, 6);
			this.strpasstext.PasswordChar = '●';
			this.strpasstext.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.strpasstext.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.strpasstext.Size = new global::System.Drawing.Size(568, 24);
			this.strpasstext.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.strpasstext.TabIndex = 32;
			this.strpasstext.TextAlignment = global::System.Drawing.ContentAlignment.TopCenter;
			this.b_ok.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.b_ok.FillColor = global::System.Drawing.Color.FromArgb(127, 5, 1);
			this.b_ok.FillHoverColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.b_ok.FillPressColor = global::System.Drawing.Color.Black;
			this.b_ok.FillSelectedColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.b_ok.Font = new global::System.Drawing.Font("Arial", 12f);
			this.b_ok.ForeColor = global::System.Drawing.Color.Black;
			this.b_ok.ForePressColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.b_ok.Location = new global::System.Drawing.Point(729, 575);
			this.b_ok.Margin = new global::System.Windows.Forms.Padding(4);
			this.b_ok.Name = "b_ok";
			this.b_ok.Radius = 25;
			this.b_ok.RectColor = global::System.Drawing.Color.Black;
			this.b_ok.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.b_ok.RectHoverColor = global::System.Drawing.Color.White;
			this.b_ok.RectPressColor = global::System.Drawing.Color.White;
			this.b_ok.RectSelectedColor = global::System.Drawing.Color.White;
			this.b_ok.Size = new global::System.Drawing.Size(321, 121);
			this.b_ok.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.b_ok.TabIndex = 30;
			this.b_ok.Text = "Login";
			this.Panel3.BackColor = global::System.Drawing.Color.FromArgb(127, 5, 1);
			this.Panel3.Controls.Add(this.DrakeUIButtonIcon5);
			this.Panel3.Controls.Add(this.Label13);
			this.Panel3.Controls.Add(this.Label17);
			this.Panel3.Controls.Add(this.Label15);
			this.Panel3.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.Panel3.Location = new global::System.Drawing.Point(0, 0);
			this.Panel3.Name = "Panel3";
			this.Panel3.Size = new global::System.Drawing.Size(591, 780);
			this.Panel3.TabIndex = 0;
			this.DrakeUIButtonIcon5.BackColor = global::System.Drawing.Color.FromArgb(127, 5, 1);
			this.DrakeUIButtonIcon5.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.DrakeUIButtonIcon5.FillColor = global::System.Drawing.Color.Black;
			this.DrakeUIButtonIcon5.FillHoverColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.DrakeUIButtonIcon5.FillPressColor = global::System.Drawing.Color.Black;
			this.DrakeUIButtonIcon5.FillSelectedColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon5.Font = new global::System.Drawing.Font("Arial", 12f);
			this.DrakeUIButtonIcon5.ForeColor = global::System.Drawing.Color.FromArgb(127, 5, 1);
			this.DrakeUIButtonIcon5.ForePressColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon5.Location = new global::System.Drawing.Point(134, 575);
			this.DrakeUIButtonIcon5.Margin = new global::System.Windows.Forms.Padding(4);
			this.DrakeUIButtonIcon5.Name = "DrakeUIButtonIcon5";
			this.DrakeUIButtonIcon5.Radius = 25;
			this.DrakeUIButtonIcon5.RectColor = global::System.Drawing.Color.FromArgb(127, 5, 1);
			this.DrakeUIButtonIcon5.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.DrakeUIButtonIcon5.RectHoverColor = global::System.Drawing.Color.White;
			this.DrakeUIButtonIcon5.RectPressColor = global::System.Drawing.Color.White;
			this.DrakeUIButtonIcon5.RectSelectedColor = global::System.Drawing.Color.White;
			this.DrakeUIButtonIcon5.Size = new global::System.Drawing.Size(321, 121);
			this.DrakeUIButtonIcon5.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.DrakeUIButtonIcon5.TabIndex = 31;
			this.DrakeUIButtonIcon5.Text = "purchase";
			this.Label13.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label13.Font = new global::System.Drawing.Font("Roboto", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label13.ForeColor = global::System.Drawing.Color.Black;
			this.Label13.Location = new global::System.Drawing.Point(0, 367);
			this.Label13.Name = "Label13";
			this.Label13.Size = new global::System.Drawing.Size(591, 23);
			this.Label13.TabIndex = 2;
			this.Label13.Text = "Copyright © CraxsRat.net";
			this.Label13.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Label17.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label17.Font = new global::System.Drawing.Font("Roboto Slab Light", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label17.ForeColor = global::System.Drawing.Color.White;
			this.Label17.Location = new global::System.Drawing.Point(0, 238);
			this.Label17.Name = "Label17";
			this.Label17.Size = new global::System.Drawing.Size(591, 129);
			this.Label17.TabIndex = 33;
			this.Label17.Text = "Build your app easily";
			this.Label17.TextAlign = global::System.Drawing.ContentAlignment.TopCenter;
			this.Label15.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label15.Font = new global::System.Drawing.Font("Roboto Slab Light", 25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label15.ForeColor = global::System.Drawing.Color.White;
			this.Label15.Location = new global::System.Drawing.Point(0, 0);
			this.Label15.Name = "Label15";
			this.Label15.Size = new global::System.Drawing.Size(591, 238);
			this.Label15.TabIndex = 3;
			this.Label15.Text = "Login to Craxs Store";
			this.Label15.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(8f, 16f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.Color.Black;
			this.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.Zoom;
			base.ClientSize = new global::System.Drawing.Size(1184, 803);
			base.Controls.Add(this.lockpanel);
			base.Controls.Add(this.mainpanel);
			base.Controls.Add(this.Panelhome);
			base.Controls.Add(this.statustext);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
			this.MaximumSize = new global::System.Drawing.Size(1184, 803);
			this.MinimumSize = new global::System.Drawing.Size(1184, 803);
			base.Name = "CraxsStore";
			base.ShowIcon = false;
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "CraxsStore";
			((global::System.ComponentModel.ISupportInitialize)this.logopic).EndInit();
			this.mainpanel.ResumeLayout(false);
			this.DrakeUITabControl1.ResumeLayout(false);
			this.TabPage2.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.DGVSTORE).EndInit();
			this.TabPage1.ResumeLayout(false);
			this.TabPage1.PerformLayout();
			this.TabPage4.ResumeLayout(false);
			this.workpanel.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.workimage).EndInit();
			this.Panel1.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.DrakeUIImageButton1).EndInit();
			this.Panelhome.ResumeLayout(false);
			this.lockpanel.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			this.Panel3.ResumeLayout(false);
			base.ResumeLayout(false);
		}

		// Token: 0x0400009E RID: 158
		private global::System.ComponentModel.Container components;
	}
}
