namespace Craxs_Rat
{
	// Token: 0x020000DE RID: 222
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Ports : global::System.Windows.Forms.Form
	{
		// Token: 0x060010F8 RID: 4344 RVA: 0x000B2090 File Offset: 0x000B0290
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					((global::System.IDisposable)this.components).Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x060010F9 RID: 4345 RVA: 0x000B20D4 File Offset: 0x000B02D4
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::Craxs_Rat.Ports));
			this.pnl0 = new global::System.Windows.Forms.Panel();
			this.pnl1 = new global::System.Windows.Forms.Panel();
			this.statuslabel = new global::System.Windows.Forms.Label();
			this.loadingimage = new global::DrakeUI.Framework.DrakeUILoadingBar();
			this.logintext = new global::System.Windows.Forms.Label();
			this.savekey = new global::DrakeUI.Framework.DrakeUICheckBox();
			this.usrkeytext = new global::DrakeUI.Framework.DrakeUITextBox();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Activlist = new global::DrakeUI.Framework.DrakeUIListBox();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.policylink = new global::DrakeUI.Framework.DrakeUILinkLabel();
			this.checkterm = new global::DrakeUI.Framework.DrakeUICheckBox();
			this.tipkey = new global::DrakeUI.Framework.DrakeUIAvatar();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.PictureBox2 = new global::System.Windows.Forms.PictureBox();
			this.loginbtn = new global::DrakeUI.Framework.DrakeUIButtonIcon();
			this.porttext = new global::DrakeUI.Framework.DrakeUITextBox();
			this.rempo = new global::DrakeUI.Framework.DrakeUIAvatar();
			this.addpo = new global::DrakeUI.Framework.DrakeUIAvatar();
			this.passtxt = new global::DrakeUI.Framework.DrakeUITextBox();
			this.portlable = new global::System.Windows.Forms.Label();
			this.keylabel = new global::System.Windows.Forms.Label();
			this.notpass = new global::System.Windows.Forms.NotifyIcon(this.components);
			this.DrakeUIToolTip1 = new global::DrakeUI.Framework.DrakeUIToolTip(this.components);
			this.ToolTip1 = new global::System.Windows.Forms.ToolTip(this.components);
			this.Timer1 = new global::System.Windows.Forms.Timer(this.components);
			this.pnl0.SuspendLayout();
			this.pnl1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).BeginInit();
			base.SuspendLayout();
			this.pnl0.BackColor = global::System.Drawing.Color.Black;
			this.pnl0.Controls.Add(this.pnl1);
			this.pnl0.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.pnl0.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			this.pnl0.Location = new global::System.Drawing.Point(0, 0);
			this.pnl0.Margin = new global::System.Windows.Forms.Padding(4);
			this.pnl0.Name = "pnl0";
			this.pnl0.Size = new global::System.Drawing.Size(755, 429);
			this.pnl0.TabIndex = 0;
			this.pnl1.BackColor = global::System.Drawing.Color.Black;
			this.pnl1.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.Stretch;
			this.pnl1.Controls.Add(this.statuslabel);
			this.pnl1.Controls.Add(this.loadingimage);
			this.pnl1.Controls.Add(this.logintext);
			this.pnl1.Controls.Add(this.savekey);
			this.pnl1.Controls.Add(this.usrkeytext);
			this.pnl1.Controls.Add(this.Label4);
			this.pnl1.Controls.Add(this.Activlist);
			this.pnl1.Controls.Add(this.Button1);
			this.pnl1.Controls.Add(this.policylink);
			this.pnl1.Controls.Add(this.checkterm);
			this.pnl1.Controls.Add(this.tipkey);
			this.pnl1.Controls.Add(this.Label3);
			this.pnl1.Controls.Add(this.PictureBox2);
			this.pnl1.Controls.Add(this.loginbtn);
			this.pnl1.Controls.Add(this.porttext);
			this.pnl1.Controls.Add(this.rempo);
			this.pnl1.Controls.Add(this.addpo);
			this.pnl1.Controls.Add(this.passtxt);
			this.pnl1.Controls.Add(this.portlable);
			this.pnl1.Controls.Add(this.keylabel);
			this.pnl1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.pnl1.ForeColor = global::System.Drawing.Color.White;
			this.pnl1.Location = new global::System.Drawing.Point(0, 0);
			this.pnl1.Margin = new global::System.Windows.Forms.Padding(4);
			this.pnl1.Name = "pnl1";
			this.pnl1.Size = new global::System.Drawing.Size(755, 429);
			this.pnl1.TabIndex = 5;
			this.statuslabel.BackColor = global::System.Drawing.Color.Black;
			this.statuslabel.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.statuslabel.Font = new global::System.Drawing.Font("Lato", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.statuslabel.ForeColor = global::System.Drawing.Color.Lime;
			this.statuslabel.Location = new global::System.Drawing.Point(0, 411);
			this.statuslabel.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.statuslabel.Name = "statuslabel";
			this.statuslabel.Size = new global::System.Drawing.Size(755, 18);
			this.statuslabel.TabIndex = 42;
			this.statuslabel.Text = "CraxsRat.net";
			this.statuslabel.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.loadingimage.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.loadingimage.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.loadingimage.Location = new global::System.Drawing.Point(655, 333);
			this.loadingimage.Margin = new global::System.Windows.Forms.Padding(4);
			this.loadingimage.Name = "loadingimage";
			this.loadingimage.Size = new global::System.Drawing.Size(31, 32);
			this.loadingimage.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.loadingimage.StyleCustomMode = true;
			this.loadingimage.TabIndex = 41;
			this.loadingimage.Text = "DrakeUILoadingBar1";
			this.loadingimage.Visible = false;
			this.logintext.AutoSize = true;
			this.logintext.BackColor = global::System.Drawing.Color.Transparent;
			this.logintext.Font = new global::System.Drawing.Font("Roboto", 12f, global::System.Drawing.FontStyle.Bold);
			this.logintext.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.logintext.Location = new global::System.Drawing.Point(215, 243);
			this.logintext.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.logintext.Name = "logintext";
			this.logintext.Size = new global::System.Drawing.Size(98, 24);
			this.logintext.TabIndex = 40;
			this.logintext.Text = "Login Key";
			this.savekey.CheckBoxColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.savekey.Checked = true;
			this.savekey.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.savekey.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.savekey.ForeColor = global::System.Drawing.Color.White;
			this.savekey.Location = new global::System.Drawing.Point(625, 237);
			this.savekey.Margin = new global::System.Windows.Forms.Padding(4);
			this.savekey.Name = "savekey";
			this.savekey.Padding = new global::System.Windows.Forms.Padding(22, 0, 0, 0);
			this.savekey.Size = new global::System.Drawing.Size(125, 30);
			this.savekey.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.savekey.TabIndex = 39;
			this.savekey.Text = "Remember";
			this.usrkeytext.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.usrkeytext.FillColor = global::System.Drawing.Color.Black;
			this.usrkeytext.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.usrkeytext.ForeColor = global::System.Drawing.Color.White;
			this.usrkeytext.Location = new global::System.Drawing.Point(338, 237);
			this.usrkeytext.Margin = new global::System.Windows.Forms.Padding(5, 6, 5, 6);
			this.usrkeytext.Maximum = 2147483647.0;
			this.usrkeytext.Minimum = -2147483648.0;
			this.usrkeytext.Name = "usrkeytext";
			this.usrkeytext.Padding = new global::System.Windows.Forms.Padding(7, 6, 7, 6);
			this.usrkeytext.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.usrkeytext.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.usrkeytext.Size = new global::System.Drawing.Size(278, 30);
			this.usrkeytext.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.usrkeytext.TabIndex = 38;
			this.usrkeytext.TextAlignment = global::System.Drawing.ContentAlignment.TopCenter;
			this.Label4.AutoSize = true;
			this.Label4.BackColor = global::System.Drawing.Color.Black;
			this.Label4.Font = new global::System.Drawing.Font("Candara", 18f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label4.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Label4.Location = new global::System.Drawing.Point(355, 126);
			this.Label4.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label4.Name = "Label4";
			this.Label4.Size = new global::System.Drawing.Size(298, 37);
			this.Label4.TabIndex = 37;
			this.Label4.Text = "Welcome To CraxsRat";
			this.Activlist.BackColor = global::System.Drawing.Color.FromArgb(20, 31, 20);
			this.Activlist.FillColor = global::System.Drawing.Color.Black;
			this.Activlist.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.Activlist.HoverColor = global::System.Drawing.Color.FromArgb(241, 160, 160);
			this.Activlist.ItemSelectBackColor = global::System.Drawing.Color.FromArgb(230, 80, 80);
			this.Activlist.ItemSelectForeColor = global::System.Drawing.Color.FromArgb(255, 235, 238);
			this.Activlist.Location = new global::System.Drawing.Point(17, 106);
			this.Activlist.Margin = new global::System.Windows.Forms.Padding(5, 6, 5, 6);
			this.Activlist.Name = "Activlist";
			this.Activlist.Padding = new global::System.Windows.Forms.Padding(7);
			this.Activlist.Radius = 15;
			this.Activlist.RectColor = global::System.Drawing.Color.FromArgb(230, 80, 80);
			this.Activlist.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.Activlist.Size = new global::System.Drawing.Size(160, 283);
			this.Activlist.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.Activlist.StyleCustomMode = true;
			this.Activlist.TabIndex = 24;
			this.Activlist.Text = "DrakeUIListBox1";
			this.Button1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.Button1.BackColor = global::System.Drawing.Color.Transparent;
			this.Button1.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.Zoom;
			this.Button1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Button1.FlatAppearance.BorderSize = 0;
			this.Button1.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(10, 3, 10);
			this.Button1.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(10, 3, 10);
			this.Button1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button1.Font = new global::System.Drawing.Font("Segoe UI", 18f, global::System.Drawing.FontStyle.Bold);
			this.Button1.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Button1.Location = new global::System.Drawing.Point(704, 4);
			this.Button1.Margin = new global::System.Windows.Forms.Padding(4);
			this.Button1.Name = "Button1";
			this.Button1.Size = new global::System.Drawing.Size(47, 60);
			this.Button1.TabIndex = 35;
			this.Button1.Text = "X";
			this.Button1.UseVisualStyleBackColor = false;
			this.policylink.ActiveLinkColor = global::System.Drawing.Color.FromArgb(220, 155, 40);
			this.policylink.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f);
			this.policylink.LinkBehavior = global::System.Windows.Forms.LinkBehavior.AlwaysUnderline;
			this.policylink.LinkColor = global::System.Drawing.Color.FromArgb(30, 136, 229);
			this.policylink.Location = new global::System.Drawing.Point(412, 293);
			this.policylink.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.policylink.Name = "policylink";
			this.policylink.Size = new global::System.Drawing.Size(235, 26);
			this.policylink.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.policylink.TabIndex = 34;
			this.policylink.TabStop = true;
			this.policylink.Text = "i agree to Terms of Service";
			this.policylink.VisitedLinkColor = global::System.Drawing.Color.FromArgb(230, 80, 80);
			this.checkterm.CheckBoxColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.checkterm.Checked = true;
			this.checkterm.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.checkterm.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f);
			this.checkterm.ForeColor = global::System.Drawing.Color.White;
			this.checkterm.Location = new global::System.Drawing.Point(373, 293);
			this.checkterm.Margin = new global::System.Windows.Forms.Padding(4);
			this.checkterm.Name = "checkterm";
			this.checkterm.Padding = new global::System.Windows.Forms.Padding(22, 0, 0, 0);
			this.checkterm.Size = new global::System.Drawing.Size(31, 26);
			this.checkterm.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.checkterm.StyleCustomMode = true;
			this.checkterm.TabIndex = 33;
			this.tipkey.AvatarSize = 25;
			this.tipkey.BackColor = global::System.Drawing.Color.Transparent;
			this.tipkey.FillColor = global::System.Drawing.Color.Black;
			this.tipkey.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.tipkey.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.tipkey.Location = new global::System.Drawing.Point(626, 192);
			this.tipkey.Margin = new global::System.Windows.Forms.Padding(4);
			this.tipkey.Name = "tipkey";
			this.tipkey.Size = new global::System.Drawing.Size(34, 34);
			this.tipkey.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.tipkey.Symbol = 61529;
			this.tipkey.SymbolSize = 25;
			this.tipkey.TabIndex = 32;
			this.tipkey.Text = "DrakeUIAvatar2";
			this.DrakeUIToolTip1.SetToolTip(this.tipkey, "This Key is like Password\r\n\r\nused between\r\n\r\nThe phone and the controller");
			this.Label3.AutoSize = true;
			this.Label3.BackColor = global::System.Drawing.Color.Black;
			this.Label3.Font = new global::System.Drawing.Font("Lato", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label3.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Label3.Location = new global::System.Drawing.Point(437, 371);
			this.Label3.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(96, 18);
			this.Label3.TabIndex = 31;
			this.Label3.Text = "CraxsRat.net";
			this.Label3.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Label3.Visible = false;
			this.PictureBox2.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.Zoom;
			this.PictureBox2.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox2.Image");
			this.PictureBox2.Location = new global::System.Drawing.Point(440, 13);
			this.PictureBox2.Margin = new global::System.Windows.Forms.Padding(4);
			this.PictureBox2.Name = "PictureBox2";
			this.PictureBox2.Size = new global::System.Drawing.Size(128, 109);
			this.PictureBox2.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox2.TabIndex = 30;
			this.PictureBox2.TabStop = false;
			this.loginbtn.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.loginbtn.Enabled = false;
			this.loginbtn.FillColor = global::System.Drawing.Color.Black;
			this.loginbtn.FillHoverColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.loginbtn.FillPressColor = global::System.Drawing.Color.Black;
			this.loginbtn.FillSelectedColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.loginbtn.Font = new global::System.Drawing.Font("Arial", 12f);
			this.loginbtn.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.loginbtn.ForePressColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.loginbtn.Location = new global::System.Drawing.Point(326, 333);
			this.loginbtn.Margin = new global::System.Windows.Forms.Padding(4);
			this.loginbtn.Name = "loginbtn";
			this.loginbtn.Radius = 25;
			this.loginbtn.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.loginbtn.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.loginbtn.RectHoverColor = global::System.Drawing.Color.White;
			this.loginbtn.RectPressColor = global::System.Drawing.Color.White;
			this.loginbtn.RectSelectedColor = global::System.Drawing.Color.White;
			this.loginbtn.Size = new global::System.Drawing.Size(321, 32);
			this.loginbtn.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.loginbtn.SymbolSize = 0;
			this.loginbtn.TabIndex = 28;
			this.loginbtn.Text = "login";
			this.porttext.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.porttext.FillColor = global::System.Drawing.Color.Black;
			this.porttext.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.porttext.ForeColor = global::System.Drawing.Color.White;
			this.porttext.Location = new global::System.Drawing.Point(17, 62);
			this.porttext.Margin = new global::System.Windows.Forms.Padding(5, 6, 5, 6);
			this.porttext.Maximum = 2147483647.0;
			this.porttext.Minimum = -2147483648.0;
			this.porttext.Name = "porttext";
			this.porttext.Padding = new global::System.Windows.Forms.Padding(7, 6, 7, 6);
			this.porttext.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.porttext.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.porttext.Size = new global::System.Drawing.Size(77, 30);
			this.porttext.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.porttext.TabIndex = 27;
			this.porttext.TextAlignment = global::System.Drawing.ContentAlignment.TopCenter;
			this.rempo.AvatarSize = 30;
			this.rempo.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.rempo.FillColor = global::System.Drawing.Color.Black;
			this.rempo.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.rempo.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.rempo.Location = new global::System.Drawing.Point(103, 62);
			this.rempo.Margin = new global::System.Windows.Forms.Padding(4);
			this.rempo.Name = "rempo";
			this.rempo.Size = new global::System.Drawing.Size(35, 30);
			this.rempo.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.rempo.Symbol = 61526;
			this.rempo.SymbolSize = 30;
			this.rempo.TabIndex = 26;
			this.rempo.Text = "DrakeUIAvatar2";
			this.addpo.AvatarSize = 30;
			this.addpo.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.addpo.FillColor = global::System.Drawing.Color.Black;
			this.addpo.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.addpo.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.addpo.Location = new global::System.Drawing.Point(146, 62);
			this.addpo.Margin = new global::System.Windows.Forms.Padding(4);
			this.addpo.Name = "addpo";
			this.addpo.Size = new global::System.Drawing.Size(35, 30);
			this.addpo.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.addpo.Symbol = 61525;
			this.addpo.SymbolSize = 30;
			this.addpo.TabIndex = 25;
			this.addpo.Text = "DrakeUIAvatar1";
			this.passtxt.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.passtxt.FillColor = global::System.Drawing.Color.Black;
			this.passtxt.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.passtxt.ForeColor = global::System.Drawing.Color.White;
			this.passtxt.Location = new global::System.Drawing.Point(338, 195);
			this.passtxt.Margin = new global::System.Windows.Forms.Padding(5, 6, 5, 6);
			this.passtxt.Maximum = 2147483647.0;
			this.passtxt.Minimum = -2147483648.0;
			this.passtxt.Name = "passtxt";
			this.passtxt.Padding = new global::System.Windows.Forms.Padding(7, 6, 7, 6);
			this.passtxt.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.passtxt.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.passtxt.Size = new global::System.Drawing.Size(278, 30);
			this.passtxt.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.passtxt.TabIndex = 23;
			this.passtxt.TextAlignment = global::System.Drawing.ContentAlignment.TopCenter;
			this.portlable.AutoSize = true;
			this.portlable.BackColor = global::System.Drawing.Color.Transparent;
			this.portlable.Font = new global::System.Drawing.Font("Roboto", 12f, global::System.Drawing.FontStyle.Bold);
			this.portlable.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.portlable.Location = new global::System.Drawing.Point(13, 28);
			this.portlable.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.portlable.Name = "portlable";
			this.portlable.Size = new global::System.Drawing.Size(164, 24);
			this.portlable.TabIndex = 20;
			this.portlable.Text = "Connection Ports";
			this.keylabel.AutoSize = true;
			this.keylabel.BackColor = global::System.Drawing.Color.Transparent;
			this.keylabel.Font = new global::System.Drawing.Font("Roboto", 12f, global::System.Drawing.FontStyle.Bold);
			this.keylabel.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.keylabel.Location = new global::System.Drawing.Point(215, 192);
			this.keylabel.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.keylabel.Name = "keylabel";
			this.keylabel.Size = new global::System.Drawing.Size(98, 24);
			this.keylabel.TabIndex = 18;
			this.keylabel.Text = "Password";
			this.notpass.Text = "NotifyIcon1";
			this.notpass.Visible = true;
			this.DrakeUIToolTip1.BackColor = global::System.Drawing.Color.FromArgb(54, 54, 54);
			this.DrakeUIToolTip1.ForeColor = global::System.Drawing.Color.FromArgb(239, 239, 239);
			this.DrakeUIToolTip1.OwnerDraw = true;
			this.ToolTip1.BackColor = global::System.Drawing.Color.Black;
			this.ToolTip1.ForeColor = global::System.Drawing.Color.White;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(8f, 16f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.SystemColors.Control;
			base.ClientSize = new global::System.Drawing.Size(755, 429);
			base.Controls.Add(this.pnl0);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
			base.Margin = new global::System.Windows.Forms.Padding(4);
			base.Name = "Ports";
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "Ports";
			this.pnl0.ResumeLayout(false);
			this.pnl1.ResumeLayout(false);
			this.pnl1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).EndInit();
			base.ResumeLayout(false);
		}

		// Token: 0x0400093B RID: 2363
		private global::System.ComponentModel.Container components;
	}
}
