namespace Craxs_Rat
{
	// Token: 0x02000031 RID: 49
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class requestapk : global::System.Windows.Forms.Form
	{
		// Token: 0x06000351 RID: 849 RVA: 0x0001D9C0 File Offset: 0x0001BBC0
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000352 RID: 850 RVA: 0x0001DA04 File Offset: 0x0001BC04
		private void InitializeComponent()
		{
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.appnametext = new global::DrakeUI.Framework.DrakeUITextBox();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Panel2 = new global::System.Windows.Forms.Panel();
			this.Panel3 = new global::System.Windows.Forms.Panel();
			this.Panel4 = new global::System.Windows.Forms.Panel();
			this.Panel5 = new global::System.Windows.Forms.Panel();
			this.reqemail = new global::DrakeUI.Framework.DrakeUITextBox();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Panel6 = new global::System.Windows.Forms.Panel();
			this.Panel7 = new global::System.Windows.Forms.Panel();
			this.apklinktext = new global::DrakeUI.Framework.DrakeUITextBox();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Panel8 = new global::System.Windows.Forms.Panel();
			this.Panel9 = new global::System.Windows.Forms.Panel();
			this.appvirtext = new global::DrakeUI.Framework.DrakeUITextBox();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Panel10 = new global::System.Windows.Forms.Panel();
			this.Panel11 = new global::System.Windows.Forms.Panel();
			this.discriptext = new global::DrakeUI.Framework.DrakeUITextBox();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.exitbtn = new global::DrakeUI.Framework.DrakeUIButtonIcon();
			this.reqbtn = new global::DrakeUI.Framework.DrakeUIButtonIcon();
			this.Panel1.SuspendLayout();
			this.Panel5.SuspendLayout();
			this.Panel7.SuspendLayout();
			this.Panel9.SuspendLayout();
			this.Panel11.SuspendLayout();
			base.SuspendLayout();
			this.Label1.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Label1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Label1.Font = new global::System.Drawing.Font("Times New Roman", 18f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label1.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Label1.Location = new global::System.Drawing.Point(0, 0);
			this.Label1.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(540, 56);
			this.Label1.TabIndex = 36;
			this.Label1.Tag = "1";
			this.Label1.Text = "Request App";
			this.Label1.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Label2.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Label2.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label2.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Label2.Font = new global::System.Drawing.Font("Roboto", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label2.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Label2.Location = new global::System.Drawing.Point(0, 56);
			this.Label2.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(540, 56);
			this.Label2.TabIndex = 37;
			this.Label2.Tag = "1";
			this.Label2.Text = "Enter app details that you which to see on Craxs store \r\n(* is required)";
			this.Label2.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Panel1.Controls.Add(this.appnametext);
			this.Panel1.Controls.Add(this.Label3);
			this.Panel1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel1.Location = new global::System.Drawing.Point(0, 143);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new global::System.Drawing.Size(540, 32);
			this.Panel1.TabIndex = 38;
			this.appnametext.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.appnametext.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.appnametext.FillColor = global::System.Drawing.Color.Black;
			this.appnametext.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.appnametext.ForeColor = global::System.Drawing.Color.White;
			this.appnametext.Location = new global::System.Drawing.Point(119, 0);
			this.appnametext.Margin = new global::System.Windows.Forms.Padding(5, 6, 5, 6);
			this.appnametext.Maximum = 2147483647.0;
			this.appnametext.MaxLength = 25;
			this.appnametext.Minimum = -2147483648.0;
			this.appnametext.Name = "appnametext";
			this.appnametext.Padding = new global::System.Windows.Forms.Padding(7, 6, 7, 6);
			this.appnametext.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.appnametext.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.appnametext.Size = new global::System.Drawing.Size(421, 30);
			this.appnametext.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.appnametext.TabIndex = 39;
			this.appnametext.TextAlignment = global::System.Drawing.ContentAlignment.TopCenter;
			this.Label3.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Label3.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.Label3.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Label3.Font = new global::System.Drawing.Font("Roboto", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label3.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Label3.Location = new global::System.Drawing.Point(0, 0);
			this.Label3.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(119, 32);
			this.Label3.TabIndex = 38;
			this.Label3.Tag = "1";
			this.Label3.Text = "App Name *";
			this.Label3.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Panel2.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel2.Location = new global::System.Drawing.Point(0, 175);
			this.Panel2.Name = "Panel2";
			this.Panel2.Size = new global::System.Drawing.Size(540, 31);
			this.Panel2.TabIndex = 39;
			this.Panel3.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel3.Location = new global::System.Drawing.Point(0, 112);
			this.Panel3.Name = "Panel3";
			this.Panel3.Size = new global::System.Drawing.Size(540, 31);
			this.Panel3.TabIndex = 40;
			this.Panel4.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel4.Location = new global::System.Drawing.Point(0, 238);
			this.Panel4.Name = "Panel4";
			this.Panel4.Size = new global::System.Drawing.Size(540, 31);
			this.Panel4.TabIndex = 42;
			this.Panel5.Controls.Add(this.reqemail);
			this.Panel5.Controls.Add(this.Label4);
			this.Panel5.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel5.Location = new global::System.Drawing.Point(0, 206);
			this.Panel5.Name = "Panel5";
			this.Panel5.Size = new global::System.Drawing.Size(540, 32);
			this.Panel5.TabIndex = 41;
			this.reqemail.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.reqemail.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.reqemail.FillColor = global::System.Drawing.Color.Black;
			this.reqemail.FillDisableColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.reqemail.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.reqemail.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.reqemail.ForeDisableColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.reqemail.Location = new global::System.Drawing.Point(119, 0);
			this.reqemail.Margin = new global::System.Windows.Forms.Padding(5, 6, 5, 6);
			this.reqemail.Maximum = 2147483647.0;
			this.reqemail.Minimum = -2147483648.0;
			this.reqemail.Name = "reqemail";
			this.reqemail.Padding = new global::System.Windows.Forms.Padding(7, 6, 7, 6);
			this.reqemail.ReadOnly = true;
			this.reqemail.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.reqemail.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.reqemail.Size = new global::System.Drawing.Size(421, 30);
			this.reqemail.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.reqemail.StyleCustomMode = true;
			this.reqemail.TabIndex = 39;
			this.reqemail.TextAlignment = global::System.Drawing.ContentAlignment.TopCenter;
			this.Label4.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Label4.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.Label4.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Label4.Font = new global::System.Drawing.Font("Roboto", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label4.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Label4.Location = new global::System.Drawing.Point(0, 0);
			this.Label4.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label4.Name = "Label4";
			this.Label4.Size = new global::System.Drawing.Size(119, 32);
			this.Label4.TabIndex = 38;
			this.Label4.Tag = "1";
			this.Label4.Text = "Your Email *";
			this.Label4.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Panel6.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel6.Location = new global::System.Drawing.Point(0, 301);
			this.Panel6.Name = "Panel6";
			this.Panel6.Size = new global::System.Drawing.Size(540, 31);
			this.Panel6.TabIndex = 44;
			this.Panel7.Controls.Add(this.apklinktext);
			this.Panel7.Controls.Add(this.Label5);
			this.Panel7.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel7.Location = new global::System.Drawing.Point(0, 269);
			this.Panel7.Name = "Panel7";
			this.Panel7.Size = new global::System.Drawing.Size(540, 32);
			this.Panel7.TabIndex = 43;
			this.apklinktext.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.apklinktext.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.apklinktext.FillColor = global::System.Drawing.Color.Black;
			this.apklinktext.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.apklinktext.ForeColor = global::System.Drawing.Color.White;
			this.apklinktext.Location = new global::System.Drawing.Point(119, 0);
			this.apklinktext.Margin = new global::System.Windows.Forms.Padding(5, 6, 5, 6);
			this.apklinktext.Maximum = 2147483647.0;
			this.apklinktext.MaxLength = 250;
			this.apklinktext.Minimum = -2147483648.0;
			this.apklinktext.Name = "apklinktext";
			this.apklinktext.Padding = new global::System.Windows.Forms.Padding(7, 6, 7, 6);
			this.apklinktext.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.apklinktext.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.apklinktext.Size = new global::System.Drawing.Size(421, 30);
			this.apklinktext.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.apklinktext.TabIndex = 39;
			this.apklinktext.TextAlignment = global::System.Drawing.ContentAlignment.TopCenter;
			this.Label5.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Label5.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.Label5.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Label5.Font = new global::System.Drawing.Font("Roboto", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label5.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Label5.Location = new global::System.Drawing.Point(0, 0);
			this.Label5.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label5.Name = "Label5";
			this.Label5.Size = new global::System.Drawing.Size(119, 32);
			this.Label5.TabIndex = 38;
			this.Label5.Tag = "1";
			this.Label5.Text = "App Link (url)";
			this.Label5.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Panel8.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel8.Location = new global::System.Drawing.Point(0, 364);
			this.Panel8.Name = "Panel8";
			this.Panel8.Size = new global::System.Drawing.Size(540, 31);
			this.Panel8.TabIndex = 46;
			this.Panel9.Controls.Add(this.appvirtext);
			this.Panel9.Controls.Add(this.Label6);
			this.Panel9.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel9.Location = new global::System.Drawing.Point(0, 332);
			this.Panel9.Name = "Panel9";
			this.Panel9.Size = new global::System.Drawing.Size(540, 32);
			this.Panel9.TabIndex = 45;
			this.appvirtext.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.appvirtext.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.appvirtext.FillColor = global::System.Drawing.Color.Black;
			this.appvirtext.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.appvirtext.ForeColor = global::System.Drawing.Color.White;
			this.appvirtext.Location = new global::System.Drawing.Point(119, 0);
			this.appvirtext.Margin = new global::System.Windows.Forms.Padding(5, 6, 5, 6);
			this.appvirtext.Maximum = 2147483647.0;
			this.appvirtext.MaxLength = 25;
			this.appvirtext.Minimum = -2147483648.0;
			this.appvirtext.Name = "appvirtext";
			this.appvirtext.Padding = new global::System.Windows.Forms.Padding(7, 6, 7, 6);
			this.appvirtext.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.appvirtext.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.appvirtext.Size = new global::System.Drawing.Size(421, 30);
			this.appvirtext.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.appvirtext.TabIndex = 39;
			this.appvirtext.TextAlignment = global::System.Drawing.ContentAlignment.TopCenter;
			this.Label6.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Label6.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.Label6.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Label6.Font = new global::System.Drawing.Font("Roboto", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label6.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Label6.Location = new global::System.Drawing.Point(0, 0);
			this.Label6.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label6.Name = "Label6";
			this.Label6.Size = new global::System.Drawing.Size(119, 32);
			this.Label6.TabIndex = 38;
			this.Label6.Tag = "1";
			this.Label6.Text = "App Version";
			this.Label6.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Panel10.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel10.Location = new global::System.Drawing.Point(0, 469);
			this.Panel10.Name = "Panel10";
			this.Panel10.Size = new global::System.Drawing.Size(540, 31);
			this.Panel10.TabIndex = 48;
			this.Panel11.Controls.Add(this.discriptext);
			this.Panel11.Controls.Add(this.Label7);
			this.Panel11.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel11.Location = new global::System.Drawing.Point(0, 395);
			this.Panel11.Name = "Panel11";
			this.Panel11.Size = new global::System.Drawing.Size(540, 74);
			this.Panel11.TabIndex = 47;
			this.discriptext.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.discriptext.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.discriptext.FillColor = global::System.Drawing.Color.Black;
			this.discriptext.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.discriptext.ForeColor = global::System.Drawing.Color.White;
			this.discriptext.Location = new global::System.Drawing.Point(119, 0);
			this.discriptext.Margin = new global::System.Windows.Forms.Padding(5, 6, 5, 6);
			this.discriptext.Maximum = 2147483647.0;
			this.discriptext.MaxLength = 140;
			this.discriptext.Minimum = -2147483648.0;
			this.discriptext.Multiline = true;
			this.discriptext.Name = "discriptext";
			this.discriptext.Padding = new global::System.Windows.Forms.Padding(7, 6, 7, 6);
			this.discriptext.RectColor = global::System.Drawing.Color.FromArgb(130, 130, 130);
			this.discriptext.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.discriptext.Size = new global::System.Drawing.Size(421, 74);
			this.discriptext.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.discriptext.StyleCustomMode = true;
			this.discriptext.TabIndex = 39;
			this.discriptext.TextAlignment = global::System.Drawing.ContentAlignment.TopCenter;
			this.Label7.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.Label7.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.Label7.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Label7.Font = new global::System.Drawing.Font("Roboto", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label7.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Label7.Location = new global::System.Drawing.Point(0, 0);
			this.Label7.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label7.Name = "Label7";
			this.Label7.Size = new global::System.Drawing.Size(119, 74);
			this.Label7.TabIndex = 38;
			this.Label7.Tag = "1";
			this.Label7.Text = "Description";
			this.Label7.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.exitbtn.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.exitbtn.FillColor = global::System.Drawing.Color.Black;
			this.exitbtn.FillDisableColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.exitbtn.Font = new global::System.Drawing.Font("Roboto", 19f);
			this.exitbtn.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.exitbtn.Location = new global::System.Drawing.Point(12, 506);
			this.exitbtn.Name = "exitbtn";
			this.exitbtn.RectColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.exitbtn.RectDisableColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.exitbtn.Size = new global::System.Drawing.Size(230, 56);
			this.exitbtn.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.exitbtn.Symbol = 62164;
			this.exitbtn.TabIndex = 49;
			this.exitbtn.Text = "Exit";
			this.reqbtn.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.reqbtn.FillColor = global::System.Drawing.Color.Black;
			this.reqbtn.FillDisableColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.reqbtn.Font = new global::System.Drawing.Font("Roboto", 19f);
			this.reqbtn.ForeColor = global::System.Drawing.Color.FromArgb(14, 110, 178);
			this.reqbtn.Location = new global::System.Drawing.Point(298, 506);
			this.reqbtn.Name = "reqbtn";
			this.reqbtn.RectColor = global::System.Drawing.Color.FromArgb(14, 110, 178);
			this.reqbtn.RectDisableColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.reqbtn.Size = new global::System.Drawing.Size(230, 56);
			this.reqbtn.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.reqbtn.Symbol = 61913;
			this.reqbtn.TabIndex = 50;
			this.reqbtn.Text = "Request";
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(8f, 16f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.Color.Black;
			base.ClientSize = new global::System.Drawing.Size(540, 574);
			base.Controls.Add(this.reqbtn);
			base.Controls.Add(this.exitbtn);
			base.Controls.Add(this.Panel10);
			base.Controls.Add(this.Panel11);
			base.Controls.Add(this.Panel8);
			base.Controls.Add(this.Panel9);
			base.Controls.Add(this.Panel6);
			base.Controls.Add(this.Panel7);
			base.Controls.Add(this.Panel4);
			base.Controls.Add(this.Panel5);
			base.Controls.Add(this.Panel2);
			base.Controls.Add(this.Panel1);
			base.Controls.Add(this.Panel3);
			base.Controls.Add(this.Label2);
			base.Controls.Add(this.Label1);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
			base.Name = "requestapk";
			base.ShowIcon = false;
			base.ShowInTaskbar = false;
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "requestapk";
			base.TopMost = true;
			this.Panel1.ResumeLayout(false);
			this.Panel5.ResumeLayout(false);
			this.Panel7.ResumeLayout(false);
			this.Panel9.ResumeLayout(false);
			this.Panel11.ResumeLayout(false);
			base.ResumeLayout(false);
		}

		// Token: 0x04000182 RID: 386
		private global::System.IDisposable components;
	}
}
