namespace Craxs_Rat
{
	// Token: 0x020000F9 RID: 249
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Settings : global::System.Windows.Forms.Form
	{
		// Token: 0x060011AE RID: 4526 RVA: 0x000B85E0 File Offset: 0x000B67E0
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					((global::System.IDisposable)this.components).Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x060011AF RID: 4527 RVA: 0x000B8624 File Offset: 0x000B6824
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle7 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle8 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle9 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle10 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle11 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::Craxs_Rat.Settings));
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle12 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle13 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle14 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle15 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle16 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle17 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle18 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle19 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle20 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle21 = new global::System.Windows.Forms.DataGridViewCellStyle();
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.DGV9 = new global::System.Windows.Forms.DataGridView();
			this.DataGridViewTextBoxColumn9 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewComboBoxColumn8 = new global::System.Windows.Forms.DataGridViewComboBoxColumn();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.DGV8 = new global::System.Windows.Forms.DataGridView();
			this.DataGridViewTextBoxColumn8 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewComboBoxColumn7 = new global::System.Windows.Forms.DataGridViewComboBoxColumn();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.DGV7 = new global::System.Windows.Forms.DataGridView();
			this.DataGridViewTextBoxColumn7 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewComboBoxColumn6 = new global::System.Windows.Forms.DataGridViewComboBoxColumn();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.DGV6 = new global::System.Windows.Forms.DataGridView();
			this.DataGridViewTextBoxColumn6 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewComboBoxColumn5 = new global::System.Windows.Forms.DataGridViewComboBoxColumn();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.DGV5 = new global::System.Windows.Forms.DataGridView();
			this.DataGridViewTextBoxColumn5 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column3 = new global::System.Windows.Forms.DataGridViewImageColumn();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.DGV4 = new global::System.Windows.Forms.DataGridView();
			this.DataGridViewTextBoxColumn4 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewComboBoxColumn4 = new global::System.Windows.Forms.DataGridViewComboBoxColumn();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.DGV3 = new global::System.Windows.Forms.DataGridView();
			this.DataGridViewTextBoxColumn3 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewComboBoxColumn3 = new global::System.Windows.Forms.DataGridViewComboBoxColumn();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.DGV2 = new global::System.Windows.Forms.DataGridView();
			this.DataGridViewTextBoxColumn2 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewComboBoxColumn2 = new global::System.Windows.Forms.DataGridViewComboBoxColumn();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.DGV1 = new global::System.Windows.Forms.DataGridView();
			this.DataGridViewTextBoxColumn1 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.DataGridViewComboBoxColumn1 = new global::System.Windows.Forms.DataGridViewComboBoxColumn();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.DGV0 = new global::System.Windows.Forms.DataGridView();
			this.Column1 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.Column2 = new global::System.Windows.Forms.DataGridViewComboBoxColumn();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.SV = new global::System.Windows.Forms.Button();
			this.DL = new global::System.Windows.Forms.Button();
			this.Panel2 = new global::System.Windows.Forms.Panel();
			this.TOpacity = new global::System.Windows.Forms.Timer(this.components);
			this.ctxPacket = new global::System.Windows.Forms.ContextMenuStrip(this.components);
			this.DefaultToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.clr_1 = new global::System.Windows.Forms.ToolStripMenuItem();
			this.clr_2 = new global::System.Windows.Forms.ToolStripMenuItem();
			this.Clr3ToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.Clr4ToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.Clr5ToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.Clr6ToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.Clr7ToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.Clr8ToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.Clr9ToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.Panel1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.DGV9).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV8).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV7).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV6).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV5).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV4).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV3).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV0).BeginInit();
			this.Panel2.SuspendLayout();
			this.ctxPacket.SuspendLayout();
			base.SuspendLayout();
			this.Panel1.AutoScroll = true;
			this.Panel1.BackColor = global::System.Drawing.Color.DimGray;
			this.Panel1.Controls.Add(this.DGV9);
			this.Panel1.Controls.Add(this.Label10);
			this.Panel1.Controls.Add(this.DGV8);
			this.Panel1.Controls.Add(this.Label9);
			this.Panel1.Controls.Add(this.DGV7);
			this.Panel1.Controls.Add(this.Label8);
			this.Panel1.Controls.Add(this.DGV6);
			this.Panel1.Controls.Add(this.Label7);
			this.Panel1.Controls.Add(this.DGV5);
			this.Panel1.Controls.Add(this.Label6);
			this.Panel1.Controls.Add(this.DGV4);
			this.Panel1.Controls.Add(this.Label5);
			this.Panel1.Controls.Add(this.DGV3);
			this.Panel1.Controls.Add(this.Label4);
			this.Panel1.Controls.Add(this.DGV2);
			this.Panel1.Controls.Add(this.Label3);
			this.Panel1.Controls.Add(this.DGV1);
			this.Panel1.Controls.Add(this.Label2);
			this.Panel1.Controls.Add(this.DGV0);
			this.Panel1.Controls.Add(this.Label1);
			this.Panel1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.Panel1.Location = new global::System.Drawing.Point(0, 0);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new global::System.Drawing.Size(369, 354);
			this.Panel1.TabIndex = 1;
			this.DGV9.AllowUserToAddRows = false;
			this.DGV9.AllowUserToDeleteRows = false;
			this.DGV9.AllowUserToResizeColumns = false;
			this.DGV9.AllowUserToResizeRows = false;
			this.DGV9.AutoSizeColumnsMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
			this.DGV9.AutoSizeRowsMode = global::System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
			this.DGV9.BackgroundColor = global::System.Drawing.Color.Black;
			this.DGV9.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.DGV9.CellBorderStyle = global::System.Windows.Forms.DataGridViewCellBorderStyle.None;
			this.DGV9.ColumnHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DGV9.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle;
			this.DGV9.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
			this.DGV9.ColumnHeadersVisible = false;
			this.DGV9.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.DataGridViewTextBoxColumn9,
				this.DataGridViewComboBoxColumn8
			});
			dataGridViewCellStyle2.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle2.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle2.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle2.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			dataGridViewCellStyle2.SelectionBackColor = global::System.Drawing.Color.FromArgb(51, 153, 255);
			dataGridViewCellStyle2.SelectionForeColor = global::System.Drawing.Color.FromArgb(240, 240, 240);
			dataGridViewCellStyle2.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DGV9.DefaultCellStyle = dataGridViewCellStyle2;
			this.DGV9.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.DGV9.EditMode = global::System.Windows.Forms.DataGridViewEditMode.EditOnEnter;
			this.DGV9.EnableHeadersVisualStyles = false;
			this.DGV9.GridColor = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.DGV9.Location = new global::System.Drawing.Point(0, 956);
			this.DGV9.Name = "DGV9";
			this.DGV9.RowHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
			this.DGV9.RowHeadersVisible = false;
			this.DGV9.ScrollBars = global::System.Windows.Forms.ScrollBars.None;
			this.DGV9.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.DGV9.Size = new global::System.Drawing.Size(352, 75);
			this.DGV9.TabIndex = 22;
			this.DataGridViewTextBoxColumn9.HeaderText = "Property";
			this.DataGridViewTextBoxColumn9.Name = "DataGridViewTextBoxColumn9";
			this.DataGridViewTextBoxColumn9.ReadOnly = true;
			this.DataGridViewTextBoxColumn9.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
			this.DataGridViewComboBoxColumn8.DisplayStyle = global::System.Windows.Forms.DataGridViewComboBoxDisplayStyle.ComboBox;
			this.DataGridViewComboBoxColumn8.DisplayStyleForCurrentCellOnly = true;
			this.DataGridViewComboBoxColumn8.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
			this.DataGridViewComboBoxColumn8.HeaderText = "value";
			this.DataGridViewComboBoxColumn8.Name = "DataGridViewComboBoxColumn8";
			this.DataGridViewComboBoxColumn8.Resizable = global::System.Windows.Forms.DataGridViewTriState.False;
			this.Label10.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.Label10.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label10.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			this.Label10.Location = new global::System.Drawing.Point(0, 932);
			this.Label10.Name = "Label10";
			this.Label10.Padding = new global::System.Windows.Forms.Padding(0, 0, 0, 4);
			this.Label10.Size = new global::System.Drawing.Size(352, 24);
			this.Label10.TabIndex = 21;
			this.Label10.Text = "File Manager";
			this.Label10.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.DGV8.AllowUserToAddRows = false;
			this.DGV8.AllowUserToDeleteRows = false;
			this.DGV8.AllowUserToResizeColumns = false;
			this.DGV8.AllowUserToResizeRows = false;
			this.DGV8.AutoSizeColumnsMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
			this.DGV8.AutoSizeRowsMode = global::System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
			this.DGV8.BackgroundColor = global::System.Drawing.Color.Black;
			this.DGV8.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.DGV8.CellBorderStyle = global::System.Windows.Forms.DataGridViewCellBorderStyle.None;
			this.DGV8.ColumnHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle3.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle3.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle3.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle3.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle3.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle3.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle3.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DGV8.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle3;
			this.DGV8.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
			this.DGV8.ColumnHeadersVisible = false;
			this.DGV8.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.DataGridViewTextBoxColumn8,
				this.DataGridViewComboBoxColumn7
			});
			dataGridViewCellStyle4.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle4.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle4.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle4.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			dataGridViewCellStyle4.SelectionBackColor = global::System.Drawing.Color.FromArgb(51, 153, 255);
			dataGridViewCellStyle4.SelectionForeColor = global::System.Drawing.Color.FromArgb(240, 240, 240);
			dataGridViewCellStyle4.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DGV8.DefaultCellStyle = dataGridViewCellStyle4;
			this.DGV8.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.DGV8.EditMode = global::System.Windows.Forms.DataGridViewEditMode.EditOnEnter;
			this.DGV8.EnableHeadersVisualStyles = false;
			this.DGV8.GridColor = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.DGV8.Location = new global::System.Drawing.Point(0, 857);
			this.DGV8.Name = "DGV8";
			this.DGV8.RowHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
			this.DGV8.RowHeadersVisible = false;
			this.DGV8.ScrollBars = global::System.Windows.Forms.ScrollBars.None;
			this.DGV8.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.DGV8.Size = new global::System.Drawing.Size(352, 75);
			this.DGV8.TabIndex = 20;
			this.DataGridViewTextBoxColumn8.HeaderText = "Property";
			this.DataGridViewTextBoxColumn8.Name = "DataGridViewTextBoxColumn8";
			this.DataGridViewTextBoxColumn8.ReadOnly = true;
			this.DataGridViewTextBoxColumn8.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
			this.DataGridViewComboBoxColumn7.DisplayStyle = global::System.Windows.Forms.DataGridViewComboBoxDisplayStyle.ComboBox;
			this.DataGridViewComboBoxColumn7.DisplayStyleForCurrentCellOnly = true;
			this.DataGridViewComboBoxColumn7.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
			this.DataGridViewComboBoxColumn7.HeaderText = "value";
			this.DataGridViewComboBoxColumn7.Name = "DataGridViewComboBoxColumn7";
			this.DataGridViewComboBoxColumn7.Resizable = global::System.Windows.Forms.DataGridViewTriState.False;
			this.Label9.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.Label9.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label9.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			this.Label9.Location = new global::System.Drawing.Point(0, 833);
			this.Label9.Name = "Label9";
			this.Label9.Padding = new global::System.Windows.Forms.Padding(0, 0, 0, 4);
			this.Label9.Size = new global::System.Drawing.Size(352, 24);
			this.Label9.TabIndex = 19;
			this.Label9.Text = "Activity status";
			this.Label9.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.DGV7.AllowUserToAddRows = false;
			this.DGV7.AllowUserToDeleteRows = false;
			this.DGV7.AllowUserToResizeColumns = false;
			this.DGV7.AllowUserToResizeRows = false;
			this.DGV7.AutoSizeColumnsMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
			this.DGV7.AutoSizeRowsMode = global::System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
			this.DGV7.BackgroundColor = global::System.Drawing.Color.Black;
			this.DGV7.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.DGV7.CellBorderStyle = global::System.Windows.Forms.DataGridViewCellBorderStyle.None;
			this.DGV7.ColumnHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle5.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle5.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle5.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle5.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle5.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle5.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle5.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DGV7.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
			this.DGV7.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
			this.DGV7.ColumnHeadersVisible = false;
			this.DGV7.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.DataGridViewTextBoxColumn7,
				this.DataGridViewComboBoxColumn6
			});
			dataGridViewCellStyle6.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle6.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle6.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle6.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			dataGridViewCellStyle6.SelectionBackColor = global::System.Drawing.Color.FromArgb(51, 153, 255);
			dataGridViewCellStyle6.SelectionForeColor = global::System.Drawing.Color.FromArgb(240, 240, 240);
			dataGridViewCellStyle6.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DGV7.DefaultCellStyle = dataGridViewCellStyle6;
			this.DGV7.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.DGV7.EditMode = global::System.Windows.Forms.DataGridViewEditMode.EditOnEnter;
			this.DGV7.EnableHeadersVisualStyles = false;
			this.DGV7.GridColor = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.DGV7.Location = new global::System.Drawing.Point(0, 758);
			this.DGV7.Name = "DGV7";
			this.DGV7.RowHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
			this.DGV7.RowHeadersVisible = false;
			this.DGV7.ScrollBars = global::System.Windows.Forms.ScrollBars.None;
			this.DGV7.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.DGV7.Size = new global::System.Drawing.Size(352, 75);
			this.DGV7.TabIndex = 18;
			this.DataGridViewTextBoxColumn7.HeaderText = "Property";
			this.DataGridViewTextBoxColumn7.Name = "DataGridViewTextBoxColumn7";
			this.DataGridViewTextBoxColumn7.ReadOnly = true;
			this.DataGridViewTextBoxColumn7.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
			this.DataGridViewComboBoxColumn6.DisplayStyle = global::System.Windows.Forms.DataGridViewComboBoxDisplayStyle.ComboBox;
			this.DataGridViewComboBoxColumn6.DisplayStyleForCurrentCellOnly = true;
			this.DataGridViewComboBoxColumn6.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
			this.DataGridViewComboBoxColumn6.HeaderText = "value";
			this.DataGridViewComboBoxColumn6.Name = "DataGridViewComboBoxColumn6";
			this.DataGridViewComboBoxColumn6.Resizable = global::System.Windows.Forms.DataGridViewTriState.False;
			this.Label8.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.Label8.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label8.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			this.Label8.Location = new global::System.Drawing.Point(0, 734);
			this.Label8.Name = "Label8";
			this.Label8.Padding = new global::System.Windows.Forms.Padding(0, 0, 0, 4);
			this.Label8.Size = new global::System.Drawing.Size(352, 24);
			this.Label8.TabIndex = 17;
			this.Label8.Text = "Flags";
			this.Label8.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.DGV6.AllowUserToAddRows = false;
			this.DGV6.AllowUserToDeleteRows = false;
			this.DGV6.AllowUserToResizeColumns = false;
			this.DGV6.AllowUserToResizeRows = false;
			this.DGV6.AutoSizeColumnsMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
			this.DGV6.AutoSizeRowsMode = global::System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
			this.DGV6.BackgroundColor = global::System.Drawing.Color.Black;
			this.DGV6.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.DGV6.CellBorderStyle = global::System.Windows.Forms.DataGridViewCellBorderStyle.None;
			this.DGV6.ColumnHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle7.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle7.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle7.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle7.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle7.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle7.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle7.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DGV6.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle7;
			this.DGV6.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
			this.DGV6.ColumnHeadersVisible = false;
			this.DGV6.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.DataGridViewTextBoxColumn6,
				this.DataGridViewComboBoxColumn5
			});
			dataGridViewCellStyle8.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle8.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle8.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle8.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			dataGridViewCellStyle8.SelectionBackColor = global::System.Drawing.Color.FromArgb(51, 153, 255);
			dataGridViewCellStyle8.SelectionForeColor = global::System.Drawing.Color.FromArgb(240, 240, 240);
			dataGridViewCellStyle8.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DGV6.DefaultCellStyle = dataGridViewCellStyle8;
			this.DGV6.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.DGV6.EditMode = global::System.Windows.Forms.DataGridViewEditMode.EditOnEnter;
			this.DGV6.EnableHeadersVisualStyles = false;
			this.DGV6.GridColor = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.DGV6.Location = new global::System.Drawing.Point(0, 659);
			this.DGV6.Name = "DGV6";
			this.DGV6.RowHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
			this.DGV6.RowHeadersVisible = false;
			this.DGV6.ScrollBars = global::System.Windows.Forms.ScrollBars.None;
			this.DGV6.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.DGV6.Size = new global::System.Drawing.Size(352, 75);
			this.DGV6.TabIndex = 16;
			this.DataGridViewTextBoxColumn6.HeaderText = "Property";
			this.DataGridViewTextBoxColumn6.Name = "DataGridViewTextBoxColumn6";
			this.DataGridViewTextBoxColumn6.ReadOnly = true;
			this.DataGridViewTextBoxColumn6.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
			this.DataGridViewComboBoxColumn5.DisplayStyle = global::System.Windows.Forms.DataGridViewComboBoxDisplayStyle.ComboBox;
			this.DataGridViewComboBoxColumn5.DisplayStyleForCurrentCellOnly = true;
			this.DataGridViewComboBoxColumn5.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
			this.DataGridViewComboBoxColumn5.HeaderText = "value";
			this.DataGridViewComboBoxColumn5.Name = "DataGridViewComboBoxColumn5";
			this.DataGridViewComboBoxColumn5.Resizable = global::System.Windows.Forms.DataGridViewTriState.False;
			this.Label7.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.Label7.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label7.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			this.Label7.Location = new global::System.Drawing.Point(0, 635);
			this.Label7.Name = "Label7";
			this.Label7.Padding = new global::System.Windows.Forms.Padding(0, 0, 0, 4);
			this.Label7.Size = new global::System.Drawing.Size(352, 24);
			this.Label7.TabIndex = 15;
			this.Label7.Text = "Font";
			this.Label7.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.DGV5.AllowUserToAddRows = false;
			this.DGV5.AllowUserToDeleteRows = false;
			this.DGV5.AllowUserToResizeColumns = false;
			this.DGV5.AllowUserToResizeRows = false;
			this.DGV5.AutoSizeColumnsMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
			this.DGV5.AutoSizeRowsMode = global::System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
			this.DGV5.BackgroundColor = global::System.Drawing.Color.Black;
			this.DGV5.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.DGV5.CellBorderStyle = global::System.Windows.Forms.DataGridViewCellBorderStyle.None;
			this.DGV5.ColumnHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle9.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle9.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle9.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle9.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle9.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle9.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle9.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DGV5.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle9;
			this.DGV5.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
			this.DGV5.ColumnHeadersVisible = false;
			this.DGV5.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.DataGridViewTextBoxColumn5,
				this.Column3
			});
			dataGridViewCellStyle10.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle10.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle10.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle10.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			dataGridViewCellStyle10.SelectionBackColor = global::System.Drawing.Color.FromArgb(51, 153, 255);
			dataGridViewCellStyle10.SelectionForeColor = global::System.Drawing.Color.FromArgb(240, 240, 240);
			dataGridViewCellStyle10.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DGV5.DefaultCellStyle = dataGridViewCellStyle10;
			this.DGV5.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.DGV5.EditMode = global::System.Windows.Forms.DataGridViewEditMode.EditOnEnter;
			this.DGV5.EnableHeadersVisualStyles = false;
			this.DGV5.GridColor = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.DGV5.Location = new global::System.Drawing.Point(0, 560);
			this.DGV5.Name = "DGV5";
			this.DGV5.RowHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
			this.DGV5.RowHeadersVisible = false;
			this.DGV5.ScrollBars = global::System.Windows.Forms.ScrollBars.None;
			this.DGV5.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.DGV5.Size = new global::System.Drawing.Size(352, 75);
			this.DGV5.TabIndex = 14;
			this.DataGridViewTextBoxColumn5.FillWeight = 178.6802f;
			this.DataGridViewTextBoxColumn5.HeaderText = "Property";
			this.DataGridViewTextBoxColumn5.Name = "DataGridViewTextBoxColumn5";
			this.DataGridViewTextBoxColumn5.ReadOnly = true;
			this.DataGridViewTextBoxColumn5.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
			this.Column3.AutoSizeMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnMode.AllCells;
			dataGridViewCellStyle11.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
			dataGridViewCellStyle11.NullValue = global::System.Runtime.CompilerServices.RuntimeHelpers.GetObjectValue(componentResourceManager.GetObject("DataGridViewCellStyle10.NullValue"));
			this.Column3.DefaultCellStyle = dataGridViewCellStyle11;
			this.Column3.FillWeight = 21f;
			this.Column3.HeaderText = "value";
			this.Column3.ImageLayout = global::System.Windows.Forms.DataGridViewImageCellLayout.Stretch;
			this.Column3.Name = "Column3";
			this.Column3.Resizable = global::System.Windows.Forms.DataGridViewTriState.False;
			this.Column3.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.Automatic;
			this.Column3.Width = 5;
			this.Label6.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.Label6.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label6.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			this.Label6.Location = new global::System.Drawing.Point(0, 536);
			this.Label6.Name = "Label6";
			this.Label6.Padding = new global::System.Windows.Forms.Padding(0, 0, 0, 4);
			this.Label6.Size = new global::System.Drawing.Size(352, 24);
			this.Label6.TabIndex = 13;
			this.Label6.Text = "Colors";
			this.Label6.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.DGV4.AllowUserToAddRows = false;
			this.DGV4.AllowUserToDeleteRows = false;
			this.DGV4.AllowUserToResizeColumns = false;
			this.DGV4.AllowUserToResizeRows = false;
			this.DGV4.AutoSizeColumnsMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
			this.DGV4.AutoSizeRowsMode = global::System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
			this.DGV4.BackgroundColor = global::System.Drawing.Color.Black;
			this.DGV4.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.DGV4.CellBorderStyle = global::System.Windows.Forms.DataGridViewCellBorderStyle.None;
			this.DGV4.ColumnHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle12.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle12.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle12.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle12.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle12.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle12.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle12.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DGV4.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle12;
			this.DGV4.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
			this.DGV4.ColumnHeadersVisible = false;
			this.DGV4.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.DataGridViewTextBoxColumn4,
				this.DataGridViewComboBoxColumn4
			});
			dataGridViewCellStyle13.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle13.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle13.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle13.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			dataGridViewCellStyle13.SelectionBackColor = global::System.Drawing.Color.FromArgb(51, 153, 255);
			dataGridViewCellStyle13.SelectionForeColor = global::System.Drawing.Color.FromArgb(240, 240, 240);
			dataGridViewCellStyle13.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DGV4.DefaultCellStyle = dataGridViewCellStyle13;
			this.DGV4.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.DGV4.EditMode = global::System.Windows.Forms.DataGridViewEditMode.EditOnEnter;
			this.DGV4.EnableHeadersVisualStyles = false;
			this.DGV4.GridColor = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.DGV4.Location = new global::System.Drawing.Point(0, 461);
			this.DGV4.Name = "DGV4";
			this.DGV4.RowHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
			this.DGV4.RowHeadersVisible = false;
			this.DGV4.ScrollBars = global::System.Windows.Forms.ScrollBars.None;
			this.DGV4.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.DGV4.Size = new global::System.Drawing.Size(352, 75);
			this.DGV4.TabIndex = 12;
			this.DataGridViewTextBoxColumn4.HeaderText = "Property";
			this.DataGridViewTextBoxColumn4.Name = "DataGridViewTextBoxColumn4";
			this.DataGridViewTextBoxColumn4.ReadOnly = true;
			this.DataGridViewTextBoxColumn4.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
			this.DataGridViewComboBoxColumn4.DisplayStyle = global::System.Windows.Forms.DataGridViewComboBoxDisplayStyle.ComboBox;
			this.DataGridViewComboBoxColumn4.DisplayStyleForCurrentCellOnly = true;
			this.DataGridViewComboBoxColumn4.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
			this.DataGridViewComboBoxColumn4.HeaderText = "value";
			this.DataGridViewComboBoxColumn4.Name = "DataGridViewComboBoxColumn4";
			this.DataGridViewComboBoxColumn4.Resizable = global::System.Windows.Forms.DataGridViewTriState.False;
			this.Label5.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.Label5.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label5.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			this.Label5.Location = new global::System.Drawing.Point(0, 437);
			this.Label5.Name = "Label5";
			this.Label5.Padding = new global::System.Windows.Forms.Padding(0, 0, 0, 4);
			this.Label5.Size = new global::System.Drawing.Size(352, 24);
			this.Label5.TabIndex = 11;
			this.Label5.Text = "Saving data";
			this.Label5.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.DGV3.AllowUserToAddRows = false;
			this.DGV3.AllowUserToDeleteRows = false;
			this.DGV3.AllowUserToResizeColumns = false;
			this.DGV3.AllowUserToResizeRows = false;
			this.DGV3.AutoSizeColumnsMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
			this.DGV3.AutoSizeRowsMode = global::System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
			this.DGV3.BackgroundColor = global::System.Drawing.Color.Black;
			this.DGV3.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.DGV3.CellBorderStyle = global::System.Windows.Forms.DataGridViewCellBorderStyle.None;
			this.DGV3.ColumnHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle14.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle14.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle14.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle14.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle14.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle14.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle14.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DGV3.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle14;
			this.DGV3.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
			this.DGV3.ColumnHeadersVisible = false;
			this.DGV3.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.DataGridViewTextBoxColumn3,
				this.DataGridViewComboBoxColumn3
			});
			dataGridViewCellStyle15.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle15.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle15.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle15.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			dataGridViewCellStyle15.SelectionBackColor = global::System.Drawing.Color.FromArgb(51, 153, 255);
			dataGridViewCellStyle15.SelectionForeColor = global::System.Drawing.Color.FromArgb(240, 240, 240);
			dataGridViewCellStyle15.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DGV3.DefaultCellStyle = dataGridViewCellStyle15;
			this.DGV3.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.DGV3.EditMode = global::System.Windows.Forms.DataGridViewEditMode.EditOnEnter;
			this.DGV3.EnableHeadersVisualStyles = false;
			this.DGV3.GridColor = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.DGV3.Location = new global::System.Drawing.Point(0, 362);
			this.DGV3.Name = "DGV3";
			this.DGV3.RowHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
			this.DGV3.RowHeadersVisible = false;
			this.DGV3.ScrollBars = global::System.Windows.Forms.ScrollBars.None;
			this.DGV3.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.DGV3.Size = new global::System.Drawing.Size(352, 75);
			this.DGV3.TabIndex = 10;
			this.DataGridViewTextBoxColumn3.HeaderText = "Property";
			this.DataGridViewTextBoxColumn3.Name = "DataGridViewTextBoxColumn3";
			this.DataGridViewTextBoxColumn3.ReadOnly = true;
			this.DataGridViewTextBoxColumn3.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
			this.DataGridViewComboBoxColumn3.DisplayStyle = global::System.Windows.Forms.DataGridViewComboBoxDisplayStyle.ComboBox;
			this.DataGridViewComboBoxColumn3.DisplayStyleForCurrentCellOnly = true;
			this.DataGridViewComboBoxColumn3.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
			this.DataGridViewComboBoxColumn3.HeaderText = "value";
			this.DataGridViewComboBoxColumn3.Name = "DataGridViewComboBoxColumn3";
			this.DataGridViewComboBoxColumn3.Resizable = global::System.Windows.Forms.DataGridViewTriState.False;
			this.Label4.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.Label4.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label4.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			this.Label4.Location = new global::System.Drawing.Point(0, 338);
			this.Label4.Name = "Label4";
			this.Label4.Padding = new global::System.Windows.Forms.Padding(0, 0, 0, 4);
			this.Label4.Size = new global::System.Drawing.Size(352, 24);
			this.Label4.TabIndex = 9;
			this.Label4.Text = "Location Manager";
			this.Label4.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.DGV2.AllowUserToAddRows = false;
			this.DGV2.AllowUserToDeleteRows = false;
			this.DGV2.AllowUserToResizeColumns = false;
			this.DGV2.AllowUserToResizeRows = false;
			this.DGV2.AutoSizeColumnsMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
			this.DGV2.AutoSizeRowsMode = global::System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
			this.DGV2.BackgroundColor = global::System.Drawing.Color.Black;
			this.DGV2.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.DGV2.CellBorderStyle = global::System.Windows.Forms.DataGridViewCellBorderStyle.None;
			this.DGV2.ColumnHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle16.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle16.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle16.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle16.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle16.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle16.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle16.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DGV2.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle16;
			this.DGV2.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
			this.DGV2.ColumnHeadersVisible = false;
			this.DGV2.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.DataGridViewTextBoxColumn2,
				this.DataGridViewComboBoxColumn2
			});
			dataGridViewCellStyle17.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle17.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle17.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle17.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			dataGridViewCellStyle17.SelectionBackColor = global::System.Drawing.Color.FromArgb(51, 153, 255);
			dataGridViewCellStyle17.SelectionForeColor = global::System.Drawing.Color.FromArgb(240, 240, 240);
			dataGridViewCellStyle17.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DGV2.DefaultCellStyle = dataGridViewCellStyle17;
			this.DGV2.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.DGV2.EditMode = global::System.Windows.Forms.DataGridViewEditMode.EditOnEnter;
			this.DGV2.EnableHeadersVisualStyles = false;
			this.DGV2.GridColor = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.DGV2.Location = new global::System.Drawing.Point(0, 263);
			this.DGV2.Name = "DGV2";
			this.DGV2.RowHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
			this.DGV2.RowHeadersVisible = false;
			this.DGV2.ScrollBars = global::System.Windows.Forms.ScrollBars.None;
			this.DGV2.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.DGV2.Size = new global::System.Drawing.Size(352, 75);
			this.DGV2.TabIndex = 8;
			this.DataGridViewTextBoxColumn2.HeaderText = "Property";
			this.DataGridViewTextBoxColumn2.Name = "DataGridViewTextBoxColumn2";
			this.DataGridViewTextBoxColumn2.ReadOnly = true;
			this.DataGridViewTextBoxColumn2.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
			this.DataGridViewComboBoxColumn2.DisplayStyle = global::System.Windows.Forms.DataGridViewComboBoxDisplayStyle.ComboBox;
			this.DataGridViewComboBoxColumn2.DisplayStyleForCurrentCellOnly = true;
			this.DataGridViewComboBoxColumn2.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
			this.DataGridViewComboBoxColumn2.HeaderText = "value";
			this.DataGridViewComboBoxColumn2.Name = "DataGridViewComboBoxColumn2";
			this.DataGridViewComboBoxColumn2.Resizable = global::System.Windows.Forms.DataGridViewTriState.False;
			this.Label3.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.Label3.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label3.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			this.Label3.Location = new global::System.Drawing.Point(0, 239);
			this.Label3.Name = "Label3";
			this.Label3.Padding = new global::System.Windows.Forms.Padding(0, 0, 0, 4);
			this.Label3.Size = new global::System.Drawing.Size(352, 24);
			this.Label3.TabIndex = 7;
			this.Label3.Text = "Camera Manager";
			this.Label3.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.DGV1.AllowUserToAddRows = false;
			this.DGV1.AllowUserToDeleteRows = false;
			this.DGV1.AllowUserToResizeColumns = false;
			this.DGV1.AllowUserToResizeRows = false;
			this.DGV1.AutoSizeColumnsMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
			this.DGV1.AutoSizeRowsMode = global::System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
			this.DGV1.BackgroundColor = global::System.Drawing.Color.Black;
			this.DGV1.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.DGV1.CellBorderStyle = global::System.Windows.Forms.DataGridViewCellBorderStyle.None;
			this.DGV1.ColumnHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle18.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle18.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle18.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle18.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle18.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle18.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle18.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DGV1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle18;
			this.DGV1.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
			this.DGV1.ColumnHeadersVisible = false;
			this.DGV1.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.DataGridViewTextBoxColumn1,
				this.DataGridViewComboBoxColumn1
			});
			dataGridViewCellStyle19.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle19.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle19.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle19.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			dataGridViewCellStyle19.SelectionBackColor = global::System.Drawing.Color.FromArgb(51, 153, 255);
			dataGridViewCellStyle19.SelectionForeColor = global::System.Drawing.Color.FromArgb(240, 240, 240);
			dataGridViewCellStyle19.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DGV1.DefaultCellStyle = dataGridViewCellStyle19;
			this.DGV1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.DGV1.EditMode = global::System.Windows.Forms.DataGridViewEditMode.EditOnEnter;
			this.DGV1.EnableHeadersVisualStyles = false;
			this.DGV1.GridColor = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.DGV1.Location = new global::System.Drawing.Point(0, 164);
			this.DGV1.Name = "DGV1";
			this.DGV1.RowHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
			this.DGV1.RowHeadersVisible = false;
			this.DGV1.ScrollBars = global::System.Windows.Forms.ScrollBars.None;
			this.DGV1.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.DGV1.Size = new global::System.Drawing.Size(352, 75);
			this.DGV1.TabIndex = 6;
			this.DataGridViewTextBoxColumn1.HeaderText = "Property";
			this.DataGridViewTextBoxColumn1.Name = "DataGridViewTextBoxColumn1";
			this.DataGridViewTextBoxColumn1.ReadOnly = true;
			this.DataGridViewTextBoxColumn1.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
			this.DataGridViewComboBoxColumn1.DisplayStyle = global::System.Windows.Forms.DataGridViewComboBoxDisplayStyle.ComboBox;
			this.DataGridViewComboBoxColumn1.DisplayStyleForCurrentCellOnly = true;
			this.DataGridViewComboBoxColumn1.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
			this.DataGridViewComboBoxColumn1.HeaderText = "value";
			this.DataGridViewComboBoxColumn1.Name = "DataGridViewComboBoxColumn1";
			this.DataGridViewComboBoxColumn1.Resizable = global::System.Windows.Forms.DataGridViewTriState.False;
			this.Label2.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.Label2.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label2.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			this.Label2.Location = new global::System.Drawing.Point(0, 140);
			this.Label2.Name = "Label2";
			this.Label2.Padding = new global::System.Windows.Forms.Padding(0, 0, 0, 4);
			this.Label2.Size = new global::System.Drawing.Size(352, 24);
			this.Label2.TabIndex = 5;
			this.Label2.Text = "Alert";
			this.Label2.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.DGV0.AllowUserToAddRows = false;
			this.DGV0.AllowUserToDeleteRows = false;
			this.DGV0.AllowUserToResizeColumns = false;
			this.DGV0.AllowUserToResizeRows = false;
			this.DGV0.AutoSizeColumnsMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
			this.DGV0.AutoSizeRowsMode = global::System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
			this.DGV0.BackgroundColor = global::System.Drawing.Color.Black;
			this.DGV0.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.DGV0.CellBorderStyle = global::System.Windows.Forms.DataGridViewCellBorderStyle.None;
			this.DGV0.ColumnHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle20.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle20.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle20.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle20.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			dataGridViewCellStyle20.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle20.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle20.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DGV0.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle20;
			this.DGV0.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.DGV0.ColumnHeadersVisible = false;
			this.DGV0.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.Column1,
				this.Column2
			});
			dataGridViewCellStyle21.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle21.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle21.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle21.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			dataGridViewCellStyle21.SelectionBackColor = global::System.Drawing.Color.FromArgb(51, 153, 255);
			dataGridViewCellStyle21.SelectionForeColor = global::System.Drawing.Color.FromArgb(240, 240, 240);
			dataGridViewCellStyle21.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DGV0.DefaultCellStyle = dataGridViewCellStyle21;
			this.DGV0.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.DGV0.EditMode = global::System.Windows.Forms.DataGridViewEditMode.EditOnEnter;
			this.DGV0.EnableHeadersVisualStyles = false;
			this.DGV0.GridColor = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.DGV0.Location = new global::System.Drawing.Point(0, 24);
			this.DGV0.Name = "DGV0";
			this.DGV0.RowHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
			this.DGV0.RowHeadersVisible = false;
			this.DGV0.ScrollBars = global::System.Windows.Forms.ScrollBars.None;
			this.DGV0.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.DGV0.Size = new global::System.Drawing.Size(352, 116);
			this.DGV0.TabIndex = 4;
			this.Column1.HeaderText = "Property";
			this.Column1.Name = "Column1";
			this.Column1.ReadOnly = true;
			this.Column1.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
			this.Column2.DisplayStyle = global::System.Windows.Forms.DataGridViewComboBoxDisplayStyle.ComboBox;
			this.Column2.DisplayStyleForCurrentCellOnly = true;
			this.Column2.FlatStyle = global::System.Windows.Forms.FlatStyle.System;
			this.Column2.HeaderText = "value";
			this.Column2.Name = "Column2";
			this.Column2.Resizable = global::System.Windows.Forms.DataGridViewTriState.False;
			this.Label1.BackColor = global::System.Drawing.Color.FromArgb(35, 35, 35);
			this.Label1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label1.ForeColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			this.Label1.Location = new global::System.Drawing.Point(0, 0);
			this.Label1.Name = "Label1";
			this.Label1.Padding = new global::System.Windows.Forms.Padding(0, 0, 0, 4);
			this.Label1.Size = new global::System.Drawing.Size(352, 24);
			this.Label1.TabIndex = 0;
			this.Label1.Text = "Socket";
			this.Label1.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.SV.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.SV.BackColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			this.SV.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.SV.ForeColor = global::System.Drawing.Color.Black;
			this.SV.Location = new global::System.Drawing.Point(285, 8);
			this.SV.Name = "SV";
			this.SV.Size = new global::System.Drawing.Size(81, 23);
			this.SV.TabIndex = 14;
			this.SV.Text = "Save";
			this.SV.UseVisualStyleBackColor = false;
			this.DL.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.DL.BackColor = global::System.Drawing.Color.FromArgb(190, 190, 190);
			this.DL.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.DL.ForeColor = global::System.Drawing.Color.Black;
			this.DL.Location = new global::System.Drawing.Point(198, 8);
			this.DL.Name = "DL";
			this.DL.Size = new global::System.Drawing.Size(81, 23);
			this.DL.TabIndex = 15;
			this.DL.Text = "Reset";
			this.DL.UseVisualStyleBackColor = false;
			this.Panel2.BackColor = global::System.Drawing.Color.Black;
			this.Panel2.Controls.Add(this.SV);
			this.Panel2.Controls.Add(this.DL);
			this.Panel2.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.Panel2.Location = new global::System.Drawing.Point(0, 354);
			this.Panel2.Name = "Panel2";
			this.Panel2.Size = new global::System.Drawing.Size(369, 34);
			this.Panel2.TabIndex = 16;
			this.TOpacity.Interval = 1;
			this.ctxPacket.Items.AddRange(new global::System.Windows.Forms.ToolStripItem[]
			{
				this.DefaultToolStripMenuItem,
				this.clr_1,
				this.clr_2,
				this.Clr3ToolStripMenuItem,
				this.Clr4ToolStripMenuItem,
				this.Clr5ToolStripMenuItem,
				this.Clr6ToolStripMenuItem,
				this.Clr7ToolStripMenuItem,
				this.Clr8ToolStripMenuItem,
				this.Clr9ToolStripMenuItem
			});
			this.ctxPacket.Name = "ctxPacket";
			this.ctxPacket.ShowImageMargin = false;
			this.ctxPacket.Size = new global::System.Drawing.Size(144, 224);
			this.DefaultToolStripMenuItem.Name = "DefaultToolStripMenuItem";
			this.DefaultToolStripMenuItem.Size = new global::System.Drawing.Size(143, 22);
			this.DefaultToolStripMenuItem.Text = "Dove Gray";
			this.clr_1.Name = "clr_1";
			this.clr_1.Size = new global::System.Drawing.Size(143, 22);
			this.clr_1.Text = "Curious Blue";
			this.clr_2.Name = "clr_2";
			this.clr_2.Size = new global::System.Drawing.Size(143, 22);
			this.clr_2.Text = "Keppel";
			this.Clr3ToolStripMenuItem.Name = "Clr3ToolStripMenuItem";
			this.Clr3ToolStripMenuItem.Size = new global::System.Drawing.Size(143, 22);
			this.Clr3ToolStripMenuItem.Text = "Pickled Bluewood";
			this.Clr4ToolStripMenuItem.Name = "Clr4ToolStripMenuItem";
			this.Clr4ToolStripMenuItem.Size = new global::System.Drawing.Size(143, 22);
			this.Clr4ToolStripMenuItem.Text = "Cerise";
			this.Clr5ToolStripMenuItem.Name = "Clr5ToolStripMenuItem";
			this.Clr5ToolStripMenuItem.Size = new global::System.Drawing.Size(143, 22);
			this.Clr5ToolStripMenuItem.Text = "Mine Shaft";
			this.Clr6ToolStripMenuItem.Name = "Clr6ToolStripMenuItem";
			this.Clr6ToolStripMenuItem.Size = new global::System.Drawing.Size(143, 22);
			this.Clr6ToolStripMenuItem.Text = "Lochmara";
			this.Clr7ToolStripMenuItem.Name = "Clr7ToolStripMenuItem";
			this.Clr7ToolStripMenuItem.Size = new global::System.Drawing.Size(143, 22);
			this.Clr7ToolStripMenuItem.Text = "Steel Gray";
			this.Clr8ToolStripMenuItem.Name = "Clr8ToolStripMenuItem";
			this.Clr8ToolStripMenuItem.Size = new global::System.Drawing.Size(143, 22);
			this.Clr8ToolStripMenuItem.Text = "Scorpion";
			this.Clr9ToolStripMenuItem.Name = "Clr9ToolStripMenuItem";
			this.Clr9ToolStripMenuItem.Size = new global::System.Drawing.Size(143, 22);
			this.Clr9ToolStripMenuItem.Text = "Rob Roy";
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(369, 388);
			base.Controls.Add(this.Panel1);
			base.Controls.Add(this.Panel2);
			base.Name = "Settings";
			base.Opacity = 0.0;
			this.Text = "Settings";
			this.Panel1.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.DGV9).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV8).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV7).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV6).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV5).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV4).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV3).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.DGV0).EndInit();
			this.Panel2.ResumeLayout(false);
			this.ctxPacket.ResumeLayout(false);
			base.ResumeLayout(false);
		}

		// Token: 0x040009C9 RID: 2505
		private global::System.ComponentModel.Container components;
	}
}
