namespace Craxs_Rat
{
	// Token: 0x020000C8 RID: 200
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class ScreenShoter : global::System.Windows.Forms.Form
	{
		// Token: 0x06000EBD RID: 3773 RVA: 0x0009B688 File Offset: 0x00099888
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.components != null)
				{
					((global::System.IDisposable)this.components).Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000EBE RID: 3774 RVA: 0x0009B6CC File Offset: 0x000998CC
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::Craxs_Rat.ScreenShoter));
			this.Save = new global::DrakeUI.Framework.DrakeUICheckBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.StopButton = new global::System.Windows.Forms.Button();
			this.StartButton = new global::System.Windows.Forms.Button();
			this.Livepicbox = new global::System.Windows.Forms.PictureBox();
			this.vewpnl = new global::System.Windows.Forms.Panel();
			this.Panel8 = new global::System.Windows.Forms.Panel();
			this.toptitle = new global::System.Windows.Forms.Label();
			this.PBS = new global::MetroSet_UI.Controls.MetroSetProgressBar();
			this.Button7 = new global::System.Windows.Forms.Button();
			this.Button6 = new global::System.Windows.Forms.Button();
			this.Button5 = new global::System.Windows.Forms.Button();
			this.textsend = new global::System.Windows.Forms.TextBox();
			this.Enterbutton = new global::System.Windows.Forms.Button();
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.Panel2 = new global::System.Windows.Forms.Panel();
			this.DrakeUIAvatar1 = new global::DrakeUI.Framework.DrakeUIAvatar();
			this.PictureBox3 = new global::System.Windows.Forms.PictureBox();
			this.PictureBox2 = new global::System.Windows.Forms.PictureBox();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.Panel3 = new global::System.Windows.Forms.Panel();
			this.Panel4 = new global::System.Windows.Forms.Panel();
			this.Panel5 = new global::System.Windows.Forms.Panel();
			this.Panel6 = new global::System.Windows.Forms.Panel();
			this.Panel7 = new global::System.Windows.Forms.Panel();
			this.combosize = new global::DrakeUI.Framework.DrakeUIComboBox();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Qualtibox = new global::DrakeUI.Framework.DrakeUIComboBox();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.FPSBOX = new global::DrakeUI.Framework.DrakeUIComboBox();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Dismisbtn = new global::DrakeUI.Framework.DrakeUIAvatar();
			this.SKtype = new global::DrakeUI.Framework.DrakeUIComboBox();
			this.DrakeUIAvatar2 = new global::DrakeUI.Framework.DrakeUIAvatar();
			this.checkblock = new global::DrakeUI.Framework.DrakeUICheckBox();
			this.DrakeUIToolTip1 = new global::DrakeUI.Framework.DrakeUIToolTip(this.components);
			this.Timer1 = new global::System.Windows.Forms.Timer(this.components);
			this.refreshtimer = new global::System.Windows.Forms.Timer(this.components);
			this.presstimer = new global::System.Windows.Forms.Timer(this.components);
			((global::System.ComponentModel.ISupportInitialize)this.Livepicbox).BeginInit();
			this.vewpnl.SuspendLayout();
			this.Panel8.SuspendLayout();
			this.Panel1.SuspendLayout();
			this.Panel2.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).BeginInit();
			this.Panel4.SuspendLayout();
			this.Panel5.SuspendLayout();
			this.Panel6.SuspendLayout();
			this.Panel7.SuspendLayout();
			base.SuspendLayout();
			this.Save.CheckBoxColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Save.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Save.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Save.Font = new global::System.Drawing.Font("Roboto", 10f);
			this.Save.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Save.Location = new global::System.Drawing.Point(0, 168);
			this.Save.Margin = new global::System.Windows.Forms.Padding(4);
			this.Save.Name = "Save";
			this.Save.Padding = new global::System.Windows.Forms.Padding(22, 0, 0, 0);
			this.Save.Size = new global::System.Drawing.Size(100, 69);
			this.Save.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.Save.StyleCustomMode = true;
			this.Save.TabIndex = 19;
			this.Save.Text = "Record";
			this.Save.TextAlign = global::System.Drawing.ContentAlignment.TopLeft;
			this.DrakeUIToolTip1.SetToolTip(this.Save, "Record Screen");
			this.Label2.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label2.Font = new global::System.Drawing.Font("Roboto", 10f);
			this.Label2.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Label2.Location = new global::System.Drawing.Point(0, 431);
			this.Label2.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(100, 21);
			this.Label2.TabIndex = 18;
			this.Label2.Text = "FPS .";
			this.Label2.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Label1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label1.Font = new global::System.Drawing.Font("Roboto", 10f);
			this.Label1.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Label1.Location = new global::System.Drawing.Point(0, 496);
			this.Label1.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(100, 21);
			this.Label1.TabIndex = 15;
			this.Label1.Text = "Qualty";
			this.Label1.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.StopButton.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.StopButton.FlatAppearance.BorderColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.StopButton.FlatAppearance.BorderSize = 0;
			this.StopButton.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.StopButton.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.StopButton.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.StopButton.Font = new global::System.Drawing.Font("Roboto", 9f);
			this.StopButton.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.StopButton.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("StopButton.Image");
			this.StopButton.ImageAlign = global::System.Drawing.ContentAlignment.TopCenter;
			this.StopButton.Location = new global::System.Drawing.Point(0, 109);
			this.StopButton.Margin = new global::System.Windows.Forms.Padding(4);
			this.StopButton.Name = "StopButton";
			this.StopButton.Size = new global::System.Drawing.Size(100, 59);
			this.StopButton.TabIndex = 1;
			this.StopButton.Text = "Stop";
			this.StopButton.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.StopButton.UseVisualStyleBackColor = true;
			this.StartButton.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.StartButton.FlatAppearance.BorderColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.StartButton.FlatAppearance.BorderSize = 0;
			this.StartButton.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.StartButton.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.StartButton.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.StartButton.Font = new global::System.Drawing.Font("Roboto", 9f);
			this.StartButton.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.StartButton.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("StartButton.Image");
			this.StartButton.ImageAlign = global::System.Drawing.ContentAlignment.TopCenter;
			this.StartButton.Location = new global::System.Drawing.Point(0, 48);
			this.StartButton.Margin = new global::System.Windows.Forms.Padding(4);
			this.StartButton.Name = "StartButton";
			this.StartButton.Size = new global::System.Drawing.Size(100, 61);
			this.StartButton.TabIndex = 0;
			this.StartButton.Text = "Start";
			this.StartButton.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.StartButton.UseVisualStyleBackColor = true;
			this.Livepicbox.BackColor = global::System.Drawing.Color.Black;
			this.Livepicbox.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.Livepicbox.Enabled = false;
			this.Livepicbox.Location = new global::System.Drawing.Point(0, 22);
			this.Livepicbox.Margin = new global::System.Windows.Forms.Padding(4);
			this.Livepicbox.Name = "Livepicbox";
			this.Livepicbox.Size = new global::System.Drawing.Size(384, 718);
			this.Livepicbox.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.Livepicbox.TabIndex = 1;
			this.Livepicbox.TabStop = false;
			this.vewpnl.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.Stretch;
			this.vewpnl.Controls.Add(this.Livepicbox);
			this.vewpnl.Controls.Add(this.Panel8);
			this.vewpnl.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vewpnl.Location = new global::System.Drawing.Point(0, 0);
			this.vewpnl.Margin = new global::System.Windows.Forms.Padding(4);
			this.vewpnl.Name = "vewpnl";
			this.vewpnl.Size = new global::System.Drawing.Size(384, 740);
			this.vewpnl.TabIndex = 2;
			this.Panel8.BackColor = global::System.Drawing.Color.Black;
			this.Panel8.Controls.Add(this.toptitle);
			this.Panel8.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel8.Location = new global::System.Drawing.Point(0, 0);
			this.Panel8.Margin = new global::System.Windows.Forms.Padding(4);
			this.Panel8.Name = "Panel8";
			this.Panel8.Size = new global::System.Drawing.Size(384, 22);
			this.Panel8.TabIndex = 2;
			this.toptitle.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.toptitle.Font = new global::System.Drawing.Font("Roboto", 9f);
			this.toptitle.ForeColor = global::System.Drawing.Color.FromArgb(65, 177, 225);
			this.toptitle.Location = new global::System.Drawing.Point(0, 0);
			this.toptitle.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.toptitle.Name = "toptitle";
			this.toptitle.Size = new global::System.Drawing.Size(384, 22);
			this.toptitle.TabIndex = 21;
			this.toptitle.Text = "...";
			this.toptitle.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.PBS.BackgroundColor = global::System.Drawing.Color.Black;
			this.PBS.BorderColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.PBS.DisabledBackColor = global::System.Drawing.Color.Black;
			this.PBS.DisabledBorderColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.PBS.DisabledProgressColor = global::System.Drawing.Color.FromArgb(120, 65, 177, 225);
			this.PBS.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.PBS.IsDerivedStyle = true;
			this.PBS.Location = new global::System.Drawing.Point(0, 0);
			this.PBS.Margin = new global::System.Windows.Forms.Padding(4);
			this.PBS.Maximum = 100;
			this.PBS.Minimum = 0;
			this.PBS.Name = "PBS";
			this.PBS.Orientation = global::MetroSet_UI.Enums.ProgressOrientation.Vertical;
			this.PBS.ProgressColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.PBS.Size = new global::System.Drawing.Size(7, 740);
			this.PBS.Style = global::MetroSet_UI.Enums.Style.Custom;
			this.PBS.StyleManager = null;
			this.PBS.TabIndex = 2;
			this.PBS.Text = "MetroSetProgressBar1";
			this.PBS.ThemeAuthor = "Narwin";
			this.PBS.ThemeName = "MetroLite";
			this.PBS.Value = 0;
			this.Button7.BackColor = global::System.Drawing.Color.Transparent;
			this.Button7.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.Button7.FlatAppearance.BorderSize = 0;
			this.Button7.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button7.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button7.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button7.Font = new global::System.Drawing.Font("Roboto Black", 20f, global::System.Drawing.FontStyle.Bold);
			this.Button7.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Button7.Location = new global::System.Drawing.Point(0, 677);
			this.Button7.Margin = new global::System.Windows.Forms.Padding(4);
			this.Button7.Name = "Button7";
			this.Button7.Size = new global::System.Drawing.Size(100, 59);
			this.Button7.TabIndex = 8;
			this.Button7.Text = "⇶";
			this.DrakeUIToolTip1.SetToolTip(this.Button7, "Recent");
			this.Button7.UseVisualStyleBackColor = false;
			this.Button6.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.Button6.FlatAppearance.BorderSize = 0;
			this.Button6.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button6.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button6.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button6.Font = new global::System.Drawing.Font("Roboto Black", 20f, global::System.Drawing.FontStyle.Bold);
			this.Button6.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Button6.Location = new global::System.Drawing.Point(0, 736);
			this.Button6.Margin = new global::System.Windows.Forms.Padding(4);
			this.Button6.Name = "Button6";
			this.Button6.Size = new global::System.Drawing.Size(100, 59);
			this.Button6.TabIndex = 7;
			this.Button6.Text = "●";
			this.DrakeUIToolTip1.SetToolTip(this.Button6, "Home");
			this.Button6.UseVisualStyleBackColor = true;
			this.Button5.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.Button5.FlatAppearance.BorderSize = 0;
			this.Button5.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button5.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button5.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button5.Font = new global::System.Drawing.Font("Roboto Black", 20f, global::System.Drawing.FontStyle.Bold);
			this.Button5.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Button5.Location = new global::System.Drawing.Point(0, 795);
			this.Button5.Margin = new global::System.Windows.Forms.Padding(4);
			this.Button5.Name = "Button5";
			this.Button5.Size = new global::System.Drawing.Size(100, 59);
			this.Button5.TabIndex = 6;
			this.Button5.Text = "↩";
			this.DrakeUIToolTip1.SetToolTip(this.Button5, "Return");
			this.Button5.UseVisualStyleBackColor = true;
			this.textsend.BackColor = global::System.Drawing.Color.Black;
			this.textsend.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.textsend.ForeColor = global::System.Drawing.Color.White;
			this.textsend.Location = new global::System.Drawing.Point(45, 16);
			this.textsend.Margin = new global::System.Windows.Forms.Padding(4);
			this.textsend.Name = "textsend";
			this.textsend.Size = new global::System.Drawing.Size(274, 22);
			this.textsend.TabIndex = 11;
			this.DrakeUIToolTip1.SetToolTip(this.textsend, "Type Text in phone");
			this.Enterbutton.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.Enterbutton.FlatAppearance.BorderSize = 0;
			this.Enterbutton.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Enterbutton.Font = new global::System.Drawing.Font("Roboto Black", 10f, global::System.Drawing.FontStyle.Bold);
			this.Enterbutton.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Enterbutton.Location = new global::System.Drawing.Point(327, 15);
			this.Enterbutton.Margin = new global::System.Windows.Forms.Padding(4);
			this.Enterbutton.Name = "Enterbutton";
			this.Enterbutton.Size = new global::System.Drawing.Size(72, 30);
			this.Enterbutton.TabIndex = 10;
			this.Enterbutton.Text = "Enter";
			this.Enterbutton.TextAlign = global::System.Drawing.ContentAlignment.TopCenter;
			this.DrakeUIToolTip1.SetToolTip(this.Enterbutton, "Enter Text");
			this.Enterbutton.UseVisualStyleBackColor = true;
			this.Panel1.BackColor = global::System.Drawing.Color.Black;
			this.Panel1.Controls.Add(this.vewpnl);
			this.Panel1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.Panel1.Location = new global::System.Drawing.Point(23, 55);
			this.Panel1.Margin = new global::System.Windows.Forms.Padding(4);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new global::System.Drawing.Size(384, 740);
			this.Panel1.TabIndex = 2;
			this.Panel2.BackColor = global::System.Drawing.Color.Transparent;
			this.Panel2.Controls.Add(this.DrakeUIAvatar1);
			this.Panel2.Controls.Add(this.PictureBox3);
			this.Panel2.Controls.Add(this.PictureBox2);
			this.Panel2.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel2.Location = new global::System.Drawing.Point(0, 0);
			this.Panel2.Margin = new global::System.Windows.Forms.Padding(4);
			this.Panel2.Name = "Panel2";
			this.Panel2.Size = new global::System.Drawing.Size(430, 55);
			this.Panel2.TabIndex = 2;
			this.DrakeUIAvatar1.AvatarSize = 30;
			this.DrakeUIAvatar1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.DrakeUIAvatar1.FillColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIAvatar1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.DrakeUIAvatar1.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIAvatar1.Location = new global::System.Drawing.Point(337, 13);
			this.DrakeUIAvatar1.Name = "DrakeUIAvatar1";
			this.DrakeUIAvatar1.Size = new global::System.Drawing.Size(49, 39);
			this.DrakeUIAvatar1.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.DrakeUIAvatar1.Symbol = 61475;
			this.DrakeUIAvatar1.SymbolSize = 30;
			this.DrakeUIAvatar1.TabIndex = 2;
			this.DrakeUIAvatar1.Text = "DrakeUIAvatar1";
			this.DrakeUIToolTip1.SetToolTip(this.DrakeUIAvatar1, "Lock Screen");
			this.PictureBox3.Location = new global::System.Drawing.Point(83, 23);
			this.PictureBox3.Margin = new global::System.Windows.Forms.Padding(4);
			this.PictureBox3.Name = "PictureBox3";
			this.PictureBox3.Size = new global::System.Drawing.Size(36, 28);
			this.PictureBox3.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox3.TabIndex = 1;
			this.PictureBox3.TabStop = false;
			this.PictureBox2.Location = new global::System.Drawing.Point(35, 13);
			this.PictureBox2.Margin = new global::System.Windows.Forms.Padding(4);
			this.PictureBox2.Name = "PictureBox2";
			this.PictureBox2.Size = new global::System.Drawing.Size(40, 39);
			this.PictureBox2.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox2.TabIndex = 0;
			this.PictureBox2.TabStop = false;
			this.Button1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Button1.FlatAppearance.BorderColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Button1.FlatAppearance.BorderSize = 0;
			this.Button1.FlatAppearance.MouseDownBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button1.FlatAppearance.MouseOverBackColor = global::System.Drawing.Color.FromArgb(10, 10, 10);
			this.Button1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button1.Font = new global::System.Drawing.Font("Roboto Black", 12f, global::System.Drawing.FontStyle.Bold);
			this.Button1.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Button1.Location = new global::System.Drawing.Point(0, 0);
			this.Button1.Margin = new global::System.Windows.Forms.Padding(4);
			this.Button1.Name = "Button1";
			this.Button1.Size = new global::System.Drawing.Size(100, 48);
			this.Button1.TabIndex = 2;
			this.Button1.Text = "X";
			this.DrakeUIToolTip1.SetToolTip(this.Button1, "Close");
			this.Button1.UseVisualStyleBackColor = true;
			this.Panel3.BackColor = global::System.Drawing.Color.Transparent;
			this.Panel3.Dock = global::System.Windows.Forms.DockStyle.Right;
			this.Panel3.Location = new global::System.Drawing.Point(407, 55);
			this.Panel3.Margin = new global::System.Windows.Forms.Padding(4);
			this.Panel3.Name = "Panel3";
			this.Panel3.Size = new global::System.Drawing.Size(23, 740);
			this.Panel3.TabIndex = 3;
			this.Panel4.BackColor = global::System.Drawing.Color.Transparent;
			this.Panel4.Controls.Add(this.PBS);
			this.Panel4.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.Panel4.Location = new global::System.Drawing.Point(0, 55);
			this.Panel4.Margin = new global::System.Windows.Forms.Padding(4);
			this.Panel4.Name = "Panel4";
			this.Panel4.Size = new global::System.Drawing.Size(23, 740);
			this.Panel4.TabIndex = 4;
			this.Panel5.BackColor = global::System.Drawing.Color.Transparent;
			this.Panel5.Controls.Add(this.textsend);
			this.Panel5.Controls.Add(this.Enterbutton);
			this.Panel5.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.Panel5.Location = new global::System.Drawing.Point(0, 795);
			this.Panel5.Margin = new global::System.Windows.Forms.Padding(4);
			this.Panel5.Name = "Panel5";
			this.Panel5.Size = new global::System.Drawing.Size(430, 59);
			this.Panel5.TabIndex = 4;
			this.Panel6.BackColor = global::System.Drawing.Color.Transparent;
			this.Panel6.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("Panel6.BackgroundImage");
			this.Panel6.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.Zoom;
			this.Panel6.Controls.Add(this.Panel1);
			this.Panel6.Controls.Add(this.Panel4);
			this.Panel6.Controls.Add(this.Panel3);
			this.Panel6.Controls.Add(this.Panel5);
			this.Panel6.Controls.Add(this.Panel2);
			this.Panel6.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.Panel6.Location = new global::System.Drawing.Point(0, 0);
			this.Panel6.Margin = new global::System.Windows.Forms.Padding(4);
			this.Panel6.Name = "Panel6";
			this.Panel6.Size = new global::System.Drawing.Size(430, 854);
			this.Panel6.TabIndex = 2;
			this.Panel7.BackColor = global::System.Drawing.Color.Black;
			this.Panel7.Controls.Add(this.combosize);
			this.Panel7.Controls.Add(this.Label7);
			this.Panel7.Controls.Add(this.Label6);
			this.Panel7.Controls.Add(this.Qualtibox);
			this.Panel7.Controls.Add(this.Label1);
			this.Panel7.Controls.Add(this.Label5);
			this.Panel7.Controls.Add(this.FPSBOX);
			this.Panel7.Controls.Add(this.Label2);
			this.Panel7.Controls.Add(this.Label4);
			this.Panel7.Controls.Add(this.Dismisbtn);
			this.Panel7.Controls.Add(this.SKtype);
			this.Panel7.Controls.Add(this.DrakeUIAvatar2);
			this.Panel7.Controls.Add(this.checkblock);
			this.Panel7.Controls.Add(this.Save);
			this.Panel7.Controls.Add(this.StopButton);
			this.Panel7.Controls.Add(this.StartButton);
			this.Panel7.Controls.Add(this.Button1);
			this.Panel7.Controls.Add(this.Button7);
			this.Panel7.Controls.Add(this.Button6);
			this.Panel7.Controls.Add(this.Button5);
			this.Panel7.Dock = global::System.Windows.Forms.DockStyle.Right;
			this.Panel7.Location = new global::System.Drawing.Point(430, 0);
			this.Panel7.Margin = new global::System.Windows.Forms.Padding(4);
			this.Panel7.Name = "Panel7";
			this.Panel7.Size = new global::System.Drawing.Size(100, 854);
			this.Panel7.TabIndex = 2;
			this.combosize.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.combosize.DropDownStyle = global::DrakeUI.Framework.UIDropDownStyle.DropDownList;
			this.combosize.FillColor = global::System.Drawing.Color.Black;
			this.combosize.Font = new global::System.Drawing.Font("Roboto", 9f);
			this.combosize.ForeColor = global::System.Drawing.Color.FromArgb(65, 177, 225);
			this.combosize.Location = new global::System.Drawing.Point(0, 578);
			this.combosize.Margin = new global::System.Windows.Forms.Padding(5, 6, 5, 6);
			this.combosize.MinimumSize = new global::System.Drawing.Size(84, 0);
			this.combosize.Name = "combosize";
			this.combosize.Padding = new global::System.Windows.Forms.Padding(0, 0, 30, 0);
			this.combosize.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.combosize.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.combosize.Size = new global::System.Drawing.Size(100, 26);
			this.combosize.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.combosize.StyleCustomMode = true;
			this.combosize.TabIndex = 26;
			this.combosize.Text = "Auto";
			this.combosize.TextAlignment = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.combosize.Visible = false;
			this.Label7.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label7.Font = new global::System.Drawing.Font("Roboto", 10f);
			this.Label7.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Label7.Location = new global::System.Drawing.Point(0, 557);
			this.Label7.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label7.Name = "Label7";
			this.Label7.Size = new global::System.Drawing.Size(100, 21);
			this.Label7.TabIndex = 25;
			this.Label7.Text = "Size(px)";
			this.Label7.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Label7.Visible = false;
			this.Label6.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label6.Font = new global::System.Drawing.Font("Roboto", 10f);
			this.Label6.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Label6.Location = new global::System.Drawing.Point(0, 543);
			this.Label6.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label6.Name = "Label6";
			this.Label6.Size = new global::System.Drawing.Size(100, 14);
			this.Label6.TabIndex = 23;
			this.Label6.Text = "\r\n\r\n\r\n";
			this.Label6.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Qualtibox.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Qualtibox.DropDownStyle = global::DrakeUI.Framework.UIDropDownStyle.DropDownList;
			this.Qualtibox.FillColor = global::System.Drawing.Color.Black;
			this.Qualtibox.Font = new global::System.Drawing.Font("Roboto", 9f);
			this.Qualtibox.ForeColor = global::System.Drawing.Color.FromArgb(65, 177, 225);
			this.Qualtibox.Items.AddRange(new object[]
			{
				"10",
				"20",
				"30",
				"40",
				"50",
				"60",
				"70",
				"80",
				"90",
				"100"
			});
			this.Qualtibox.Location = new global::System.Drawing.Point(0, 517);
			this.Qualtibox.Margin = new global::System.Windows.Forms.Padding(5, 6, 5, 6);
			this.Qualtibox.MinimumSize = new global::System.Drawing.Size(84, 0);
			this.Qualtibox.Name = "Qualtibox";
			this.Qualtibox.Padding = new global::System.Windows.Forms.Padding(0, 0, 30, 0);
			this.Qualtibox.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Qualtibox.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.Qualtibox.Size = new global::System.Drawing.Size(100, 26);
			this.Qualtibox.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.Qualtibox.StyleCustomMode = true;
			this.Qualtibox.TabIndex = 28;
			this.Qualtibox.Text = "100";
			this.Qualtibox.TextAlignment = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.Label5.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label5.Font = new global::System.Drawing.Font("Roboto", 10f);
			this.Label5.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Label5.Location = new global::System.Drawing.Point(0, 478);
			this.Label5.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label5.Name = "Label5";
			this.Label5.Size = new global::System.Drawing.Size(100, 18);
			this.Label5.TabIndex = 22;
			this.Label5.Text = "\r\n\r\n\r\n";
			this.Label5.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.FPSBOX.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.FPSBOX.DropDownStyle = global::DrakeUI.Framework.UIDropDownStyle.DropDownList;
			this.FPSBOX.FillColor = global::System.Drawing.Color.Black;
			this.FPSBOX.Font = new global::System.Drawing.Font("Roboto", 9f);
			this.FPSBOX.ForeColor = global::System.Drawing.Color.FromArgb(65, 177, 225);
			this.FPSBOX.Items.AddRange(new object[]
			{
				"5",
				"10",
				"15",
				"30",
				"60"
			});
			this.FPSBOX.Location = new global::System.Drawing.Point(0, 452);
			this.FPSBOX.Margin = new global::System.Windows.Forms.Padding(5, 6, 5, 6);
			this.FPSBOX.MinimumSize = new global::System.Drawing.Size(84, 0);
			this.FPSBOX.Name = "FPSBOX";
			this.FPSBOX.Padding = new global::System.Windows.Forms.Padding(0, 0, 30, 0);
			this.FPSBOX.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.FPSBOX.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.FPSBOX.Size = new global::System.Drawing.Size(100, 26);
			this.FPSBOX.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.FPSBOX.StyleCustomMode = true;
			this.FPSBOX.TabIndex = 27;
			this.FPSBOX.Text = "5";
			this.FPSBOX.TextAlignment = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.Label4.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label4.Font = new global::System.Drawing.Font("Roboto Black", 10f, global::System.Drawing.FontStyle.Bold);
			this.Label4.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Label4.Location = new global::System.Drawing.Point(0, 421);
			this.Label4.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label4.Name = "Label4";
			this.Label4.Size = new global::System.Drawing.Size(100, 10);
			this.Label4.TabIndex = 21;
			this.Label4.Text = "\r\n\r\n\r\n";
			this.Label4.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Dismisbtn.AvatarSize = 45;
			this.Dismisbtn.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Dismisbtn.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Dismisbtn.FillColor = global::System.Drawing.Color.Transparent;
			this.Dismisbtn.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.Dismisbtn.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.Dismisbtn.Location = new global::System.Drawing.Point(0, 373);
			this.Dismisbtn.Name = "Dismisbtn";
			this.Dismisbtn.Size = new global::System.Drawing.Size(100, 48);
			this.Dismisbtn.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.Dismisbtn.Symbol = 61473;
			this.Dismisbtn.SymbolSize = 25;
			this.Dismisbtn.TabIndex = 29;
			this.Dismisbtn.Text = "DrakeUIAvatar3";
			this.DrakeUIToolTip1.SetToolTip(this.Dismisbtn, "Dismiss Screenshot");
			this.Dismisbtn.Visible = false;
			this.SKtype.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.SKtype.DropDownStyle = global::DrakeUI.Framework.UIDropDownStyle.DropDownList;
			this.SKtype.FillColor = global::System.Drawing.Color.Black;
			this.SKtype.Font = new global::System.Drawing.Font("Roboto", 9f);
			this.SKtype.ForeColor = global::System.Drawing.Color.FromArgb(65, 177, 225);
			this.SKtype.Items.AddRange(new object[]
			{
				"Slient",
				"Normal"
			});
			this.SKtype.Location = new global::System.Drawing.Point(0, 347);
			this.SKtype.Margin = new global::System.Windows.Forms.Padding(5, 6, 5, 6);
			this.SKtype.MinimumSize = new global::System.Drawing.Size(84, 0);
			this.SKtype.Name = "SKtype";
			this.SKtype.Padding = new global::System.Windows.Forms.Padding(0, 0, 30, 0);
			this.SKtype.RectColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.SKtype.RectDisableColor = global::System.Drawing.Color.FromArgb(227, 242, 253);
			this.SKtype.Size = new global::System.Drawing.Size(100, 26);
			this.SKtype.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.SKtype.StyleCustomMode = true;
			this.SKtype.TabIndex = 28;
			this.SKtype.Text = "Slient";
			this.SKtype.TextAlignment = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.DrakeUIAvatar2.AvatarSize = 45;
			this.DrakeUIAvatar2.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.DrakeUIAvatar2.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.DrakeUIAvatar2.FillColor = global::System.Drawing.Color.Transparent;
			this.DrakeUIAvatar2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.DrakeUIAvatar2.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.DrakeUIAvatar2.Location = new global::System.Drawing.Point(0, 299);
			this.DrakeUIAvatar2.Name = "DrakeUIAvatar2";
			this.DrakeUIAvatar2.Size = new global::System.Drawing.Size(100, 48);
			this.DrakeUIAvatar2.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.DrakeUIAvatar2.Symbol = 62024;
			this.DrakeUIAvatar2.TabIndex = 3;
			this.DrakeUIAvatar2.Text = "DrakeUIAvatar2";
			this.DrakeUIToolTip1.SetToolTip(this.DrakeUIAvatar2, "Phone Screen Shot");
			this.checkblock.CheckBoxColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.checkblock.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.checkblock.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.checkblock.Font = new global::System.Drawing.Font("Roboto", 10f);
			this.checkblock.ForeColor = global::System.Drawing.Color.FromArgb(157, 5, 17);
			this.checkblock.Location = new global::System.Drawing.Point(0, 237);
			this.checkblock.Margin = new global::System.Windows.Forms.Padding(4);
			this.checkblock.Name = "checkblock";
			this.checkblock.Padding = new global::System.Windows.Forms.Padding(22, 0, 0, 0);
			this.checkblock.Size = new global::System.Drawing.Size(100, 62);
			this.checkblock.Style = global::DrakeUI.Framework.UIStyle.Custom;
			this.checkblock.StyleCustomMode = true;
			this.checkblock.TabIndex = 30;
			this.checkblock.Text = "Block";
			this.checkblock.TextAlign = global::System.Drawing.ContentAlignment.TopLeft;
			this.DrakeUIToolTip1.SetToolTip(this.checkblock, "Disable the phone screen while controlling");
			this.DrakeUIToolTip1.BackColor = global::System.Drawing.Color.FromArgb(54, 54, 54);
			this.DrakeUIToolTip1.ForeColor = global::System.Drawing.Color.FromArgb(239, 239, 239);
			this.DrakeUIToolTip1.OwnerDraw = true;
			this.Timer1.Interval = 1;
			this.refreshtimer.Interval = 1;
			this.presstimer.Interval = 1000;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(8f, 16f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.Color.Linen;
			this.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.Stretch;
			base.ClientSize = new global::System.Drawing.Size(530, 854);
			base.Controls.Add(this.Panel6);
			base.Controls.Add(this.Panel7);
			this.DoubleBuffered = true;
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
			base.Margin = new global::System.Windows.Forms.Padding(4);
			this.MinimumSize = new global::System.Drawing.Size(443, 603);
			base.Name = "ScreenShoter";
			base.ShowIcon = false;
			this.Text = "ScreenShoter";
			((global::System.ComponentModel.ISupportInitialize)this.Livepicbox).EndInit();
			this.vewpnl.ResumeLayout(false);
			this.Panel8.ResumeLayout(false);
			this.Panel1.ResumeLayout(false);
			this.Panel2.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).EndInit();
			this.Panel4.ResumeLayout(false);
			this.Panel5.ResumeLayout(false);
			this.Panel5.PerformLayout();
			this.Panel6.ResumeLayout(false);
			this.Panel7.ResumeLayout(false);
			base.ResumeLayout(false);
		}

		// Token: 0x0400081F RID: 2079
		private global::System.ComponentModel.Container components;
	}
}
